import {expect,test,type Page} from "@playwright/test";

const state={version:12,week:["gold-chicken-curry","sambal-udang","thai-green-chicken","pad-kra-pao","chicken-cacciatore","mustard-mushroom-chicken","beef-broccoli"],weekStatus:"confirmed",suggestedWeek:null,planMode:"both",allowExtraPrep:true,monthlyPool:[],activePrepIds:["gold","red"],componentBatches:[],manualComponentStock:{gold:{qty:240,unit:"g"},red:{qty:180,unit:"g"}},ingredientStock:{},qualitativeIngredientStock:{},groceryChecked:{},ratings:{},recipeNotes:{},recipeVersions:{},history:[],cookObservations:[],useSoon:{},useSoonAt:{},favourites:{},kitchenReady:true,migrationWarnings:[]};
const none={type:"none",dayIndex:null,mealId:null,mealIds:null,ingredientId:null,componentId:null,componentIds:null,quantity:null,value:null,note:null,author:null};
async function seed(page:Page,person:"josh"|"g"="josh",style:"normal"|"shorter"|"chatty"="normal"){await page.addInitScript(({state,person,style})=>{localStorage.setItem("home-meals-household-v12",JSON.stringify(state));localStorage.setItem("home-meals-welcome-seen-v1","1");localStorage.setItem("home-meals-person-v1",person);localStorage.setItem("home-meals-josh-style-v1",style)}, {state,person,style})}
async function openJosh(page:Page){await page.goto("/",{waitUntil:"domcontentloaded"});await page.waitForTimeout(120);await page.getByRole("button",{name:"Ask Josh"}).last().click();return page.getByRole("dialog",{name:"Ask Josh"})}

test("Ask Josh sends person/style context and renders a prep plan as structured household UI",async({page})=>{
 await seed(page,"g","shorter");let posted:any=null;
 await page.route("**/api/conversation**",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({configured:true,conversation:{id:"thread-g",person:"g"},messages:[{role:"assistant",content:"We were sorting the week earlier.",structured:{responseType:"short_answer",truthLevel:"household_truth",cardContext:"default",text:"We were sorting the week earlier."}}]})}));
 await page.route("**/api/ask-home",async route=>{if(route.request().method()==="GET")return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({configured:true,memory:true})});posted=route.request().postDataJSON();return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({responseType:"prep_plan",truthLevel:"home_verified",cardContext:"prep",text:"Yep. Keep this one simple.",sections:[{title:"Definitely make",items:[{label:"RED",detail:"Tomato base",state:"180 g",href:"/prep/red"},{label:"GOLD",detail:"Curry base",state:"240 g",href:"/prep/gold"}]},{title:"Only if we go Chinese",items:[{label:"WOK-B",detail:"Brown stir-fry sauce",state:"optional",href:"/prep/mids/wok-brown"}]}],mealIds:[],tags:[],href:null,action:null,mutation:none,memoryCandidates:[],recipeDraft:null,conversationId:"thread-g"})})});
 const dialog=await openJosh(page);await expect(dialog).toContainText("We were sorting the week earlier.");await dialog.getByRole("textbox",{name:"Ask Josh"}).fill("What should we prep for those dinners?");await dialog.getByRole("button",{name:"Send"}).click();await expect(dialog).toContainText("Yep. Keep this one simple.");await expect(dialog).toContainText("Definitely make");await expect(dialog).toContainText("Only if we go Chinese");await expect(dialog).toContainText("180 g");expect(posted.person).toBe("g");expect(posted.style).toBe("shorter");expect(posted.conversationId).toBe("thread-g");await expect(page.locator(".hm-josh-head")).toHaveCount(1);
});

test("off-catalog dishes become explicit working drafts and preferences require confirmation",async({page})=>{
 await seed(page,"josh","normal");let memoryWrites=0,draftWrites=0;
 await page.route("**/api/conversation**",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({configured:true,conversation:{id:"thread-j",person:"josh"},messages:[]})}));
 await page.route("**/api/memory",async route=>{if(route.request().method()==="POST"){memoryWrites++;return route.fulfill({status:201,contentType:"application/json",body:JSON.stringify({memory:{id:"m1"}})})}return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({configured:true,memories:[]})})});
 await page.route("**/api/recipe-drafts",async route=>{if(route.request().method()==="POST"){draftWrites++;return route.fulfill({status:201,contentType:"application/json",body:JSON.stringify({draft:{id:"d1"}})})}return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({configured:true,drafts:[]})})});
 await page.route("**/api/ask-home",async route=>{if(route.request().method()==="GET")return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({configured:true,memory:true})});return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({responseType:"recipe_draft",truthLevel:"household_draft",cardContext:"default",text:"Yeah. Vongole doesn't need one of our big bases. I'd keep it fresh.",sections:[{title:"The idea",items:[{label:"No mother base",detail:"Garlic, chilli, olive oil, wine and clam liquor do the work.",state:null,href:null}]}],mealIds:[],tags:["new idea"],href:null,action:null,mutation:none,memoryCandidates:[{subject:"Vongole project",kind:"recipe_project",text:"We're shaping a fresh white-wine vongole with no tomato.",requiresConfirmation:true}],recipeDraft:{title:"Our white-wine vongole",servings:4,ingredients:[{name:"Clams",quantity:1,unit:"kg"},{name:"Spaghetti",quantity:360,unit:"g"}],method:["Purge and clean the clams.","Build the sauce with garlic, chilli and white wine."],notes:["No tomato in the first pass."]},conversationId:"thread-j"})})});
 const dialog=await openJosh(page);await dialog.getByRole("textbox",{name:"Ask Josh"}).fill("Let's make our own vongole. No tomato.");await dialog.getByRole("button",{name:"Send"}).click();await expect(dialog).toContainText("WORKING DRAFT");await expect(dialog).toContainText("Our white-wine vongole");await expect(dialog.getByRole("button",{name:"Remember this"})).toBeVisible();await expect(dialog.getByRole("button",{name:"Save as draft"})).toBeVisible();expect(memoryWrites).toBe(0);expect(draftWrites).toBe(0);await dialog.getByRole("button",{name:"Remember this"}).click();await dialog.getByRole("button",{name:"Save as draft"}).click();await expect.poll(()=>memoryWrites).toBe(1);await expect.poll(()=>draftWrites).toBe(1);expect(await page.locator("body").innerText()).not.toContain("—");
});

test("More exposes Josh vibe, reviewable memory and working recipe drafts",async({page})=>{
 await seed(page,"josh","normal");let deleted=false;
 await page.route("**/api/memory**",async route=>{if(route.request().method()==="DELETE"){deleted=true;return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({deleted:true})})}return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({configured:true,memories:[{id:"m1",subject:"Coriander",kind:"preference",text:"G doesn't like lots of raw coriander.",source_person:"g",updated_at:new Date().toISOString()}]})})});
 await page.route("**/api/recipe-drafts**",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({configured:true,drafts:[{id:"d1",title:"Our white-wine vongole",status:"draft",payload:{},updated_at:new Date().toISOString()}]})}));
 await page.goto("/learn",{waitUntil:"domcontentloaded"});await expect(page.getByText("How much should I say?")).toBeVisible();await page.getByRole("button",{name:/Shorter/}).click();expect(await page.evaluate(()=>localStorage.getItem("home-meals-josh-style-v1"))).toBe("shorter");await page.getByRole("button",{name:/Things I remember/}).click();await expect(page.getByText("G doesn't like lots of raw coriander.")).toBeVisible();await page.getByRole("button",{name:"Forget Coriander"}).click();await expect.poll(()=>deleted).toBe(true);await page.getByRole("button",{name:/Working recipes/}).click();await expect(page.getByText("Our white-wine vongole")).toBeVisible();
});
