import {expect,test,type Page} from "@playwright/test";

const state={version:12,week:["gold-chicken-curry"],weekStatus:"confirmed",suggestedWeek:null,planMode:"both",allowExtraPrep:true,monthlyPool:[],activePrepIds:["gold","red"],componentBatches:[],manualComponentStock:{gold:{qty:240,unit:"g"}},ingredientStock:{},qualitativeIngredientStock:{},groceryChecked:{},ratings:{},recipeNotes:{},recipeVersions:{},history:[],cookObservations:[],useSoon:{},useSoonAt:{},favourites:{},kitchenReady:true,migrationWarnings:[]};
const none={type:"none",dayIndex:null,mealId:null,mealIds:null,ingredientId:null,componentId:null,componentIds:null,quantity:null,value:null,note:null,author:null};
const draft={id:"d21",title:"Creamy miso chicken pasta",status:"draft",payload:{title:"Creamy miso chicken pasta",servings:4,ingredients:[{name:"Chicken thigh",quantity:500,unit:"g"},{name:"Mushrooms",quantity:250,unit:"g"},{name:"Miso",quantity:35,unit:"g"},{name:"Pasta",quantity:360,unit:"g"}],method:["Brown the chicken and mushrooms.","Build the miso cream sauce.","Toss through the pasta."],notes:[]},provenance:{},updated_at:new Date().toISOString()};
const tiny=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9ZQMcAAAAASUVORK5CYII=","base64");
async function seed(page:Page){await page.addInitScript(state=>{localStorage.setItem("home-meals-household-v12",JSON.stringify(state));localStorage.setItem("home-meals-welcome-seen-v1","1");localStorage.setItem("home-meals-person-v1","josh")},state)}
function image(id:string,selected:boolean){return{id,draft_id:"d21",url:`/api/recipe-image/${id}`,mime_type:"image/webp",model:"gpt-image-2.5-sunburst",quality:"max",look:selected?null:"alternate",selected,created_at:new Date().toISOString()}}

test("explicit new-recipe image request saves the draft and executes Josh's image action",async({page})=>{
 await seed(page);let draftWrites=0,imageWrites=0,imageBody:any=null;
 await page.route("**/api/conversation**",r=>r.fulfill({status:200,contentType:"application/json",body:JSON.stringify({configured:true,conversation:{id:"thread-21",person:"josh"},messages:[]})}));
 await page.route("**/api/recipe-drafts",async r=>{if(r.request().method()==="POST"){draftWrites++;return r.fulfill({status:201,contentType:"application/json",body:JSON.stringify({draft})})}return r.fulfill({status:200,contentType:"application/json",body:JSON.stringify({configured:true,drafts:[]})})});
 await page.route("**/api/recipe-image?**",r=>r.fulfill({status:200,contentType:"application/json",body:JSON.stringify({configured:true,selected:null,images:[]})}));
 await page.route("**/api/recipe-image",async r=>{if(r.request().method()==="POST"){imageWrites++;imageBody=r.request().postDataJSON();return r.fulfill({status:201,contentType:"application/json",body:JSON.stringify({image:image("i21",true),selected:true,mode:"initial"})} )}return r.continue()});
 await page.route("**/api/recipe-image/i21",r=>r.fulfill({status:200,contentType:"image/png",body:tiny}));
 await page.route("**/api/ask-home",async r=>{if(r.request().method()==="GET")return r.fulfill({status:200,contentType:"application/json",body:JSON.stringify({configured:true,memory:true})});return r.fulfill({status:200,contentType:"application/json",body:JSON.stringify({responseType:"recipe_draft",truthLevel:"household_draft",cardContext:"default",text:"Yeah. I'd make it creamy but not heavy.",sections:[],mealIds:[],tags:["new idea"],href:null,action:null,mutation:none,memoryCandidates:[],recipeDraft:draft.payload,recipeImageAction:{type:"generate_recipe_image",lookHint:"warm home pasta bowl"},conversationId:"thread-21"})})});
 await page.goto("/",{waitUntil:"domcontentloaded"});await page.waitForTimeout(100);await page.getByRole("button",{name:"Ask Josh"}).last().click();const dialog=page.getByRole("dialog",{name:"Ask Josh"});await dialog.getByRole("textbox",{name:"Ask Josh"}).fill("Make us a creamy miso chicken pasta and generate an image too.");await dialog.getByRole("button",{name:"Send"}).click();await expect.poll(()=>draftWrites).toBe(1);await expect.poll(()=>imageWrites).toBe(1);expect(imageBody.draftId).toBe("d21");expect(imageBody.mode).toBe("initial");expect(imageBody.lookHint).toBe("warm home pasta bowl");await expect(dialog.getByAltText(/generated recipe illustration/)).toBeVisible();await expect(dialog).toContainText("gpt-image-2.5-sunburst");await expect(page.locator(".hm-josh-head")).toHaveCount(1);const preview=dialog.locator(".hm-ask-generated").first();await expect.poll(async()=>{const box=await preview.boundingBox();return box?box.y<await page.evaluate(()=>innerHeight):false}).toBe(true);
});

test("working recipe can try another look without replacing the current image until chosen",async({page})=>{
 await seed(page);let selected=image("hero",true),candidate=image("alt",false),posts:string[]=[],patches=0;
 await page.route("**/api/recipe-drafts**",r=>r.fulfill({status:200,contentType:"application/json",body:JSON.stringify({configured:true,draft})}));
 await page.route("**/api/recipe-image/hero",r=>r.fulfill({status:200,contentType:"image/png",body:tiny}));await page.route("**/api/recipe-image/alt",r=>r.fulfill({status:200,contentType:"image/png",body:tiny}));
 await page.route("**/api/recipe-image?**",r=>r.fulfill({status:200,contentType:"application/json",body:JSON.stringify({configured:true,selected,images:[selected,candidate]})}));
 await page.route("**/api/recipe-image",async r=>{const method=r.request().method();if(method==="POST"){const body=r.request().postDataJSON();posts.push(body.mode);return r.fulfill({status:201,contentType:"application/json",body:JSON.stringify({image:body.mode==="candidate"?candidate:image("replacement",true),selected:body.mode!=="candidate",mode:body.mode})})}if(method==="PATCH"){patches++;selected={...candidate,selected:true};return r.fulfill({status:200,contentType:"application/json",body:JSON.stringify({image:selected})})}return r.continue()});
 await page.goto("/cook/drafts/d21",{waitUntil:"domcontentloaded"});await expect(page.getByAltText(/generated recipe illustration/)).toHaveAttribute("src","/api/recipe-image/hero");await page.getByRole("button",{name:"Try another look"}).click();await expect.poll(()=>posts).toContain("candidate");await expect(page.getByText("NEW LOOK")).toBeVisible();await expect(page.getByRole("button",{name:"Use this image"})).toBeVisible();await page.getByRole("button",{name:"Keep current"}).click();await expect(page.getByAltText(/generated recipe illustration/)).toHaveAttribute("src","/api/recipe-image/hero");await page.getByRole("button",{name:"Try another look"}).click();await page.getByRole("button",{name:"Use this image"}).click();await expect.poll(()=>patches).toBe(1);await expect(page.getByAltText(/generated recipe illustration/)).toHaveAttribute("src","/api/recipe-image/alt");await page.getByRole("button",{name:"Regenerate"}).click();await expect.poll(()=>posts).toContain("replace");const unchanged=await page.evaluate(()=>JSON.parse(localStorage.getItem("home-meals-household-v12")||"{}").manualComponentStock?.gold?.qty);expect(unchanged).toBe(240);
});

test("Cook shelf uses the selected generated image for working recipes",async({page})=>{
 await seed(page);const hero=image("hero",true);
 await page.route("**/api/recipe-drafts",r=>r.fulfill({status:200,contentType:"application/json",body:JSON.stringify({configured:true,drafts:[draft]})}));
 await page.route("**/api/recipe-image?**",r=>r.fulfill({status:200,contentType:"application/json",body:JSON.stringify({configured:true,selected:hero,images:[hero]})}));
 await page.route("**/api/recipe-image/hero",r=>r.fulfill({status:200,contentType:"image/png",body:tiny}));
 await page.goto("/cook",{waitUntil:"domcontentloaded"});const card=page.getByRole("link",{name:/Creamy miso chicken pasta/});await expect(card).toBeVisible();await expect(card.getByAltText(/generated recipe illustration/)).toHaveAttribute("src","/api/recipe-image/hero");await expect(page.locator(".hm-josh-head")).toHaveCount(1);
});
