"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { researchedWeek } from "@/data/meal-plan";
import { mealBySlug } from "@/data/meals-researched";
import { mothers } from "@/data/foundation";
import { MealVisual } from "./MealVisual";
import { Icon } from "./Icons";

export function HomeDashboard(){
 const [hydrated,setHydrated]=useState(false);const[shopProgress,setShopProgress]=useState(0);const[prepProgress,setPrepProgress]=useState(0);
 useEffect(()=>{setHydrated(true);try{const shop=JSON.parse(localStorage.getItem("home-meals-foundation-shop-v2")||"{}");const shopDone=Object.values(shop).filter(Boolean).length;setShopProgress(shopDone);const hot=JSON.parse(localStorage.getItem("home-meals-prep-day-hot")||"{}");const mods=JSON.parse(localStorage.getItem("home-meals-prep-day-modifiers")||"{}");setPrepProgress(Object.values({...hot,...Object.fromEntries(Object.entries(mods).map(([k,v])=>[`m-${k}`,v]))}).filter(Boolean).length)}catch{}},[]);
 const dayIndex=useMemo(()=>hydrated?(new Date().getDay()+6)%7:0,[hydrated]);
 const today=researchedWeek[dayIndex];const meal=mealBySlug(today.slug)!;
 return <><section className="today-hero"><div className="today-copy"><span className="eyebrow">{hydrated?`${today.day.toUpperCase()} · TODAY`:`FIRST OPERATING WEEK`}</span><h2>{meal.title}</h2><p>{meal.subtitle}</p><div className="today-stats"><span>{meal.time} min</span><span>{meal.method}</span>{meal.parts.map(x=><span key={x.code}>{x.code} ×{x.count}</span>)}</div><div className="button-row"><Link href={`/cook/${meal.slug}/cook`} className="primary-button">Start cooking <Icon name="arrow"/></Link><Link href={`/cook/${meal.slug}`} className="secondary-button">Recipe</Link></div></div><MealVisual slug={meal.slug} title={meal.title}/></section><section className="operating-cards"><Link href="/prep/groceries"><span className="op-num">01</span><div><small>FOUNDATION SHOP</small><strong>{shopProgress?`${shopProgress} items checked`:`Start the first shop`}</strong><p>First Run and Full Library lists.</p></div><b>→</b></Link><Link href="/prep/day"><span className="op-num">02</span><div><small>PREP STATUS</small><strong>{prepProgress?`${prepProgress} stages checked`:`Two-session First Run`}</strong><p>Six mothers + core modifiers.</p></div><b>→</b></Link><Link href="/plan"><span className="op-num">03</span><div><small>THIS WEEK</small><strong>7 researched dinners</strong><p>Swap anything without breaking the system.</p></div><b>→</b></Link></section><section className="home-week"><div className="section-heading"><div><span className="eyebrow">THIS WEEK</span><h2>One main dinner a day.</h2></div><Link href="/plan">Plan & shop →</Link></div><div className="home-week-grid">{researchedWeek.map((x,i)=>{const m=mealBySlug(x.slug)!;return <Link href={`/cook/${m.slug}`} key={x.day} className={i===dayIndex?"active":""}><span>{x.day}</span><strong>{m.title}</strong><small>{m.time} min</small></Link>})}</div></section><section className="home-foundation"><div className="section-heading"><div><span className="eyebrow">FREEZER FOUNDATION</span><h2>Six mothers underneath everything.</h2></div><Link href="/prep">Open foundation →</Link></div><div className="home-foundation-row">{mothers.map(m=><Link href={`/prep/${m.slug}`} key={m.code} style={{"--tone":m.tone} as React.CSSProperties}><i/><span>{m.code}</span><strong>{m.name}</strong><small>{m.portionMl} ml</small></Link>)}</div></section></>
}
