"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {usePathname} from "next/navigation";
import {getHouseholdPerson,householdPersonLabel,setHouseholdPerson,type HouseholdPerson} from "@/lib/device-profile";
import styles from "./HouseholdSync.module.css";

const STATE_KEY="home-meals-household-v11";
const META_KEY="home-meals-sync-meta-v1";
const PENDING_KEY="home-meals-sync-pending-v1";
type Remote={version:number;payload:Record<string,unknown>|null;updatedAt:string|null};
type Meta={version:number;lastSyncedPayload:string};
type SyncState="checking"|"disabled"|"needs-code"|"needs-person"|"ready"|"syncing"|"conflict"|"deferred"|"error";

function readMeta():Meta{try{const raw=localStorage.getItem(META_KEY);if(!raw)return {version:0,lastSyncedPayload:""};const p=JSON.parse(raw);return {version:Number(p.version)||0,lastSyncedPayload:typeof p.lastSyncedPayload==="string"?p.lastSyncedPayload:""}}catch{return {version:0,lastSyncedPayload:""}}}
function writeMeta(meta:Meta){localStorage.setItem(META_KEY,JSON.stringify(meta))}
function localPayload(){try{const raw=localStorage.getItem(STATE_KEY);if(!raw)return null;const value=JSON.parse(raw) as Record<string,unknown>;const payload={...value,mealPhotos:[]};return {raw,payload,syncRaw:JSON.stringify(payload)}}catch{return null}}
function mergedRemote(remote:Record<string,unknown>,localRaw:string|null){let photos:unknown[]=[];try{const local=localRaw?JSON.parse(localRaw):null;if(Array.isArray(local?.mealPhotos))photos=local.mealPhotos}catch{}return JSON.stringify({...remote,mealPhotos:photos})}

export function HouseholdSync(){
 const path=usePathname();const cooking=/^\/cook\/[^/]+\/cook$/.test(path);
 const[state,setState]=useState<SyncState>("checking");const[code,setCode]=useState("");const[person,setPerson]=useState<HouseholdPerson|null>(null);const[message,setMessage]=useState("");const[conflict,setConflict]=useState<Remote|null>(null);const busy=useRef(false);
 const applyRemote=useCallback((remote:Remote)=>{if(!remote.payload)return;const local=localStorage.getItem(STATE_KEY);const merged=mergedRemote(remote.payload,local);const syncRaw=JSON.stringify({...remote.payload,mealPhotos:[]});writeMeta({version:remote.version,lastSyncedPayload:syncRaw});if(cooking){localStorage.setItem(PENDING_KEY,JSON.stringify(remote));setState("deferred");return}localStorage.setItem(STATE_KEY,merged);localStorage.removeItem(PENDING_KEY);window.location.reload()},[cooking]);
 const fetchRemote=useCallback(async()=>{const res=await fetch("/api/household",{cache:"no-store"});if(res.status===401){setState("needs-code");return null}if(res.status===503){setState("disabled");return null}if(!res.ok)throw new Error("sync_read");return await res.json() as Remote},[]);
 const pushLocal=useCallback(async(baseVersion:number,current:{payload:Record<string,unknown>;syncRaw:string})=>{const res=await fetch("/api/household",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({baseVersion,payload:current.payload})});if(res.status===409)return "conflict" as const;if(res.status===401){setState("needs-code");return null}if(!res.ok)throw new Error("sync_write");const saved=await res.json() as Remote;writeMeta({version:saved.version,lastSyncedPayload:current.syncRaw});setState("ready");return saved},[]);
 const syncNow=useCallback(async()=>{if(busy.current||!navigator.onLine)return;busy.current=true;try{const remote=await fetchRemote();if(!remote)return;const current=localPayload();if(!current){setState("ready");return}const meta=readMeta();if(remote.version===0||!remote.payload){const saved=await pushLocal(0,current);if(saved==="conflict")setState("conflict");return}if(meta.version===0){if(current.syncRaw===JSON.stringify({...remote.payload,mealPhotos:[]})){writeMeta({version:remote.version,lastSyncedPayload:current.syncRaw});setState("ready")}else applyRemote(remote);return}const localChanged=current.syncRaw!==meta.lastSyncedPayload;const remoteChanged=remote.version!==meta.version;if(localChanged&&remoteChanged){setConflict(remote);setState("conflict");return}if(localChanged){const saved=await pushLocal(meta.version,current);if(saved==="conflict"){const fresh=await fetchRemote();if(fresh){setConflict(fresh);setState("conflict")}}return}if(remoteChanged){applyRemote(remote);return}setState("ready")}catch{setState("error")}finally{busy.current=false}},[applyRemote,fetchRemote,pushLocal]);
 useEffect(()=>{let timer:ReturnType<typeof setInterval>|undefined;let live=true;(async()=>{try{const currentPerson=getHouseholdPerson();setPerson(currentPerson);const res=await fetch("/api/household/session",{cache:"no-store"});const info=await res.json() as {configured?:boolean;authenticated?:boolean};if(!live)return;if(!info.configured){setState("disabled");return}if(!info.authenticated){setState("needs-code");return}if(!currentPerson){setState("needs-person");return}const pending=localStorage.getItem(PENDING_KEY);if(pending&&!cooking){try{applyRemote(JSON.parse(pending) as Remote);return}catch{localStorage.removeItem(PENDING_KEY)}}await syncNow();timer=setInterval(syncNow,5000)}catch{setState("error")}})();const wake=()=>syncNow();window.addEventListener("focus",wake);window.addEventListener("online",wake);return()=>{live=false;if(timer)clearInterval(timer);window.removeEventListener("focus",wake);window.removeEventListener("online",wake)}},[applyRemote,cooking,syncNow]);
 const connect=async(e:React.FormEvent)=>{e.preventDefault();setMessage("");if(!person){setMessage("Choose whether this phone is Josh or G first.");return}try{const res=await fetch("/api/household/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code})});if(!res.ok){setMessage(res.status===401?"That household code doesn’t match.":"Couldn’t connect this device.");return}setHouseholdPerson(person);setCode("");setState("ready");await syncNow()}catch{setMessage("Couldn’t connect this device.")}};
 const savePerson=async(selected:HouseholdPerson)=>{setHouseholdPerson(selected);setPerson(selected);setMessage("");setState("ready");await syncNow()};
 const useThisDevice=async()=>{if(!conflict)return;const current=localPayload();if(!current)return;setState("syncing");try{const saved=await pushLocal(conflict.version,current);if(saved==="conflict"){setMessage("Household changed again. Try once more.");setState("conflict");return}setConflict(null)}catch{setState("error")}};
 const useHousehold=()=>{if(conflict){const chosen=conflict;setConflict(null);applyRemote(chosen)}};
 if(state==="disabled"||state==="checking"||state==="ready")return null;
 if(state==="syncing")return <div className={styles.status} role="status">Syncing Josh + G…</div>;
 if(state==="deferred")return <div className={styles.wrap}><div className={styles.card}><strong>Household updated</strong><small>The other device changed Home Meals. It will apply after this cooking session.</small></div></div>;
 if(state==="needs-person")return <div className={styles.wrap}><div className={styles.card}><strong>Who is using this device?</strong><small>This only sets the local author for notes, ratings and recipe changes. Kitchen and Plan stay shared.</small><div className={styles.people}><button className={person==="josh"?styles.chosen:""} onClick={()=>setPerson("josh")}><b>J</b><span>Josh</span></button><button className={person==="g"?styles.chosen:""} onClick={()=>setPerson("g")}><b>G</b><span>G</span></button></div><button className={styles.primaryWide} disabled={!person} onClick={()=>person&&savePerson(person)}>Continue as {householdPersonLabel(person)}</button></div></div>;
 if(state==="needs-code")return <div className={styles.wrap}><form className={styles.card} onSubmit={connect}><strong>Connect Josh + G</strong><small>Choose this phone, then enter the private household code once.</small><div className={styles.people}><button type="button" className={person==="josh"?styles.chosen:""} onClick={()=>setPerson("josh")}><b>J</b><span>Josh</span></button><button type="button" className={person==="g"?styles.chosen:""} onClick={()=>setPerson("g")}><b>G</b><span>G</span></button></div><div className={styles.row}><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Household code" aria-label="Household code" autoCapitalize="characters"/><button className={styles.primary}>Connect</button></div>{message&&<div className={styles.error}>{message}</div>}</form></div>;
 if(state==="conflict")return <div className={styles.wrap}><div className={styles.card}><strong>Two devices changed Home Meals</strong><small>Choose which state should win. Nothing has been overwritten yet.</small><div className={styles.actions}><button className={styles.secondary} onClick={useHousehold}>Use household</button><button className={styles.primary} onClick={useThisDevice}>Use this device</button></div>{message&&<div className={styles.error}>{message}</div>}</div></div>;
 return <div className={styles.wrap}><div className={styles.card}><strong>Household sync needs attention</strong><small>Your local Home Meals still works and will retry automatically.</small></div></div>;
}
