"use client";
import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { defaultWeek, getIngredient, initialComponentStock, initialIngredientStock, recipes, shoppingNeedsForWeek } from "@/data/home-data";
import { batchOutputMl, componentConsumptionMl, ingredientConsumptionExact, prepNeedsForWeekMl } from "@/data/stock-math";

type Rating={josh?:number;g?:number;note?:string};
type RecipeNote={author:"josh"|"g"|"home";text:string;at:string};
type CookEvent={mealId:string;at:string};
export type PrepBatch={componentId:string;outputMl:number;remainingMl:number;at:string};
type HouseholdState={
 week:string[]; monthlyPool:string[]; componentStock:Record<string,number>; ingredientStock:Record<string,number>; groceryChecked:Record<string,boolean>; ratings:Record<string,Rating>; recipeNotes:Record<string,RecipeNote[]>; history:CookEvent[]; prepBatches:PrepBatch[]; kitchenReady:boolean; useSoon:Record<string,boolean>; favourites:Record<string,boolean>; storageIssue:boolean;
 prepNeeds:ReturnType<typeof prepNeedsForWeekMl>; shoppingNeeds:ReturnType<typeof shoppingNeedsForWeek>;
 setDay:(index:number,mealId:string)=>void; toggleMonthlyPool:(recipeId:string)=>void; setComponent:(id:string,ml:number)=>void; setIngredient:(id:string,qty:number)=>void; toggleGrocery:(id:string)=>void; makeBatch:(id:string)=>void; cookMeal:(mealId:string)=>void; rateMeal:(mealId:string,who:"josh"|"g",value:number)=>void; noteMeal:(mealId:string,note:string,author?:"josh"|"g"|"home")=>void; confirmKitchen:()=>void; toggleUseSoon:(id:string)=>void; toggleFavourite:(recipeId:string)=>void; clearStorageIssue:()=>void; resetDemo:()=>void;
};
const Ctx=createContext<HouseholdState|null>(null);
const KEY="home-meals-household-v7";
const LEGACY_KEYS=["home-meals-household-v6","home-meals-household-v5","home-meals-household-v4","home-meals-linked-v3"];
const validRecipeIds=new Set(recipes.map(x=>x.id));
const defaultMonthPool=[...defaultWeek,"gold-chana-masala","curry-laksa","rempah-chicken-rendang","teriyaki-salmon","gochujang-chicken","beef-ragu","pesto-salmon","harissa-chicken-traybake","chipotle-chicken-bowl"].filter((id,i,a)=>validRecipeIds.has(id)&&a.indexOf(id)===i);

function consumeRecordedBatches(prev:PrepBatch[],needs:{id:string;ml:number}[]){
 const next=prev.map(b=>({...b,remainingMl:b.remainingMl??b.outputMl}));
 for(const need of needs){let left=need.ml;const order=next.map((b,i)=>({b,i})).filter(x=>x.b.componentId===need.id&&(x.b.remainingMl??x.b.outputMl)>0).sort((a,b)=>new Date(a.b.at).getTime()-new Date(b.b.at).getTime());for(const {i} of order){if(left<=0)break;const available=next[i].remainingMl??next[i].outputMl;const used=Math.min(available,left);next[i]={...next[i],remainingMl:Math.max(0,available-used)};left-=used}}
 return next;
}

export function HouseholdStateProvider({children}:{children:React.ReactNode}){
 const [week,setWeek]=useState<string[]>(defaultWeek);const [monthlyPool,setMonthlyPool]=useState<string[]>(defaultMonthPool);const [componentStock,setComponentStock]=useState<Record<string,number>>(initialComponentStock);const [ingredientStock,setIngredientStock]=useState<Record<string,number>>(initialIngredientStock);const [groceryChecked,setGroceryChecked]=useState<Record<string,boolean>>({});const [ratings,setRatings]=useState<Record<string,Rating>>({});const [recipeNotes,setRecipeNotes]=useState<Record<string,RecipeNote[]>>({});const [history,setHistory]=useState<CookEvent[]>([]);const [prepBatches,setPrepBatches]=useState<PrepBatch[]>([]);const [kitchenReady,setKitchenReady]=useState(false);const [useSoon,setUseSoon]=useState<Record<string,boolean>>({});const [favourites,setFavourites]=useState<Record<string,boolean>>({});const [hydrated,setHydrated]=useState(false);const[storageIssue,setStorageIssue]=useState(false);
 useEffect(()=>{try{const exact=localStorage.getItem(KEY);const legacy=!exact?LEGACY_KEYS.map(k=>localStorage.getItem(k)).find(Boolean):null;const raw=exact??legacy;if(raw){const s=JSON.parse(raw);if(Array.isArray(s.week)){const migrated=s.week.filter((x:string)=>validRecipeIds.has(x));setWeek(migrated.length===7?migrated:defaultWeek)}if(Array.isArray(s.monthlyPool)){const pool=s.monthlyPool.filter((x:string)=>validRecipeIds.has(x));if(pool.length)setMonthlyPool(pool)}if(exact){if(s.componentStock)setComponentStock({...initialComponentStock,...s.componentStock});if(s.ingredientStock)setIngredientStock({...initialIngredientStock,...s.ingredientStock});setKitchenReady(!!s.kitchenReady);if(s.prepBatches)setPrepBatches((s.prepBatches as any[]).map(b=>({...b,remainingMl:b.remainingMl??b.outputMl})));if(s.useSoon)setUseSoon(s.useSoon);if(s.favourites)setFavourites(s.favourites)}if(s.groceryChecked)setGroceryChecked(s.groceryChecked);if(s.ratings){setRatings(s.ratings);const notes:Record<string,RecipeNote[]>={};for(const [id,r] of Object.entries(s.ratings as Record<string,Rating>)){if(r.note)notes[id]=[{author:"home",text:r.note,at:new Date().toISOString()}]}setRecipeNotes(s.recipeNotes??notes)}if(s.recipeNotes)setRecipeNotes(s.recipeNotes);if(s.history)setHistory((s.history as CookEvent[]).filter(x=>validRecipeIds.has(x.mealId)))}}catch{setStorageIssue(true)}finally{setHydrated(true)}},[]);
 useEffect(()=>{if(!hydrated)return;try{localStorage.setItem(KEY,JSON.stringify({version:7,week,monthlyPool,componentStock,ingredientStock,groceryChecked,ratings,recipeNotes,history,prepBatches,kitchenReady,useSoon,favourites}));setStorageIssue(false)}catch{setStorageIssue(true)}},[hydrated,week,monthlyPool,componentStock,ingredientStock,groceryChecked,ratings,recipeNotes,history,prepBatches,kitchenReady,useSoon,favourites]);
 const prepNeeds=useMemo(()=>prepNeedsForWeekMl(week,componentStock),[week,componentStock]);const shoppingNeeds=useMemo(()=>shoppingNeedsForWeek(week,ingredientStock),[week,ingredientStock]);
 const setDay=(index:number,mealId:string)=>{if(!validRecipeIds.has(mealId))return;setWeek(prev=>prev.map((x,i)=>i===index?mealId:x));setGroceryChecked({})};
 const toggleMonthlyPool=(recipeId:string)=>{if(!validRecipeIds.has(recipeId))return;setMonthlyPool(prev=>prev.includes(recipeId)?prev.filter(id=>id!==recipeId):[...prev,recipeId])};
 const setComponent=(id:string,ml:number)=>{setComponentStock(prev=>({...prev,[id]:Math.max(0,ml)}));setKitchenReady(true)};
 const setIngredient=(id:string,qty:number)=>{setIngredientStock(prev=>({...prev,[id]:Math.max(0,qty)}));setKitchenReady(true);if(qty<=0)setUseSoon(prev=>({...prev,[id]:false}))};
 const toggleGrocery=(id:string)=>setGroceryChecked(prev=>({...prev,[id]:!prev[id]}));
 const makeBatch=(id:string)=>{const ml=batchOutputMl(id);if(!ml)return;const now=new Date().toISOString();setComponentStock(prev=>({...prev,[id]:(prev[id]??0)+ml}));setPrepBatches(prev=>[{componentId:id,outputMl:ml,remainingMl:ml,at:now},...prev].slice(0,100));setKitchenReady(true)};
 const cookMeal=(mealId:string)=>{if(!validRecipeIds.has(mealId))return;const componentNeeds=componentConsumptionMl(mealId);setComponentStock(prev=>{const next={...prev};for(const req of componentNeeds)next[req.id]=Math.max(0,(next[req.id]??0)-req.ml);return next});setPrepBatches(prev=>consumeRecordedBatches(prev,componentNeeds));setIngredientStock(prev=>{const next={...prev};for(const req of ingredientConsumptionExact(mealId)){const def=getIngredient(req.id);if(def?.tracking==="state")continue;next[req.id]=Math.max(0,(next[req.id]??0)-req.qty)}return next});setHistory(prev=>[{mealId,at:new Date().toISOString()},...prev].slice(0,100));setKitchenReady(true)};
 const rateMeal=(mealId:string,who:"josh"|"g",value:number)=>setRatings(prev=>({...prev,[mealId]:{...(prev[mealId]??{}),[who]:value}}));
 const noteMeal=(mealId:string,note:string,author:"josh"|"g"|"home"="home")=>{const clean=note.trim();setRatings(prev=>({...prev,[mealId]:{...(prev[mealId]??{}),note:clean}}));if(clean)setRecipeNotes(prev=>({...prev,[mealId]:[{author,text:clean,at:new Date().toISOString()},...(prev[mealId]??[])].slice(0,20)}))};
 const confirmKitchen=()=>setKitchenReady(true);const toggleUseSoon=(id:string)=>setUseSoon(prev=>({...prev,[id]:!prev[id]}));const toggleFavourite=(recipeId:string)=>{if(!validRecipeIds.has(recipeId))return;setFavourites(prev=>({...prev,[recipeId]:!prev[recipeId]}))};const clearStorageIssue=()=>setStorageIssue(false);
 const resetDemo=()=>{setWeek(defaultWeek);setMonthlyPool(defaultMonthPool);setComponentStock(initialComponentStock);setIngredientStock(initialIngredientStock);setGroceryChecked({});setRatings({});setRecipeNotes({});setHistory([]);setPrepBatches([]);setKitchenReady(false);setUseSoon({});setFavourites({})};
 const value={week,monthlyPool,componentStock,ingredientStock,groceryChecked,ratings,recipeNotes,history,prepBatches,kitchenReady,useSoon,favourites,storageIssue,prepNeeds,shoppingNeeds,setDay,toggleMonthlyPool,setComponent,setIngredient,toggleGrocery,makeBatch,cookMeal,rateMeal,noteMeal,confirmKitchen,toggleUseSoon,toggleFavourite,clearStorageIssue,resetDemo};
 return <Ctx.Provider value={value}>{hydrated?children:<div className="hm-boot-v5" aria-label="Loading Home Meals"><div><span>♥</span><strong>Home Meals</strong><small>Josh + G</small><i/></div></div>}</Ctx.Provider>
}
export function useHousehold(){const v=useContext(Ctx);if(!v)throw new Error("useHousehold must be inside HouseholdStateProvider");return v}
