"use client";
import {createContext,useContext,useEffect,useMemo,useState} from "react";
import {defaultWeek,recipes} from "@/data/home-data";
import {quantity,type Quantity} from "@/data/food-quantity";
import {prepNeedsForRecipesV2,createMeasuredPrepBatchV2} from "@/data/food-engine-v2";
import {shoppingNeedsForPlanV2} from "@/data/ingredient-engine-v2";
import type {RecipeCookObservationV2} from "@/data/calibration-v2";
import {addMeasuredBatchV12,componentStockV12,cookRecipeV12,migrateHouseholdV11ToV12,recordCookObservationV12,setIngredientStockV12,setManualComponentStockV12,type HouseholdStateV12,type RatingV12,type RecipeNoteV12,type RecipeVersionV12} from "@/data/household-v12";

const KEY="home-meals-household-v12",LEGACY_KEY="home-meals-household-v11";const validRecipeIds=new Set(recipes.map(x=>x.id));const defaultMonthPool=[...defaultWeek,"gold-chana-masala","curry-laksa","rempah-chicken-rendang","teriyaki-salmon","gochujang-chicken","beef-ragu","pesto-salmon","harissa-chicken-traybake","chipotle-chicken-bowl"].filter((id,i,a)=>validRecipeIds.has(id)&&a.indexOf(id)===i);const defaults={week:defaultWeek,monthlyPool:defaultMonthPool};
export type HouseholdStateV12Context={state:HouseholdStateV12;componentStock:ReturnType<typeof componentStockV12>;prepNeeds:ReturnType<typeof prepNeedsForRecipesV2>;shoppingNeeds:ReturnType<typeof shoppingNeedsForPlanV2>;setDay:(index:number,recipeId:string)=>void;setComponentObserved:(componentId:string,value:Quantity)=>void;setIngredientObserved:(ingredientId:string,value:Quantity)=>void;recordMeasuredBatch:(componentId:string,measuredOutput:Quantity,recipeVersion:string)=>void;cookMeal:(recipeId:string,variantId?:string)=>void;recordCookObservation:(observation:RecipeCookObservationV2)=>void;rateMeal:(recipeId:string,who:"josh"|"g",value:number)=>void;noteMeal:(recipeId:string,text:string,author?:"josh"|"g"|"home")=>void;promoteRecipeVersion:(recipeId:string,summary:string,author?:"josh"|"g"|"home")=>void;toggleUseSoon:(ingredientId:string)=>void;toggleFavourite:(recipeId:string)=>void;toggleGrocery:(ingredientId:string)=>void;clearMigrationWarnings:()=>void;resetV12:()=>void};
const Ctx=createContext<HouseholdStateV12Context|null>(null);function freshState(){return migrateHouseholdV11ToV12({},defaults)}
function restoreV12(raw:string):HouseholdStateV12|null{try{const parsed=JSON.parse(raw);if(parsed?.version!==12||!Array.isArray(parsed.week)||!parsed.manualComponentStock||!parsed.ingredientStock)return null;return{...parsed,cookObservations:Array.isArray(parsed.cookObservations)?parsed.cookObservations:[]} as HouseholdStateV12}catch{return null}}
function uid(prefix:string){return`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`}
export function HouseholdStateV12Provider({children}:{children:React.ReactNode}){const[state,setState]=useState<HouseholdStateV12>(freshState),[hydrated,setHydrated]=useState(false);
 useEffect(()=>{try{const exact=localStorage.getItem(KEY),restored=exact?restoreV12(exact):null;if(restored)setState(restored);else{const legacyRaw=localStorage.getItem(LEGACY_KEY),legacy=legacyRaw?JSON.parse(legacyRaw):{},migrated=migrateHouseholdV11ToV12(legacy,defaults);setState(migrated);localStorage.setItem(KEY,JSON.stringify(migrated))}}catch{setState(freshState())}finally{setHydrated(true)}},[]);useEffect(()=>{if(hydrated)localStorage.setItem(KEY,JSON.stringify(state))},[hydrated,state]);
 const componentStock=useMemo(()=>componentStockV12(state),[state.componentBatches,state.manualComponentStock]),prepNeeds=useMemo(()=>prepNeedsForRecipesV2(state.week,componentStock),[state.week,componentStock]),shoppingNeeds=useMemo(()=>shoppingNeedsForPlanV2(state.week.map(recipeId=>({recipeId})),state.ingredientStock),[state.week,state.ingredientStock]);
 const setDay=(index:number,recipeId:string)=>{if(index<0||index>6||!validRecipeIds.has(recipeId))return;setState(prev=>({...prev,week:prev.week.map((x,i)=>i===index?recipeId:x),groceryChecked:{}}))},setComponentObserved=(componentId:string,value:Quantity)=>setState(prev=>setManualComponentStockV12(prev,componentId,value)),setIngredientObserved=(ingredientId:string,value:Quantity)=>setState(prev=>setIngredientStockV12(prev,ingredientId,value));
 const recordMeasuredBatch=(componentId:string,measuredOutput:Quantity,recipeVersion:string)=>setState(prev=>addMeasuredBatchV12(prev,createMeasuredPrepBatchV2({batchId:uid(componentId),componentId,measuredOutput,producedAt:new Date().toISOString(),recipeVersion}))),cookMeal=(recipeId:string,variantId?:string)=>{if(validRecipeIds.has(recipeId))setState(prev=>cookRecipeV12(prev,recipeId,variantId))},recordCookObservation=(observation:RecipeCookObservationV2)=>setState(prev=>recordCookObservationV12(prev,observation));
 const rateMeal=(recipeId:string,who:"josh"|"g",value:number)=>{if(!validRecipeIds.has(recipeId)||!Number.isFinite(value))return;setState(prev=>{const rating:RatingV12={...(prev.ratings[recipeId]??{}),[who]:Math.max(1,Math.min(5,value))};return{...prev,ratings:{...prev.ratings,[recipeId]:rating}}})},noteMeal=(recipeId:string,text:string,author:"josh"|"g"|"home"="home")=>{const clean=text.trim();if(!validRecipeIds.has(recipeId)||!clean)return;setState(prev=>{const note:RecipeNoteV12={author,text:clean.slice(0,500),at:new Date().toISOString()};return{...prev,recipeNotes:{...prev.recipeNotes,[recipeId]:[note,...(prev.recipeNotes[recipeId]??[])].slice(0,20)}}})},promoteRecipeVersion=(recipeId:string,summary:string,author:"josh"|"g"|"home"="home")=>{const clean=summary.trim();if(!validRecipeIds.has(recipeId)||!clean)return;setState(prev=>{const current=prev.recipeVersions[recipeId]??[],version:RecipeVersionV12={number:(current[0]?.number??1)+1,summary:clean.slice(0,500),author,at:new Date().toISOString()};return{...prev,recipeVersions:{...prev.recipeVersions,[recipeId]:[version,...current].slice(0,20)}}})};
 const toggleUseSoon=(ingredientId:string)=>setState(prev=>{const next=!prev.useSoon[ingredientId],useSoon={...prev.useSoon,[ingredientId]:next},useSoonAt={...prev.useSoonAt};if(next)useSoonAt[ingredientId]=new Date().toISOString();else delete useSoonAt[ingredientId];return{...prev,useSoon,useSoonAt}}),toggleFavourite=(recipeId:string)=>{if(validRecipeIds.has(recipeId))setState(prev=>({...prev,favourites:{...prev.favourites,[recipeId]:!prev.favourites[recipeId]}}))},toggleGrocery=(ingredientId:string)=>setState(prev=>({...prev,groceryChecked:{...prev.groceryChecked,[ingredientId]:!prev.groceryChecked[ingredientId]}})),clearMigrationWarnings=()=>setState(prev=>({...prev,migrationWarnings:[]})),resetV12=()=>setState(freshState());
 const value={state,componentStock,prepNeeds,shoppingNeeds,setDay,setComponentObserved,setIngredientObserved,recordMeasuredBatch,cookMeal,recordCookObservation,rateMeal,noteMeal,promoteRecipeVersion,toggleUseSoon,toggleFavourite,toggleGrocery,clearMigrationWarnings,resetV12};if(!hydrated)return<div aria-label="Loading Home Meals"/>;return<Ctx.Provider value={value}>{children}</Ctx.Provider>}
export function useHouseholdV12(){const value=useContext(Ctx);if(!value)throw new Error("useHouseholdV12 must be inside HouseholdStateV12Provider");return value}export{quantity};
