"use client";
import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { defaultWeek, getIngredient, initialComponentStock, initialIngredientStock, recipes, shoppingNeedsForWeek } from "@/data/home-data";
import { batchOutputMl, componentConsumptionMl, ingredientConsumptionExact, prepNeedsForWeekMl } from "@/data/stock-math";

type Rating={josh?:number;g?:number;note?:string};
type RecipeNote={author:"josh"|"g"|"home";text:string;at:string};
export type RecipeVersion={number:number;summary:string;author:"josh"|"g"|"home";at:string};
export type MealPhoto={mealId:string;dataUrl:string;at:string};
type CookEvent={mealId:string;at:string};
export type PrepBatch={componentId:string;outputMl:number;remainingMl:number;at:string};
type HouseholdState={
 week:string[]; monthlyPool:string[]; componentStock:Record<string,number>; ingredientStock:Record<string,number>; groceryChecked:Record<string,boolean>; ratings:Record<string,Rating>; recipeNotes:Record<string,RecipeNote[]>; recipeVersions:Record<string,RecipeVersion[]>; mealPhotos:MealPhoto[]; history:CookEvent[]; prepBatches:PrepBatch[]; kitchenReady:boolean; useSoon:Record<string,boolean>; favourites:Record<string,boolean>; storageIssue:boolean;
 prepNeeds:ReturnType<typeof prepNeedsForWeekMl>; shoppingNeeds:ReturnType<typeof shoppingNeedsForWeek>;
 setDay:(index:number,mealId:string)=>void; toggleMonthlyPool:(recipeId:string)=>void; setComponent:(id:string,ml:number)=>void; setIngredient:(id:string,qty:number)=>void; toggleGrocery:(id:string)=>void; makeBatch:(id:string)=>void; cookMeal:(mealId:string)=>void; rateMeal:(mealId:string,who:"josh"|"g",value:number)=>void; noteMeal:(mealId:string,note:string,author?:"josh"|"g"|"home")=>void; promoteRecipeVersion:(mealId:string,summary:string,author?:"josh"|"g"|"home")=>void; saveMealPhoto:(mealId:string,dataUrl:string)=>void; confirmKitchen:()=>void; toggleUseSoon:(id:string)=>void; toggleFavourite:(recipeId:string)=>void; clearStorageIssue:()=>void; resetDemo:()=>void;
};
const Ctx=createContext<HouseholdState|null>(null);
const KEY="home-meals-household-v10";
const LEGACY_KEYS=["home-meals-household-v9","home-meals-household-v8","home-meals-household-v7","home-meals-household-v6","home-meals-household-v5","home-meals-household-v4","home-meals-linked-v3"];
const validRecipeIds=new Set(recipes.map(x=>x.id));
const defaultMonthPool=[...defaultWeek,"gold-chana-masala","curry-laksa","rempah-chicken-rendang","teriyaki-salmon","gochujang-chicken","beef-ragu","pesto-salmon","harissa-chicken-traybake","chipotle-chicken-bowl"].filter((id,i,a)=>validRecipeIds.has(id)&&a.indexOf(id)===i);

function consumeRecordedBatches(prev:PrepBatch[],needs:{id:string;ml:number}[]){
 const next=prev.map(b=>({...b,remainingMl:b.remainingMl??b.outputMl}));
 for(const need of needs){let left=need.ml;const order=next.map((b,i)=>({b,i})).filter(x=>x.b.componentId===need.id&&(x.b.remainingMl??x.b.outputMl)>0).sort((a,b)=>new Date(a.b.at).getTime()-new Date(b.b.at).getTime());for(const {i} of order){if(left<=0)break;const available=next[i].remainingMl??next[i].outputMl;const used=Math.min(available,left);next[i]={...next[i],remainingMl:Math.max(0,available-used)};left-=used}}
 return next;
}
function safeRecord(value:unknown){return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,any>:null}

export function HouseholdStateProvider({children}:{children:React.ReactNode}){
 const [week,setWeek]=useState<string[]>(defaultWeek);const [monthlyPool,setMonthlyPool]=useState<string[]>(defaultMonthPool);const [componentStock,setComponentStock]=useState<Record<string,number>>(initialComponentStock);const [ingredientStock,setIngredientStock]=useState<Record<string,number>>(initialIngredientStock);const [groceryChecked,setGroceryChecked]=useState<Record<string,boolean>>({});const [ratings,setRatings]=useState<Record<string,Rating>>({});const [recipeNotes,setRecipeNotes]=useState<Record<string,RecipeNote[]>>({});const [recipeVersions,setRecipeVersions]=useState<Record<string,RecipeVersion[]>>({});const [mealPhotos,setMealPhotos]=useState<MealPhoto[]>([]);const [history,setHistory]=useState<CookEvent[]>([]);const [prepBatches,setPrepBatches]=useState<PrepBatch[]>([]);const [kitchenReady,setKitchenReady]=useState(false);const [useSoon,setUseSoon]=useState<Record<string,boolean>>({});const [favourites,setFavourites]=useState<Record<string,boolean>>({});const [hydrated,setHydrated]=useState(false);const[storageIssue,setStorageIssue]=useState(false);
 useEffect(()=>{try{const exact=localStorage.getItem(KEY);let legacyRaw:string|null=null;if(!exact){for(const k of LEGACY_KEYS){const candidate=localStorage.getItem(k);if(candidate){legacyRaw=candidate;break}}}const raw=exact??legacyRaw;if(raw){const s=JSON.parse(raw);if(Array.isArray(s.week)){const migrated=s.week.filter((x:string)=>validRecipeIds.has(x));setWeek(migrated.length===7?migrated:defaultWeek)}if(Array.isArray(s.monthlyPool)){const pool=s.monthlyPool.filter((x:string)=>validRecipeIds.has(x));if(pool.length)setMonthlyPool(pool)}const components=safeRecord(s.componentStock);if(components)setComponentStock({...initialComponentStock,...components});const ingredientValues=safeRecord(s.ingredientStock);if(ingredientValues)setIngredientStock({...initialIngredientStock,...ingredientValues});setKitchenReady(!!s.kitchenReady);if(Array.isArray(s.prepBatches))setPrepBatches((s.prepBatches as any[]).filter(b=>b&&typeof b.componentId==="string"&&Number.isFinite(Number(b.outputMl))).map(b=>({...b,outputMl:Number(b.outputMl),remainingMl:Number(b.remainingMl??b.outputMl),at:b.at||new Date().toISOString()})).slice(0,100));const soon=safeRecord(s.useSoon);if(soon)setUseSoon(soon as Record<string,boolean>);const fav=safeRecord(s.favourites);if(fav)setFavourites(fav as Record<string,boolean>);const checked=safeRecord(s.groceryChecked);if(checked)setGroceryChecked(checked as Record<string,boolean>);const savedRatings=safeRecord(s.ratings);if(savedRatings){setRatings(savedRatings as Record<string,Rating>);const notes:Record<string,RecipeNote[]>={};for(const [id,r] of Object.entries(savedRatings as Record<string,Rating>)){if(validRecipeIds.has(id)&&r.note)notes[id]=[{author:"home",text:r.note,at:new Date().toISOString()}]}setRecipeNotes(safeRecord(s.recipeNotes) as Record<string,RecipeNote[]>??notes)}const savedNotes=safeRecord(s.recipeNotes);if(savedNotes)setRecipeNotes(savedNotes as Record<string,RecipeNote[]>);const savedVersions=safeRecord(s.recipeVersions);if(savedVersions){const versions:Record<string,RecipeVersion[]>={};for(const [id,value] of Object.entries(savedVersions)){if(!validRecipeIds.has(id)||!Array.isArray(value))continue;versions[id]=(value as any[]).filter(v=>v&&Number.isFinite(Number(v.number))&&typeof v.summary==="string").map(v=>({number:Math.max(2,Number(v.number)),summary:String(v.summary),author:v.author==="josh"||v.author==="g"?v.author:"home",at:v.at||new Date().toISOString()})).sort((a,b)=>b.number-a.number).slice(0,20)}setRecipeVersions(versions)}if(Array.isArray(s.mealPhotos))setMealPhotos((s.mealPhotos as any[]).filter(p=>p&&validRecipeIds.has(p.mealId)&&typeof p.dataUrl==="string"&&p.dataUrl.startsWith("data:image/")&&p.dataUrl.length<900000).map(p=>({mealId:p.mealId,dataUrl:p.dataUrl,at:p.at||new Date().toISOString()})).slice(0,8));if(Array.isArray(s.history))setHistory((s.history as CookEvent[]).filter(x=>x&&validRecipeIds.has(x.mealId)).slice(0,100))}}catch{setStorageIssue(true)}finally{setHydrated(true)}},[]);
 useEffect(()=>{if(!hydrated)return;try{localStorage.setItem(KEY,JSON.stringify({version:10,week,monthlyPool,componentStock,ingredientStock,groceryChecked,ratings,recipeNotes,recipeVersions,mealPhotos,history,prepBatches,kitchenReady,useSoon,favourites}));for(const old of LEGACY_KEYS)localStorage.removeItem(old);setStorageIssue(false)}catch{setStorageIssue(true)}},[hydrated,week,monthlyPool,componentStock,ingredientStock,groceryChecked,ratings,recipeNotes,recipeVersions,mealPhotos,history,prepBatches,kitchenReady,useSoon,favourites]);
 const prepNeeds=useMemo(()=>prepNeedsForWeekMl(week,componentStock),[week,componentStock]);const shoppingNeeds=useMemo(()=>shoppingNeedsForWeek(week,ingredientStock),[week,ingredientStock]);
 const setDay=(index:number,mealId:string)=>{if(!validRecipeIds.has(mealId))return;setWeek(prev=>prev.map((x,i)=>i===index?mealId:x));setGroceryChecked({})};
 const toggleMonthlyPool=(recipeId:string)=>{if(!validRecipeIds.has(recipeId))return;setMonthlyPool(prev=>prev.includes(recipeId)?prev.filter(id=>id!==recipeId):[...prev,recipeId])};
 const setComponent=(id:string,ml:number)=>{setComponentStock(prev=>({...prev,[id]:Math.max(0,ml)}));setKitchenReady(true)};
 const setIngredient=(id:string,qty:number)=>{setIngredientStock(prev=>({...prev,[id]:Math.max(0,qty)}));setKitchenReady(true);if(qty<=0)setUseSoon(prev=>({...prev,[id]:false}))};
 const toggleGrocery=(id:string)=>setGroceryChecked(prev=>({...prev,[id]:!prev[id]}));
 const makeBatch=(id:string)=>{const ml=batchOutputMl(id);if(!ml)return;const now=new Date().toISOString();setComponentStock(prev=>({...prev,[id]:(prev[id]??0)+ml}));setPrepBatches(prev=>[{componentId:id,outputMl:ml,remainingMl:ml,at:now},...prev].slice(0,100));setKitchenReady(true)};
 const cookMeal=(mealId:string)=>{if(!validRecipeIds.has(mealId))return;const componentNeeds=componentConsumptionMl(mealId);setComponentStock(prev=>{const next={...prev};for(const req of componentNeeds)next[req.id]=Math.max(0,(next[req.id]??0)-req.ml);return next});setPrepBatches(prev=>consumeRecordedBatches(prev,componentNeeds));setIngredientStock(prev=>{const next={...prev};for(const req of ingredientConsumptionExact(mealId)){const def=getIngredient(req.id);if(def?.tracking==="state")continue;next[req.id]=Math.max(0,(next[req.id]??0)-req.qty)}return next});setHistory(prev=>[{mealId,at:new Date().toISOString()},...prev].slice(0,100));setKitchenReady(true)};
 const rateMeal=(mealId:string,who:"josh"|"g",value:number)=>setRatings(prev=>({...prev,[mealId]:{...(prev[mealId]??{}),[who]:value}}));
 const noteMeal=(mealId:string,note:string,author:"josh"|"g"|"home"="home")=>{const clean=note.trim();setRatings(prev=>({...prev,[mealId]:{...(prev[mealId]??{}),note:clean}}));if(clean)setRecipeNotes(prev=>({...prev,[mealId]:[{author,text:clean,at:new Date().toISOString()},...(prev[mealId]??[])].slice(0,20)}))};
 const promoteRecipeVersion=(mealId:string,summary:string,author:"josh"|"g"|"home"="home")=>{const clean=summary.trim();if(!clean||!validRecipeIds.has(mealId))return;setRecipeVersions(prev=>{const existing=prev[mealId]??[];if(existing[0]?.summary===clean)return prev;const number=(existing[0]?.number??1)+1;return {...prev,[mealId]:[{number,summary:clean,author,at:new Date().toISOString()},...existing].slice(0,20)}})};
 const saveMealPhoto=(mealId:string,dataUrl:string)=>{if(!validRecipeIds.has(mealId)||!dataUrl.startsWith("data:image/")||dataUrl.length>=900000){setStorageIssue(true);return}setMealPhotos(prev=>[{mealId,dataUrl,at:new Date().toISOString()},...prev].slice(0,8))};
 const confirmKitchen=()=>setKitchenReady(true);const toggleUseSoon=(id:string)=>setUseSoon(prev=>({...prev,[id]:!prev[id]}));const toggleFavourite=(recipeId:string)=>{if(!validRecipeIds.has(recipeId))return;setFavourites(prev=>({...prev,[recipeId]:!prev[recipeId]}))};const clearStorageIssue=()=>setStorageIssue(false);
 const resetDemo=()=>{setWeek(defaultWeek);setMonthlyPool(defaultMonthPool);setComponentStock(initialComponentStock);setIngredientStock(initialIngredientStock);setGroceryChecked({});setRatings({});setRecipeNotes({});setRecipeVersions({});setMealPhotos([]);setHistory([]);setPrepBatches([]);setKitchenReady(false);setUseSoon({});setFavourites({})};
 const value={week,monthlyPool,componentStock,ingredientStock,groceryChecked,ratings,recipeNotes,recipeVersions,mealPhotos,history,prepBatches,kitchenReady,useSoon,favourites,storageIssue,prepNeeds,shoppingNeeds,setDay,toggleMonthlyPool,setComponent,setIngredient,toggleGrocery,makeBatch,cookMeal,rateMeal,noteMeal,promoteRecipeVersion,saveMealPhoto,confirmKitchen,toggleUseSoon,toggleFavourite,clearStorageIssue,resetDemo};
 return <Ctx.Provider value={value}>{hydrated?children:<div className="hm-boot-v5" aria-label="Loading Home Meals"><div><span>♥</span><strong>Home Meals</strong><small>Josh + G</small><i/></div></div>}</Ctx.Provider>
}
export function useHousehold(){const v=useContext(Ctx);if(!v)throw new Error("useHousehold must be inside HouseholdStateProvider");return v}
