"use client";
import { useHousehold } from "./HouseholdState";
import { getIngredient, ingredients, midBases, motherBases } from "@/data/home-graph";

export function KitchenV2(){
 const h=useHousehold();
 return <div className="hm-screen hm-kitchen-screen">
  <header className="hm-page-head"><div><p className="hm-kicker">KITCHEN</p><h1>What we actually have.</h1><p>Enough detail to plan well. Not warehouse management.</p></div><button className="hm-reset" onClick={h.resetDemo}>Reset demo</button></header>
  <section className="hm-kitchen-summary"><div><span>FRIDGE / PANTRY</span><strong>{ingredients.filter(x=>(h.ingredientStock[x.id]??0)>0).length}</strong><small>tracked ingredients</small></div><div><span>MOTHERS</span><strong>{motherBases.reduce((n,x)=>n+(h.componentStock[x.id]??0),0)}</strong><small>portions in freezer</small></div><div><span>MIDS</span><strong>{midBases.reduce((n,x)=>n+(h.componentStock[x.id]??0),0)}</strong><small>directional portions</small></div><div><span>THIS WEEK</span><strong>{h.prepNeeds.length}</strong><small>prep gaps</small></div></section>
  <section className="hm-section"><div className="hm-section-title"><div><span>CORE BASES</span><h2>Mother stock</h2></div><small>Tap + / − as you prep or use them</small></div><div className="hm-inventory-grid">{motherBases.map(x=><article key={x.id} style={{"--tone":x.tone} as React.CSSProperties}><i/><div><strong>{x.code}</strong><span>{x.name}</span><small>{x.portionLabel}</small></div><div className="hm-qty"><button onClick={()=>h.setComponent(x.id,(h.componentStock[x.id]??0)-1)}>−</button><b>{h.componentStock[x.id]??0}</b><button onClick={()=>h.setComponent(x.id,(h.componentStock[x.id]??0)+1)}>+</button></div></article>)}</div></section>
  <section className="hm-section"><div className="hm-section-title"><div><span>MID-BASES</span><h2>Multipliers</h2></div><small>16 linked mids</small></div><div className="hm-inventory-grid mids">{midBases.map(x=><article key={x.id} style={{"--tone":x.tone} as React.CSSProperties}><i/><div><strong>{x.code}</strong><span>{x.name}</span><small>{x.parentMotherIds.length?`with ${x.parentMotherIds.map(id=>motherBases.find(m=>m.id===id)?.code).join(" + ")}`:"standalone"}</small></div><div className="hm-qty"><button onClick={()=>h.setComponent(x.id,(h.componentStock[x.id]??0)-1)}>−</button><b>{h.componentStock[x.id]??0}</b><button onClick={()=>h.setComponent(x.id,(h.componentStock[x.id]??0)+1)}>+</button></div></article>)}</div></section>
  <section className="hm-section"><div className="hm-section-title"><div><span>FRIDGE + PANTRY</span><h2>Ingredient stock</h2></div><small>exact where it matters</small></div><div className="hm-ingredient-table">{ingredients.map(x=><label key={x.id}><span><strong>{x.name}</strong><small>{x.category}</small></span><input type="number" min="0" value={h.ingredientStock[x.id]??0} onChange={e=>h.setIngredient(x.id,Number(e.target.value)||0)}/><b>{x.defaultUnit}</b></label>)}</div></section>
 </div>
}
