"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { meals, midBases, motherBases } from "@/data/home-graph";
export function MealBuilderV2(){
 const [mother,setMother]=useState("all");const [mid,setMid]=useState("all");
 const matches=useMemo(()=>meals.filter(m=>(mother==="all"||m.motherIds.includes(mother))&&(mid==="all"||m.midIds.includes(mid))),[mother,mid]);
 return <div className="hm-screen hm-builder-screen"><header className="hm-page-head"><div><p className="hm-kicker">BUILD FROM WHAT WE HAVE</p><h1>Find real combinations.</h1><p>This never invents a meal. It only returns recipes already linked to the selected mother/mid.</p></div><Link href="/cook" className="hm-btn secondary">Our recipes</Link></header><section className="hm-builder-controls"><label><span>Mother base</span><select value={mother} onChange={e=>setMother(e.target.value)}><option value="all">Any mother</option>{motherBases.map(x=><option value={x.id} key={x.id}>{x.code} · {x.name}</option>)}</select></label><label><span>Mid-base</span><select value={mid} onChange={e=>setMid(e.target.value)}><option value="all">Any mid</option>{midBases.map(x=><option value={x.id} key={x.id}>{x.code} · {x.name}</option>)}</select></label></section><section className="hm-builder-result"><div className="hm-section-title"><div><span>MATCHES</span><h2>{matches.length} actual recipes</h2></div></div><div className="hm-recipe-grid">{matches.map(m=><Link href={`/cook/${m.id}`} key={m.id} className="hm-recipe-card">{m.image?<img src={m.image} alt=""/>:<div className="hm-meal-placeholder big">{m.title[0]}</div>}<div className="hm-recipe-card-copy"><div className="hm-code-row">{m.motherIds.map(id=><b key={id}>{motherBases.find(x=>x.id===id)?.code}</b>)}{m.midIds.map(id=><b key={id}>{midBases.find(x=>x.id===id)?.code}</b>)}</div><h2>{m.title}</h2><p>{m.subtitle}</p><footer><span>{m.cuisine}</span><span>{m.minutes} min</span></footer></div></Link>)}</div>{!matches.length&&<div className="hm-covered-card">No approved recipe uses that exact combination yet. That means we research one before adding it; the builder does not fabricate food.</div>}</section></div>
}
