"use client";
import { useMemo, useState } from "react";
import { bases } from "@/data/home-meals";

const proteins=["Chicken thigh","Salmon","Prawns","Minced beef","Tofu"];
const carbs=["Basmati rice","Pasta","Potatoes","Noodles","Flatbread"];
const finishers: Record<string,string[]>={RED:["Basil + Parmesan","Cream + chilli","Cumin + paprika"],GOLD:["Coconut milk","Cream + butter","Yoghurt","Spinach"],ASIAN:["Soy + honey","Coconut + lime","Oyster + sesame"],DARK:["Mushroom + cream","Dijon + butter","Miso + butter"],GREEN:["Parmesan + lemon","Cream","Butter + herbs"],FIRE:["Cumin + yoghurt","Smoked paprika + lemon","Cream"]};
const names:Record<string,string>={"Chicken thigh|GOLD":"Coconut curry chicken","Chicken thigh|DARK":"Mustard pan-sauce chicken","Chicken thigh|RED":"Tomato chicken","Salmon|GREEN":"Herb salmon","Salmon|DARK":"Miso butter salmon","Prawns|ASIAN":"Ginger soy prawns","Prawns|FIRE":"Spicy pepper prawns","Minced beef|RED":"Quick beef ragù","Tofu|GOLD":"GOLD tofu masala"};
export function MealBuilder(){const[protein,setProtein]=useState(proteins[0]);const[base,setBase]=useState("GOLD");const[finisher,setFinisher]=useState(finishers.GOLD[0]);const[carb,setCarb]=useState(carbs[0]);const result=useMemo(()=>names[`${protein}|${base}`]??`${base} ${protein.toLowerCase()} bowl`,[protein,base]);const selectBase=(value:string)=>{setBase(value);setFinisher(finishers[value][0])};return <div className="meal-builder"><div className="builder-stage"><span className="eyebrow">BUILD-A-MEAL</span><h2>{result}</h2><p>{protein} + {base} + {finisher} + {carb}</p><div className="builder-plate"><span>{base}</span><i/><b>{protein}</b></div><div className="builder-result-meta"><span>~20–30 min</span><span>Fresh-cooked</span><span>Freezer-first</span></div></div><div className="builder-controls"><label><span>01 · Protein</span><select value={protein} onChange={e=>setProtein(e.target.value)}>{proteins.map(x=><option key={x}>{x}</option>)}</select></label><label><span>02 · Base</span><div className="builder-base-buttons">{bases.map(b=><button key={b.code} onClick={()=>selectBase(b.code)} className={base===b.code?"active":""} style={{"--base-color":b.tone} as React.CSSProperties}><i/>{b.code}</button>)}</div></label><label><span>03 · Finisher</span><select value={finisher} onChange={e=>setFinisher(e.target.value)}>{finishers[base].map(x=><option key={x}>{x}</option>)}</select></label><label><span>04 · Carb</span><select value={carb} onChange={e=>setCarb(e.target.value)}>{carbs.map(x=><option key={x}>{x}</option>)}</select></label></div></div>}
