"use client";
import Link from "next/link";
import { useHousehold } from "./HouseholdState";
import { getIngredient, getMeal, meals, midBases, motherBases } from "@/data/home-graph";
const days=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
export function PlanV2(){
 const h=useHousehold();
 const grouped=h.shoppingNeeds.reduce<Record<string,typeof h.shoppingNeeds>>((acc,x)=>{const cat=getIngredient(x.id).category;(acc[cat]??=[]).push(x);return acc},{});
 const codeLine=(id:string)=>{const m=getMeal(id);return [...m.motherIds.map(x=>motherBases.find(b=>b.id===x)?.code),...m.midIds.map(x=>midBases.find(b=>b.id===x)?.code)].filter(Boolean).join(" + ")||"Fresh-only"};
 const rated=Object.entries(h.ratings).filter(([,v])=>v.josh||v.g).slice(0,4);
 return <div className="hm-screen hm-plan-screen">
  <header className="hm-page-head"><div><p className="hm-kicker">THIS WEEK</p><h1>Plan & shop</h1><p>Change a meal and groceries + prep update automatically.</p></div><div className="hm-household-avatar"><span>J</span><span>G</span></div></header>
  <section className="hm-section hm-week-plan"><div className="hm-section-title"><div><span>YOUR WEEK</span><h2>Seven linked dinners</h2></div><small>Recipes → stock → shop → prep</small></div><div className="hm-plan-cards">{h.week.map((id,i)=>{const m=getMeal(id);return <article key={`${id}-${i}`}>{m.image?<img src={m.image} alt=""/>:<div className="hm-meal-placeholder">{m.title[0]}</div>}<span>{days[i]}</span><strong>{m.title}</strong><small>{m.minutes}m · {codeLine(id)}</small><select value={id} onChange={e=>h.setDay(i,e.target.value)} aria-label={`Change ${days[i]} meal`}>{meals.map(opt=><option key={opt.id} value={opt.id}>{opt.title}</option>)}</select></article>})}</div></section>
  <section className="hm-plan-split"><article><div className="hm-section-title"><div><span>PREP GENERATED FROM WEEK</span><h2>{h.prepNeeds.length?`${h.prepNeeds.length} gaps to fill`:"Prep covered"}</h2></div><Link href="/prep">Prep →</Link></div>{h.prepNeeds.length?h.prepNeeds.slice(0,5).map(x=>{const item=motherBases.find(b=>b.id===x.id)??midBases.find(b=>b.id===x.id);return <div className="hm-linked-row" key={x.id}><i style={{background:item?.tone}}/><div><strong>{item?.code} · {item?.name}</strong><small>need {x.needed} · have {x.onHand} · short {x.short}</small></div></div>}):<p className="hm-empty">Everything the plan needs is already prepped.</p>}</article><article><div className="hm-section-title"><div><span>WHY IT CHANGED</span><h2>One shared state</h2></div></div><p className="hm-linked-explainer">Swap a meal above and this screen recalculates both fresh groceries and freezer prep. Nothing below is a separate list.</p><div className="hm-flow-mini"><span>7 meals</span><b>→</b><span>ingredients</span><b>−</b><span>kitchen</span><b>=</b><span>shop</span></div><div className="hm-flow-mini"><span>7 meals</span><b>→</b><span>bases</span><b>−</b><span>freezer</span><b>=</b><span>prep</span></div></article></section>
  <section className="hm-section"><div className="hm-section-title"><div><span>SHOPPING LIST</span><h2>{h.shoppingNeeds.length} real top-ups</h2></div><small>Plan requirements minus kitchen stock</small></div>{h.shoppingNeeds.length?<div className="hm-shopping-grid">{Object.entries(grouped).map(([cat,items])=><article key={cat}><h3>{cat}</h3>{items.map(x=><label key={x.id} className={h.groceryChecked[x.id]?"done":""}><input type="checkbox" checked={!!h.groceryChecked[x.id]} onChange={()=>h.toggleGrocery(x.id)}/><span><strong>{getIngredient(x.id).name}</strong><small>Buy {Math.ceil(x.qty)} {x.unit} · need {Math.ceil(x.required)} · home {Math.ceil(x.onHand)}</small></span></label>)}</article>)}</div>:<div className="hm-covered-card">✓ This week's meals are fully covered by current kitchen stock.</div>}</section>
  <section className="hm-section"><div className="hm-section-title"><div><span>HOUSEHOLD RATINGS</span><h2>What we actually liked</h2></div><Link href="/cook">Our recipes →</Link></div>{rated.length?<div className="hm-ratings-strip">{rated.map(([id,v])=><div key={id}><strong>{getMeal(id).title}</strong><span>Josh {v.josh??"—"}/5 · G {v.g??"—"}/5</span></div>)}</div>:<div className="hm-covered-card">Cook a meal, then Josh + G can rate it separately. Those ratings will shape future planning.</div>}</section>
 </div>
}
