"use client";
import Link from "next/link";
import { useHousehold } from "./HouseholdState";
import { midBases, motherBases } from "@/data/home-graph";
import { foundationImages } from "@/data/foundation-assets";
export function PrepDayV2(){
 const h=useHousehold();const item=(id:string)=>motherBases.find(x=>x.id===id)??midBases.find(x=>x.id===id);
 return <div className="hm-screen hm-prepday-screen"><header className="hm-page-head"><div><p className="hm-kicker">PREP DAY</p><h1>Only what this week needs.</h1><p>Plan drives prep. Prep updates Kitchen. No separate lists.</p></div><Link href="/prep" className="hm-btn secondary">Back to Prep</Link></header><section className="hm-prepday-hero">{foundationImages.prepDay&&<img src={foundationImages.prepDay} alt="Prep day"/>}<div><span>THIS SESSION</span><h2>{h.prepNeeds.length?`${h.prepNeeds.length} linked prep jobs`:"Nothing required"}</h2><p>{h.prepNeeds.length?"Finish a batch and log it here. The freezer stock updates immediately.":"Your freezer already covers the planned week."}</p></div></section>{h.prepNeeds.length?<section className="hm-prep-queue">{h.prepNeeds.map((x,i)=>{const p=item(x.id)!;return <article key={x.id} style={{"--tone":p.tone} as React.CSSProperties}><span>{String(i+1).padStart(2,"0")}</span><i/><div><strong>{p.code} · {p.name}</strong><small>Need {x.needed} · have {x.onHand} · short {x.short}</small><p>Make one starter batch ×{p.batchYield}; extra portions stay as future stock.</p></div><button onClick={()=>h.makeBatch(x.id)}>Batch done +{p.batchYield}</button></article>})}</section>:<div className="hm-covered-card">✓ No prep required for the current week.</div>}<section className="hm-prepday-rules"><article><b>1</b><div><strong>Start long cooks first</strong><p>DARK, CLEAR, RED, ONION and other slow foundations go first when they are actually needed.</p></div></article><article><b>2</b><div><strong>Group equipment</strong><p>Paste-and-fry work can share blender/wok cleanup. Stocks and oven reductions share passive time.</p></div></article><article><b>3</b><div><strong>Cool, portion, label</strong><p>Name / portion / date. The physical freezer and the app should say the same thing.</p></div></article></section></div>
}
