"use client";

import { useEffect, useState } from "react";
import { Icon } from "./Icons";

const modes=["Fridge","Freezer","Receipt","Ingredient","Prep check","Meal"];
const freezerDetected={RED:5,GOLD:7,REMPAH:4,SAMBAL:3,DARK:8,BLOND:5,"THAI-G":3,"WOK-B":4,GG:8};
const fridgeDetected=[{name:"Chicken thighs",qty:3,unit:"portions"},{name:"Eggs",qty:8,unit:"eggs"},{name:"Parmesan",qty:1,unit:"piece"},{name:"Cooking cream",qty:1,unit:"carton"},{name:"Broccoli",qty:2,unit:"heads"},{name:"Mushrooms",qty:1,unit:"box"}];

export function ScanClient(){
 const[mode,setMode]=useState("Fridge");const[preview,setPreview]=useState<string|null>(null);const[analysed,setAnalysed]=useState(false);const[confirmed,setConfirmed]=useState(false);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 const onFile=(file?:File)=>{if(!file)return;if(preview)URL.revokeObjectURL(preview);setPreview(URL.createObjectURL(file));setAnalysed(false);setConfirmed(false)};
 const confirm=()=>{try{if(mode==="Freezer")localStorage.setItem("hm-foundation-stock",JSON.stringify(freezerDetected));if(mode==="Fridge")localStorage.setItem("hm-fridge",JSON.stringify(fridgeDetected));if(mode==="Receipt"){const existing=JSON.parse(localStorage.getItem("hm-receipts")||"[]");existing.push({date:"11 Sep",retailer:"Village Grocer",items:["Chicken thigh 1 kg","Cooking cream ×2","Tomatoes 1 kg"],total:null});localStorage.setItem("hm-receipts",JSON.stringify(existing))}setConfirmed(true)}catch{setConfirmed(false)}};
 const result=mode==="Freezer"?["RED ×5","GOLD ×7","REMPAH ×4","SAMBAL ×3","DARK ×8","BLOND ×5","THAI-G ×3","WOK-B ×4","GG ×8"]:mode==="Fridge"?["Chicken portions ×3","Eggs ×8","Parmesan ×1","Cream ×1","Broccoli ×2","Mushrooms ×1"]:mode==="Ingredient"?["Likely: coriander / cilantro","Confidence: simulated V1"]:mode==="Prep check"?["Surface looks reduced rather than watery","Use the recipe's visual cue as authority","Vision coaching is simulated in V1"]:mode==="Meal"?["Meal photo recorded locally in V1 preview","Automatic recipe matching arrives with vision"]:[];
 return <div className="scan-experience"><div className="scan-v1-note"><strong>V1 camera surface</strong><p>You can take a real photo now. The interpretation shown below is deliberately simulated; confirming Fridge or Freezer updates the real local state used by this device. Live vision comes in Phase 2.</p></div><div className="mode-strip">{modes.map(m=><button key={m} className={mode===m?"active":""} onClick={()=>{setMode(m);setAnalysed(false);setConfirmed(false)}}>{m}</button>)}</div><div className="camera-stage">{preview?<img src={preview} alt="Selected kitchen photo"/>:<><div className="camera-reticle"><i/><i/><i/><i/></div><div className="camera-copy"><Icon name="camera" size={34}/><strong>Show Home your {mode.toLowerCase()}</strong><span>Use the rear camera or choose an existing photo.</span></div></>}<label className="camera-shutter"><input type="file" accept="image/*" capture="environment" onChange={e=>onFile(e.target.files?.[0])}/><span/></label></div>{preview&&<button className="primary-button analyse-button" onClick={()=>{setAnalysed(true);setConfirmed(false)}}><Icon name="spark"/> Analyse {mode}</button>}{analysed&&<div className="scan-result"><div className="scan-result-head"><span className="eyebrow">SIMULATED INTERPRETATION · V1</span><h3>{mode} preview</h3></div>{mode==="Receipt"?<><p>Village Grocer · 11 Sep</p><ul><li>Chicken thigh 1 kg <strong>RM18.90</strong></li><li>Cooking cream ×2 <strong>RM14.60</strong></li><li>Tomatoes 1 kg <strong>RM7.90</strong></li></ul></>:<div className="detected-chips">{result.map(x=><span key={x}>{x}</span>)}</div>}{(["Fridge","Freezer","Receipt"].includes(mode))?<button className={confirmed?"secondary-button confirmed-action":"secondary-button"} onClick={confirm} disabled={confirmed}><Icon name="check"/>{confirmed?" Updated on this device":" Confirm & update local state"}</button>:<p className="phase-note">This mode is preview-only until live vision coaching is connected.</p>}</div>}</div>
}
