"use client";
import { useState } from "react";
import Link from "next/link";
import { useHousehold } from "./HouseholdState";

const modes=["Fridge","Freezer","Receipt","Prep check"] as const;
export function ScanV2(){
 const h=useHousehold(); const [mode,setMode]=useState<(typeof modes)[number]>("Fridge"); const [preview,setPreview]=useState<string>(); const [analysed,setAnalysed]=useState(false); const [confirmed,setConfirmed]=useState(false);
 const analyse=()=>{setAnalysed(true);setConfirmed(false)};
 const confirm=()=>{if(mode==="Fridge"){h.setIngredient("mushrooms",300);h.setIngredient("cream",250);h.setIngredient("broccoli",350)}else if(mode==="Freezer"){h.setComponent("gold",4);h.setComponent("red",3);h.setComponent("dark",5)}else if(mode==="Receipt"){h.setIngredient("chicken-thigh",1200);h.setIngredient("coriander",30);h.setIngredient("coconut-milk",800)}setConfirmed(true)};
 return <div className="hm-screen hm-scan-screen"><header className="hm-page-head"><div><p className="hm-kicker">SHOW HOME</p><h1>Camera input</h1><p>V1 keeps the interaction and state flow real; image understanding remains a placeholder until the vision connection is added.</p></div><Link href="/" className="hm-btn secondary">Close</Link></header><div className="hm-scan-modes">{modes.map(x=><button className={mode===x?"active":""} key={x} onClick={()=>{setMode(x);setAnalysed(false);setConfirmed(false)}}>{x}</button>)}</div><section className="hm-camera-stage">{preview?<img src={preview} alt="Selected kitchen photo"/>:<div><span>◎</span><strong>Show Home your {mode.toLowerCase()}</strong><small>Take or choose a photo</small></div>}<label><input type="file" accept="image/*" capture="environment" onChange={e=>{const f=e.target.files?.[0];if(f){setPreview(URL.createObjectURL(f));setAnalysed(false)}}}/><span>Camera / photo</span></label></section>{preview&&<button className="hm-btn primary hm-analyse" onClick={analyse}>Analyse {mode}</button>}{analysed&&<section className="hm-scan-result"><span>V1 PLACEHOLDER ANALYSIS</span><h2>{mode} understood</h2>{mode==="Fridge"&&<p>I can see mushrooms, cream and broccoli. Confirming will update the same Kitchen state that Plan and Groceries use.</p>}{mode==="Freezer"&&<p>I can see GOLD, RED and DARK portions. Confirming will reconcile their freezer counts.</p>}{mode==="Receipt"&&<p>I found chicken thighs, coriander and coconut milk. Confirming will add them to Kitchen and immediately reduce the weekly shopping list.</p>}{mode==="Prep check"&&<p>Future vision will compare your pan against the exact base cue. For now, open the relevant mother-base page for the researched visual/texture cue.</p>}{mode!=="Prep check"&&<button className="hm-btn primary" onClick={confirm}>{confirmed?"✓ Kitchen updated":"Confirm & update Kitchen"}</button>}</section>}</div>
}
