"use client";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {useEffect,useRef,useState} from "react";
import {useHousehold} from "./HouseholdState";
import {getComponent,getIngredient,getRecipe} from "@/data/home-data";
import {recipeTitle} from "@/data/recipe-display";
import {Icon} from "./Icons";
import styles from "./SmartAskRuntime.module.css";

type Mutation={type:"none"|"set_day"|"set_ingredient"|"set_component"|"set_use_soon"|"add_note"|"set_favourite";dayIndex:number|null;mealId:string|null;ingredientId:string|null;componentId:string|null;quantity:number|null;value:boolean|null;note:string|null;author:"josh"|"g"|"home"|null};
type Reply={text:string;mealIds?:string[];tags?:string[];href?:string|null;action?:string|null;mutation?:Mutation|null};
type Message=Reply&{who:"you"|"home"};
const quick=["What should we cook tonight?","What can we make now?","Something quick under 30 minutes","G doesn't want rice","What should we use soon?","What should we prep?"];
const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];

export function SmartAskRuntime(){
 const path=usePathname();const h=useHousehold();const[configured,setConfigured]=useState(false);const[open,setOpen]=useState(false);const[q,setQ]=useState("");const[loading,setLoading]=useState(false);const[messages,setMessages]=useState<Message[]>([{who:"home",text:"What do you need? I’m using the same Kitchen, Plan and cookbook."}]);const[applied,setApplied]=useState<Record<string,boolean>>({});const configuredRef=useRef(false);const bypass=useRef(false);
 const cameraMode=path.startsWith("/prep")?"Prep":path.startsWith("/kitchen")?"Fridge":"Fridge";const cameraHref=`/scan?mode=${cameraMode}&back=${encodeURIComponent(path)}`;
 useEffect(()=>{fetch("/api/ask-home",{cache:"no-store"}).then(r=>r.json()).then((x:{configured?:boolean})=>{const ready=!!x.configured;configuredRef.current=ready;setConfigured(ready)}).catch(()=>{})},[]);
 useEffect(()=>{const handler=(event:Event)=>{if(bypass.current){bypass.current=false;return}if(!configuredRef.current)return;event.stopImmediatePropagation();setOpen(true);window.setTimeout(()=>{const legacy=document.querySelector<HTMLButtonElement>(".hm-ask-sheet-v5 .hm-icon-button-v5");legacy?.click()},20)};window.addEventListener("home-meals:ask",handler);return()=>window.removeEventListener("home-meals:ask",handler)},[]);
 const fallbackLegacy=()=>{setOpen(false);bypass.current=true;window.setTimeout(()=>window.dispatchEvent(new Event("home-meals:ask")),0)};
 const statePayload={week:h.week,componentStock:h.componentStock,ingredientStock:h.ingredientStock,useSoon:h.useSoon,favourites:h.favourites,ratings:h.ratings,history:h.history,recipeNotes:h.recipeNotes,prepBatches:h.prepBatches,kitchenReady:h.kitchenReady};
 const send=async(text=q)=>{const clean=text.trim();if(!clean||loading)return;const prior=messages.slice(-6);setMessages(v=>[...v,{who:"you",text:clean}]);setQ("");setLoading(true);try{const context=prior.length>1?`${prior.map(m=>`${m.who==="you"?"Household":"Home"}: ${m.text}`).join("\n")}\nHousehold: ${clean}`:clean;const res=await fetch("/api/ask-home",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:context,state:statePayload})});if(res.status===503){fallbackLegacy();return}if(!res.ok)throw new Error("ask_failed");const reply=await res.json() as Reply;setMessages(v=>[...v,{who:"home",text:reply.text,mealIds:reply.mealIds??[],tags:reply.tags??[],href:reply.href,action:reply.action,mutation:reply.mutation}])}catch{setMessages(v=>[...v,{who:"home",text:"I couldn’t reach the household brain just now. Your local Kitchen and Plan are still safe."}])}finally{setLoading(false)}};
 const mutationLabel=(m:Mutation)=>{if(m.type==="set_day"&&m.dayIndex!=null&&m.mealId)return `Set ${days[m.dayIndex]} to ${recipeTitle(m.mealId,getRecipe(m.mealId).title)}`;if(m.type==="set_ingredient"&&m.ingredientId&&m.quantity!=null)return `Set ${getIngredient(m.ingredientId)?.name??m.ingredientId} to ${m.quantity}`;if(m.type==="set_component"&&m.componentId&&m.quantity!=null)return `Set ${getComponent(m.componentId)?.code??m.componentId} to ${m.quantity} ml`;if(m.type==="set_use_soon"&&m.ingredientId)return `${m.value?"Mark":"Unmark"} ${getIngredient(m.ingredientId)?.name??m.ingredientId} use soon`;if(m.type==="add_note"&&m.mealId)return `Save note to ${recipeTitle(m.mealId,getRecipe(m.mealId).title)}`;if(m.type==="set_favourite"&&m.mealId)return `${m.value?"Favourite":"Unfavourite"} ${recipeTitle(m.mealId,getRecipe(m.mealId).title)}`;return "Apply change"};
 const applyMutation=(m:Mutation)=>{const key=JSON.stringify(m);if(applied[key])return;if(m.type==="set_day"&&m.dayIndex!=null&&m.mealId)h.setDay(m.dayIndex,m.mealId);else if(m.type==="set_ingredient"&&m.ingredientId&&m.quantity!=null)h.setIngredient(m.ingredientId,m.quantity);else if(m.type==="set_component"&&m.componentId&&m.quantity!=null)h.setComponent(m.componentId,m.quantity);else if(m.type==="set_use_soon"&&m.ingredientId&&m.value!=null){if(!!h.useSoon[m.ingredientId]!==m.value)h.toggleUseSoon(m.ingredientId)}else if(m.type==="add_note"&&m.mealId&&m.note)h.noteMeal(m.mealId,m.note,m.author??"home");else if(m.type==="set_favourite"&&m.mealId&&m.value!=null){if(!!h.favourites[m.mealId]!==m.value)h.toggleFavourite(m.mealId)}else return;setApplied(v=>({...v,[key]:true}))};
 if(!configured||!open)return null;
 return <div className={styles.backdrop} role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className={styles.sheet} role="dialog" aria-modal="true" aria-label="Ask Home"><header className={styles.header}><div><span className={styles.eyebrow}>HOME</span><h2>Ask Home</h2><p>Kitchen + Plan + cookbook, together.</p></div><button className={styles.close} onClick={()=>setOpen(false)} aria-label="Close Ask Home">×</button></header><div className={styles.modes}><Link href={cameraHref} onClick={()=>setOpen(false)}><Icon name="camera" size={19}/>Show</Link><button className={styles.active} onClick={()=>document.querySelector<HTMLInputElement>(`.${styles.composer} input`)?.focus()}><Icon name="spark" size={19}/>Ask</button><button onClick={()=>{setOpen(false);window.dispatchEvent(new Event("home-meals:voice"))}}><Icon name="mic" size={19}/>Talk</button></div><div className={`${styles.messages} ${loading?styles.loading:""}`} aria-live="polite">{messages.length?messages.slice(-8).map((m,i)=><article key={i} className={`${styles.message} ${m.who==="you"?styles.user:""}`}><p>{m.text}</p>{m.tags&&m.tags.length>0&&<div className={styles.tags}>{m.tags.map(tag=><span key={tag}>{tag}</span>)}</div>}{m.mealIds&&m.mealIds.length>0&&<div className={styles.meals}>{m.mealIds.map(id=>{const r=getRecipe(id);const title=recipeTitle(id,r.title);return <Link key={id} className={styles.meal} href={`/cook/${id}`} onClick={()=>setOpen(false)}>{r.image?<img src={r.image} alt={title}/>:<span/>}<span><strong>{title}</strong><small>{r.minutes} min · {r.cuisine}</small></span></Link>})}</div>}{m.mutation&&m.mutation.type!=="none"&&<button className={styles.mutation} disabled={!!applied[JSON.stringify(m.mutation)]} onClick={()=>applyMutation(m.mutation!)}>{applied[JSON.stringify(m.mutation)]?"Applied ✓":mutationLabel(m.mutation)}</button>}{m.href&&m.action&&<Link className={styles.action} href={m.href} onClick={()=>setOpen(false)}>{m.action} →</Link>}</article>):<div className={styles.empty}>Ask what to eat, what to prep, what is running low, or what needs using first.</div>}{loading&&<article className={styles.message}><p>Checking Home…</p></article>}</div><div className={styles.quick}>{quick.map(item=><button key={item} onClick={()=>send(item)}>{item.replace("What should we cook tonight?","Tonight").replace("What can we make now?","Ready now").replace("Something quick under 30 minutes","Quick").replace("G doesn't want rice","No rice").replace("What should we use soon?","Use soon").replace("What should we prep?","Prep")}</button>)}</div><form className={styles.composer} onSubmit={e=>{e.preventDefault();send()}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ask about home…" aria-label="Ask Home" autoFocus/><button className={styles.send} aria-label="Send" disabled={loading}>→</button></form></section></div>;
}
