"use client";
import {usePathname} from "next/navigation";
import {useEffect,useRef,useState} from "react";
import {useHousehold} from "./HouseholdState";
import {useHouseholdV12} from "./HouseholdStateV12";
import {getRecipe} from "@/data/home-data";
import {getCanonicalPrepV2} from "@/data/food-truth-v2";
import {getCanonicalIngredientV2} from "@/data/ingredient-catalog-v2";
import {quantity} from "@/data/food-quantity";
import {recipeTitle} from "@/data/recipe-display";
import {useSheet} from "@/lib/useSheet";
import {AskHomeView} from "./AskHomeView";

type Mutation={type:"none"|"set_day"|"set_week"|"set_ingredient"|"set_component"|"set_use_soon"|"add_note"|"set_favourite"|"set_active_prep_set"|"confirm_empty_kitchen";dayIndex:number|null;mealId:string|null;mealIds:string[]|null;ingredientId:string|null;componentId:string|null;componentIds:string[]|null;quantity:number|null;value:boolean|null;note:string|null;author:"josh"|"g"|"home"|null};
type Reply={text:string;mealIds?:string[];tags?:string[];href?:string|null;action?:string|null;mutation?:Mutation|null};
type Message=Reply&{who:"you"|"home"};
const quick=[{label:"Tonight",text:"What should we cook tonight?"},{label:"Our prep",text:"What dinners fit our active prep repertoire?"},{label:"Not lately",text:"What do we both like that we haven’t eaten recently?"},{label:"Ready now",text:"What can we make now?"},{label:"Use soon",text:"What should we use soon?"},{label:"Prep",text:"What should we prep this week?"}];
const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];

export function SmartAskRuntime(){
 const path=usePathname(),h=useHousehold(),v12=useHouseholdV12();const[configured,setConfigured]=useState(false),[open,setOpen]=useState(false),[q,setQ]=useState(""),[loading,setLoading]=useState(false),[messages,setMessages]=useState<Message[]>([{who:"home",text:"What do you need? I’m using the same Kitchen, Plan, prep repertoire and meal history."}]),[applied,setApplied]=useState<Record<string,boolean>>({});const configuredRef=useRef(false),bypass=useRef(false);
 const cameraMode=path.startsWith("/prep")?"Prep":path.startsWith("/kitchen")?"Fridge":"Fridge",cameraHref=`/scan?mode=${cameraMode}&back=${encodeURIComponent(path)}`;
 useEffect(()=>{fetch("/api/ask-home",{cache:"no-store"}).then(r=>r.json()).then((x:{configured?:boolean})=>{const ready=!!x.configured;configuredRef.current=ready;setConfigured(ready)}).catch(()=>{})},[]);
 useEffect(()=>{const handler=(event:Event)=>{if(bypass.current){bypass.current=false;return}if(!configuredRef.current)return;event.stopImmediatePropagation();setOpen(true);window.setTimeout(()=>document.querySelector<HTMLButtonElement>("[data-local] [data-ask-close]")?.click(),20)};window.addEventListener("home-meals:ask",handler);return()=>window.removeEventListener("home-meals:ask",handler)},[]);
 useSheet(open&&configured,()=>setOpen(false));
 useEffect(()=>{const handler=(event:Event)=>{if(!configuredRef.current)return;const detail=(event as CustomEvent<{question?:string;reply?:Reply}>).detail;if(!detail?.reply)return;const reply=detail.reply;setOpen(true);setMessages(v=>[...v,...(detail.question?[{who:"you" as const,text:detail.question}]:[]),{who:"home",text:String(reply.text||""),mealIds:reply.mealIds??[],tags:reply.tags??[],href:reply.href,action:reply.action,mutation:reply.mutation}])};window.addEventListener("home-meals:voice-proposal",handler as EventListener);return()=>window.removeEventListener("home-meals:voice-proposal",handler as EventListener)},[]);
 const fallbackLegacy=()=>{setOpen(false);bypass.current=true;window.setTimeout(()=>window.dispatchEvent(new Event("home-meals:ask")),0)};
 const statePayload={...v12.state,componentStockV2:v12.componentStock};
 const send=async(text=q)=>{const clean=text.trim();if(!clean||loading)return;const prior=messages.slice(-6);setMessages(v=>[...v,{who:"you",text:clean}]);setQ("");setLoading(true);try{const context=prior.length>1?`${prior.map(m=>`${m.who==="you"?"Household":"Home"}: ${m.text}`).join("\n")}\nHousehold: ${clean}`:clean;const res=await fetch("/api/ask-home",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:context,state:statePayload})});if(res.status===503){fallbackLegacy();return}if(!res.ok)throw new Error("ask_failed");const reply=await res.json() as Reply;setMessages(v=>[...v,{who:"home",text:reply.text,mealIds:reply.mealIds??[],tags:reply.tags??[],href:reply.href,action:reply.action,mutation:reply.mutation}])}catch{setMessages(v=>[...v,{who:"home",text:"I couldn’t reach the household brain just now. Your local Kitchen and Plan are still safe."}])}finally{setLoading(false)}};
 const mutationLabel=(m:Mutation)=>{if(m.type==="set_day"&&m.dayIndex!=null&&m.mealId)return `Set ${days[m.dayIndex]} to ${recipeTitle(m.mealId,getRecipe(m.mealId).title)}`;if(m.type==="set_week"&&m.mealIds?.length===7)return"Use this 7-day plan";if(m.type==="set_active_prep_set"&&m.componentIds)return`Use ${m.componentIds.length} active prep items`;if(m.type==="confirm_empty_kitchen")return"Confirm Kitchen is empty";if(m.type==="set_ingredient"&&m.ingredientId&&m.quantity!=null){const ing=getCanonicalIngredientV2(m.ingredientId);return `Set ${ing?.name??m.ingredientId} to ${m.quantity} ${ing?.canonicalUnit??""}`.trim()}if(m.type==="set_component"&&m.componentId&&m.quantity!=null){const c=getCanonicalPrepV2(m.componentId);return `Set ${c?.code??m.componentId} to ${m.quantity} ${c?.workingUnit.unit??""}`.trim()}if(m.type==="set_use_soon"&&m.ingredientId)return `${m.value?"Mark":"Unmark"} ${getCanonicalIngredientV2(m.ingredientId)?.name??m.ingredientId} use soon`;if(m.type==="add_note"&&m.mealId)return `Save note to ${recipeTitle(m.mealId,getRecipe(m.mealId).title)}`;if(m.type==="set_favourite"&&m.mealId)return `${m.value?"Favourite":"Unfavourite"} ${recipeTitle(m.mealId,getRecipe(m.mealId).title)}`;return"Apply change"};
 const applyMutation=(m:Mutation)=>{const key=JSON.stringify(m);if(applied[key])return;if(m.type==="set_day"&&m.dayIndex!=null&&m.mealId)v12.setDay(m.dayIndex,m.mealId);else if(m.type==="set_week"&&m.mealIds?.length===7)m.mealIds.forEach((id,i)=>v12.setDay(i,id));else if(m.type==="set_active_prep_set"&&m.componentIds)v12.setActivePrepSet(m.componentIds);else if(m.type==="confirm_empty_kitchen")v12.confirmEmptyKitchen();else if(m.type==="set_ingredient"&&m.ingredientId&&m.quantity!=null){const ing=getCanonicalIngredientV2(m.ingredientId);if(!ing)return;v12.setIngredientObserved(m.ingredientId,quantity(m.quantity,ing.canonicalUnit))}else if(m.type==="set_component"&&m.componentId&&m.quantity!=null){const c=getCanonicalPrepV2(m.componentId);if(!c)return;v12.reconcileComponentTotal(m.componentId,quantity(m.quantity,c.workingUnit.unit))}else if(m.type==="set_use_soon"&&m.ingredientId&&m.value!=null){if(!!v12.state.useSoon[m.ingredientId]!==m.value)v12.toggleUseSoon(m.ingredientId)}else if(m.type==="add_note"&&m.mealId&&m.note)v12.noteMeal(m.mealId,m.note,m.author??"home");else if(m.type==="set_favourite"&&m.mealId&&m.value!=null){if(!!v12.state.favourites[m.mealId]!==m.value)v12.toggleFavourite(m.mealId)}else return;setApplied(v=>({...v,[key]:true}))};
 if(!configured||!open)return null;const view=messages.map(m=>({...m,extra:m.mutation&&m.mutation.type!=="none"?<button className="hm-ask-action" style={{marginRight:6}} disabled={!!applied[JSON.stringify(m.mutation)]} onClick={()=>applyMutation(m.mutation!)}>{applied[JSON.stringify(m.mutation)]?"Applied ✓":mutationLabel(m.mutation)}</button>:undefined}));
 return <AskHomeView messages={view} q={q} setQ={setQ} onSend={text=>{void send(text)}} onClose={()=>setOpen(false)} cameraHref={cameraHref} quick={quick} loading={loading} status={loading?"Home is thinking":"Ask Home"}/>;
}
