"use client";
import {usePathname} from "next/navigation";
import {useEffect,useRef,useState,type ReactNode} from "react";
import {useHouseholdV12} from "./HouseholdStateV12";
import {getLiveRecipeV7} from "@/data/recipe-catalog-v7";
import {getCanonicalPrepV2} from "@/data/food-truth-v2";
import {getCanonicalIngredientV7} from "@/data/ingredient-catalog-v7";
import {quantity} from "@/data/food-quantity";
import {recipeTitle} from "@/data/recipe-display";
import {getHouseholdPerson,type HouseholdPerson} from "@/lib/device-profile";
import type {CardContext,JoshStyle,MemoryKind,ResponseType,TruthLevel} from "@/lib/josh-conversation";
import {useSheet} from "@/lib/useSheet";
import {AskHomeView,type AskMessage} from "./AskHomeView";

const STYLE_KEY="home-meals-josh-style-v1";
type Mutation={type:"none"|"set_day"|"set_week"|"set_ingredient"|"set_component"|"set_use_soon"|"add_note"|"set_favourite"|"set_active_prep_set"|"confirm_empty_kitchen";dayIndex:number|null;mealId:string|null;mealIds:string[]|null;ingredientId:string|null;componentId:string|null;componentIds:string[]|null;quantity:number|null;value:boolean|null;note:string|null;author:"josh"|"g"|"home"|null};
type StructuredItem={label:string;detail:string|null;state:string|null;href:string|null};
type StructuredSection={title:string|null;items:StructuredItem[]};
type MemoryCandidate={subject:string;kind:MemoryKind;text:string;requiresConfirmation:boolean};
type RecipeDraft={title:string;servings:number|null;ingredients:{name:string;quantity:number|null;unit:string|null}[];method:string[];notes:string[]};
type VisionContext={mode:string;summary:string;assessment:string|null;cookingCue:string|null;items:{id:string|null;name:string;quantity:number|null;unit:string|null;confidence:number;useSoon:boolean}[];warnings:string[]};
type DraftContext={id:string;title:string;status:"idea"|"draft"|"cooked"|"revised"|"household_approved";payload:Record<string,unknown>};
type RecipeImageAction={type:"none"|"suggest_generate_recipe_image"|"generate_recipe_image"|"regenerate_recipe_image";lookHint:string|null};
type RecipeImageMeta={id:string;draft_id:string;url:string;model:string;quality:string;look:string|null;selected:boolean;created_at:string};
type ImageJob={status:"generating"|"ready"|"error";draftId:string|null;image:RecipeImageMeta|null;message:string|null};
type Reply={text:string;responseType?:ResponseType;truthLevel?:TruthLevel;cardContext?:CardContext;sections?:StructuredSection[];mealIds?:string[];tags?:string[];href?:string|null;action?:string|null;mutation?:Mutation|null;memoryCandidates?:MemoryCandidate[];recipeDraft?:RecipeDraft|null;recipeImageAction?:RecipeImageAction;conversationId?:string|null};
type Message=Reply&{who:"you"|"home";extra?:ReactNode};
type StoredMessage={role:"user"|"assistant";content:string;structured?:Reply|null};
const quick=[{label:"Tonight",text:"What should we cook tonight?"},{label:"Our prep",text:"What works well with the prep we like keeping around?"},{label:"Not lately",text:"What do we both like that we haven’t eaten recently?"},{label:"Ready now",text:"What can we make now?"},{label:"Use soon",text:"What should we use soon?"},{label:"Prep",text:"What should we prep this week?"}];
const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
const liveTitle=(id:string)=>{const r=getLiveRecipeV7(id);return r?recipeTitle(id,r.title):id};
function readStyle():JoshStyle{try{const value=localStorage.getItem(STYLE_KEY);return value==="shorter"||value==="chatty"?value:"normal"}catch{return"normal"}}
function introFor(person:HouseholdPerson){return person==="g"?"What are you in the mood for? Dinner, prep, the week, anything.":"What are we doing? Dinner, prep, the week, whatever."}

export function SmartAskRuntime(){
 const path=usePathname(),v12=useHouseholdV12();
 const[configured,setConfigured]=useState(false),[open,setOpen]=useState(false),[q,setQ]=useState(""),[loading,setLoading]=useState(false),[person,setPerson]=useState<HouseholdPerson>("josh"),[style,setStyle]=useState<JoshStyle>("normal"),[conversationId,setConversationId]=useState<string|null>(null),[messages,setMessages]=useState<Message[]>([]),[applied,setApplied]=useState<Record<string,boolean>>({}),[remembered,setRemembered]=useState<Record<string,boolean>>({}),[savedDrafts,setSavedDrafts]=useState<Record<string,string>>({}),[imageJobs,setImageJobs]=useState<Record<string,ImageJob>>({}),[visionContext,setVisionContext]=useState<VisionContext|null>(null),[draftContext,setDraftContext]=useState<DraftContext|null>(null);
 const configuredRef=useRef(false),bypass=useRef(false),loadedPerson=useRef<HouseholdPerson|null>(null);
 const cameraMode=path.startsWith("/prep")?"Prep":"Fridge",cameraHref=`/scan?mode=${cameraMode}&back=${encodeURIComponent(path)}`;
 useEffect(()=>{const sync=()=>{setPerson(getHouseholdPerson()??"josh");setStyle(readStyle())};sync();const personHandler=()=>sync(),styleHandler=()=>sync();window.addEventListener("home-meals:person",personHandler);window.addEventListener("home-meals:josh-style",styleHandler);return()=>{window.removeEventListener("home-meals:person",personHandler);window.removeEventListener("home-meals:josh-style",styleHandler)}},[]);
 useEffect(()=>{fetch("/api/ask-home",{cache:"no-store"}).then(r=>r.json()).then((x:{configured?:boolean})=>{const ready=!!x.configured;configuredRef.current=ready;setConfigured(ready)}).catch(()=>{})},[]);
 useEffect(()=>{if(!configured||loadedPerson.current===person)return;loadedPerson.current=person;setConversationId(null);setMessages([]);fetch(`/api/conversation?person=${encodeURIComponent(person)}`,{cache:"no-store"}).then(async r=>r.ok?r.json():null).then((x:{conversation?:{id?:string}|null;messages?:StoredMessage[]}|null)=>{if(!x)return;const id=x.conversation?.id??null;setConversationId(id);const loaded=(x.messages??[]).map<Message>(m=>m.role==="user"?{who:"you",text:m.content}:{who:"home",text:m.content,...(m.structured??{})});setMessages(loaded.length?loaded:[{who:"home",text:introFor(person),responseType:"short_answer",truthLevel:"reasoned_suggestion",cardContext:"default"}])}).catch(()=>setMessages([{who:"home",text:introFor(person)}]))},[configured,person]);
 useEffect(()=>{const handler=(event:Event)=>{if(bypass.current){bypass.current=false;return}if(!configuredRef.current)return;event.stopImmediatePropagation();const detail=(event as CustomEvent<{prefill?:string;visionContext?:VisionContext;draftContext?:DraftContext}>).detail;setVisionContext(detail?.visionContext??null);setDraftContext(detail?.draftContext??null);if(detail?.prefill)setQ(detail.prefill);setOpen(true);window.setTimeout(()=>document.querySelector<HTMLButtonElement>("[data-local] [data-ask-close]")?.click(),20)};window.addEventListener("home-meals:ask",handler);return()=>window.removeEventListener("home-meals:ask",handler)},[]);
 useSheet(open&&configured,()=>setOpen(false));
 useEffect(()=>{const handler=(event:Event)=>{if(!configuredRef.current)return;const detail=(event as CustomEvent<{question?:string;reply?:Reply}>).detail;if(!detail?.reply)return;const reply=detail.reply;if(reply.conversationId)setConversationId(reply.conversationId);setOpen(true);setMessages(v=>[...v,...(detail.question?[{who:"you" as const,text:detail.question}]:[]),{who:"home",...reply,text:String(reply.text||"")}])};window.addEventListener("home-meals:voice-proposal",handler as EventListener);return()=>window.removeEventListener("home-meals:voice-proposal",handler as EventListener)},[]);
 const fallbackLegacy=()=>{setOpen(false);bypass.current=true;window.setTimeout(()=>window.dispatchEvent(new Event("home-meals:ask")),0)};
 const statePayload={...v12.state,componentStockV2:v12.componentStock};
 const draftKey=(d:RecipeDraft)=>JSON.stringify(d);
 const imageKey=(reply:Reply)=>reply.recipeDraft?`recipe:${draftKey(reply.recipeDraft)}`:draftContext?.id?`draft:${draftContext.id}:${reply.text}`:`reply:${reply.text}`;
 const saveDraftV21=async(d:RecipeDraft)=>{const key=draftKey(d);if(savedDrafts[key])return savedDrafts[key];const updating=!!draftContext?.id;const res=await fetch("/api/recipe-drafts",{method:updating?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(updating?{id:draftContext!.id,status:"revised",payload:d}:{title:d.title,payload:d,provenance:{conversationId,person}})});if(!res.ok)return null;const x=await res.json() as {draft?:{id?:string}};const id=x.draft?.id??draftContext?.id??null;if(id){setSavedDrafts(v=>({...v,[key]:id}));if(updating)setDraftContext({...draftContext!,title:d.title,status:"revised",payload:d as unknown as Record<string,unknown>});window.dispatchEvent(new Event("home-meals:drafts-changed"))}return id};
 const generateRecipeImage=async(reply:Reply,forcedMode?:"initial"|"replace"|"candidate")=>{const key=imageKey(reply);if(imageJobs[key]?.status==="generating")return;setImageJobs(v=>({...v,[key]:{status:"generating",draftId:null,image:null,message:null}}));let draftId=draftContext?.id??null;if(reply.recipeDraft)draftId=await saveDraftV21(reply.recipeDraft);if(!draftId){setImageJobs(v=>({...v,[key]:{status:"error",draftId:null,image:null,message:"Save the working recipe first."}}));return}let mode=forcedMode;if(!mode){try{const current=await fetch(`/api/recipe-image?draftId=${encodeURIComponent(draftId)}`,{cache:"no-store"}).then(r=>r.ok?r.json():null);mode=current?.selected?"candidate":"initial"}catch{mode="initial"}}try{const res=await fetch("/api/recipe-image",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({draftId,mode,lookHint:reply.recipeImageAction?.lookHint??null})});if(!res.ok)throw new Error("image_failed");const x=await res.json() as {image:RecipeImageMeta};setImageJobs(v=>({...v,[key]:{status:"ready",draftId,image:x.image,message:null}}));window.dispatchEvent(new Event("home-meals:recipe-image-changed"));window.dispatchEvent(new Event("home-meals:drafts-changed"))}catch{setImageJobs(v=>({...v,[key]:{status:"error",draftId,image:null,message:"Couldn’t make that image just now. Try again."}}))}};
 const selectGeneratedImage=async(key:string,job:ImageJob)=>{if(!job.draftId||!job.image)return;const res=await fetch("/api/recipe-image",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({draftId:job.draftId,imageId:job.image.id})});if(!res.ok)return;const x=await res.json() as {image:RecipeImageMeta};setImageJobs(v=>({...v,[key]:{...job,image:x.image,status:"ready"}}));window.dispatchEvent(new Event("home-meals:recipe-image-changed"));window.dispatchEvent(new Event("home-meals:drafts-changed"))};
 const send=async(text=q)=>{const clean=text.trim();if(!clean||loading)return;setMessages(v=>[...v,{who:"you",text:clean}]);setQ("");setLoading(true);try{const res=await fetch("/api/ask-home",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:clean,state:statePayload,person,style,conversationId,visionContext,draftContext})});if(res.status===503){fallbackLegacy();return}if(!res.ok)throw new Error("ask_failed");const reply=await res.json() as Reply;if(reply.conversationId)setConversationId(reply.conversationId);setMessages(v=>[...v,{who:"home",...reply,text:reply.text}]);setVisionContext(null);if(reply.recipeImageAction?.type==="generate_recipe_image")void generateRecipeImage(reply);else if(reply.recipeImageAction?.type==="regenerate_recipe_image")void generateRecipeImage(reply,"replace")}catch{setMessages(v=>[...v,{who:"home",text:"Couldn’t check that just now. Nothing changed. Try me again in a sec."}])}finally{setLoading(false)}};
 const mutationLabel=(m:Mutation)=>{if(m.type==="set_day"&&m.dayIndex!=null&&m.mealId)return `Put ${liveTitle(m.mealId)} on ${days[m.dayIndex]}`;if(m.type==="set_week"&&m.mealIds?.length===7)return"Use this week";if(m.type==="set_active_prep_set"&&m.componentIds)return`Keep these ${m.componentIds.length} prep items`;if(m.type==="confirm_empty_kitchen")return"Kitchen is empty";if(m.type==="set_ingredient"&&m.ingredientId&&m.quantity!=null){const ing=getCanonicalIngredientV7(m.ingredientId);return `Set ${ing?.name??m.ingredientId} to ${m.quantity} ${ing?.canonicalUnit??""}`.trim()}if(m.type==="set_component"&&m.componentId&&m.quantity!=null){const c=getCanonicalPrepV2(m.componentId);return `Set ${c?.code??m.componentId} to ${m.quantity} ${c?.workingUnit.unit??""}`.trim()}if(m.type==="set_use_soon"&&m.ingredientId)return `${m.value?"Use soon":"No rush"}: ${getCanonicalIngredientV7(m.ingredientId)?.name??m.ingredientId}`;if(m.type==="add_note"&&m.mealId)return `Save note to ${liveTitle(m.mealId)}`;if(m.type==="set_favourite"&&m.mealId)return `${m.value?"Favourite":"Unfavourite"} ${liveTitle(m.mealId)}`;return"Make the change"};
 const applyMutation=(m:Mutation)=>{const key=JSON.stringify(m);if(applied[key])return;if(m.type==="set_day"&&m.dayIndex!=null&&m.mealId)v12.setDay(m.dayIndex,m.mealId);else if(m.type==="set_week"&&m.mealIds?.length===7)v12.setConfirmedWeek(m.mealIds);else if(m.type==="set_active_prep_set"&&m.componentIds)v12.setActivePrepSet(m.componentIds);else if(m.type==="confirm_empty_kitchen")v12.confirmEmptyKitchen();else if(m.type==="set_ingredient"&&m.ingredientId&&m.quantity!=null){const ing=getCanonicalIngredientV7(m.ingredientId);if(!ing)return;v12.setIngredientObserved(m.ingredientId,quantity(m.quantity,ing.canonicalUnit))}else if(m.type==="set_component"&&m.componentId&&m.quantity!=null){const c=getCanonicalPrepV2(m.componentId);if(!c)return;v12.reconcileComponentTotal(m.componentId,quantity(m.quantity,c.workingUnit.unit))}else if(m.type==="set_use_soon"&&m.ingredientId&&m.value!=null){if(!!v12.state.useSoon[m.ingredientId]!==m.value)v12.toggleUseSoon(m.ingredientId)}else if(m.type==="add_note"&&m.mealId&&m.note)v12.noteMeal(m.mealId,m.note,m.author??"home");else if(m.type==="set_favourite"&&m.mealId&&m.value!=null){if(!!v12.state.favourites[m.mealId]!==m.value)v12.toggleFavourite(m.mealId)}else return;setApplied(v=>({...v,[key]:true}))};
 const remember=async(c:MemoryCandidate)=>{const key=JSON.stringify(c);if(remembered[key])return;const res=await fetch("/api/memory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subject:c.subject,kind:c.kind,text:c.text,sourcePerson:person,provenance:{conversationId}})});if(res.ok)setRemembered(v=>({...v,[key]:true}))};
 if(!configured||!open)return null;
 const view:AskMessage[]=messages.map((m,i)=>{const controls:ReactNode[]=[];if(m.mutation&&m.mutation.type!=="none"){const key=JSON.stringify(m.mutation);controls.push(<button key="mutation" className="hm-ask-action" disabled={!!applied[key]} onClick={()=>applyMutation(m.mutation!)}>{applied[key]?"Done ✓":mutationLabel(m.mutation)}</button>)}for(const c of m.memoryCandidates??[]){if(c.requiresConfirmation){const key=JSON.stringify(c);controls.push(<button key={`memory-${key}`} className="hm-ask-action ghost" disabled={!!remembered[key]} onClick={()=>void remember(c)}>{remembered[key]?"Remembered ✓":"Remember this"}</button>)}}const hasImageIntent=!!m.recipeDraft||(m.recipeImageAction&&m.recipeImageAction.type!=="none");if(m.recipeDraft){const key=draftKey(m.recipeDraft);controls.push(<button key="draft" className="hm-ask-action ghost" disabled={!!savedDrafts[key]} onClick={()=>void saveDraftV21(m.recipeDraft!)}>{savedDrafts[key]?(draftContext?"Updated ✓":"Saved ✓"):(draftContext?"Update draft":"Save working recipe")}</button>)}if(hasImageIntent){const key=imageKey(m),job=imageJobs[key];if(job?.status==="ready"&&job.image){controls.push(<div className="hm-ask-generated" key="generated"><img src={job.image.url} alt={`${m.recipeDraft?.title??draftContext?.title??"Working recipe"} generated recipe illustration`}/><small>Generated with {job.image.model}</small><div>{!job.image.selected&&<button className="hm-ask-action" onClick={()=>void selectGeneratedImage(key,job)}>Use this image</button>}<button className="hm-ask-action ghost" onClick={()=>void generateRecipeImage(m,"candidate")}>Try another look</button>{job.draftId&&<a className="hm-ask-action ghost" href={`/cook/drafts/${encodeURIComponent(job.draftId)}`}>Open recipe</a>}</div></div>)}else controls.push(<button key="image" className="hm-ask-action" disabled={job?.status==="generating"} onClick={()=>void generateRecipeImage(m)}>{job?.status==="generating"?"Generating image…":job?.status==="error"?"Try image again":"Generate image"}</button>);if(job?.status==="error"&&job.message)controls.push(<span className="hm-ask-image-error" key="image-error">{job.message}</span>)}return{...m,extra:controls.length?<div className="hm-ask-inline-actions" key={`extra-${i}`}>{controls}</div>:undefined}});
 return <AskHomeView messages={view} q={q} setQ={setQ} onSend={text=>{void send(text)}} onClose={()=>setOpen(false)} cameraHref={cameraHref} quick={quick} loading={loading} status={loading?"Thinking…":"Ask Josh"}/>;
}
