"use client";
import {useEffect,useMemo,useState} from "react";
import {usePathname} from "next/navigation";
import {getIngredient} from "@/data/home-data";
import {getCanonicalPrepV2} from "@/data/food-truth-v2";
import {useHousehold} from "./HouseholdState";
import {JoshPresenceAnchor} from "./JoshPresence";
import styles from "./VisionRuntime.module.css";

type VisionItem={id:string|null;name:string;quantity:number|null;unit:string|null;confidence:number;useSoon:boolean};
type VisionResult={summary:string;items:VisionItem[];assessment:string|null;cookingCue:string|null;needsConfirmation:boolean;warnings:string[];source?:string};
const modes=new Set(["Fridge","Freezer","Pantry","Receipt","Prep","Meal"]);
function fileDataUrl(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>typeof reader.result==="string"?resolve(reader.result):reject(new Error("read"));reader.onerror=()=>reject(reader.error??new Error("read"));reader.readAsDataURL(file)})}
function clampQty(value:number|null){return value==null?null:Math.max(0,Number(value)||0)}

export function VisionRuntime(){
 const path=usePathname(),h=useHousehold();const[enabled,setEnabled]=useState<boolean|null>(null),[result,setResult]=useState<VisionResult|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[applied,setApplied]=useState<Record<string,boolean>>({});
 const mode=useMemo(()=>{if(path!=="/scan")return null;const q=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("mode"):null;return q&&modes.has(q)?q:"Meal"},[path]);
 useEffect(()=>{if(path!=="/scan")return;fetch("/api/vision",{cache:"no-store"}).then(r=>r.json().then((x:{configured?:boolean})=>setEnabled(r.ok&&!!x.configured))).catch(()=>setEnabled(false))},[path]);
 useEffect(()=>{if(path!=="/scan"||enabled===false)return;const onChange=async(event:Event)=>{const input=event.target instanceof HTMLInputElement?event.target:null;if(!input||input.type!=="file"||!input.accept.includes("image"))return;const file=input.files?.[0];if(!file)return;setResult(null);setApplied({});setError("");setLoading(true);try{const imageDataUrl=await fileDataUrl(file);const current=new URLSearchParams(window.location.search).get("mode"),active=current&&modes.has(current)?current:(mode??"Meal");const res=await fetch("/api/vision",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:active,imageDataUrl})});if(res.status===503){setEnabled(false);return}if(!res.ok)throw new Error("vision");setResult(await res.json() as VisionResult);setEnabled(true)}catch{setError("I couldn’t read that photo clearly. Nothing has changed.")}finally{setLoading(false)}};document.addEventListener("change",onChange,true);return()=>document.removeEventListener("change",onChange,true)},[enabled,mode,path]);
 const askJosh=()=>{if(!result)return;window.dispatchEvent(new CustomEvent("home-meals:ask",{detail:{prefill:"What do you think about this?",visionContext:{mode:mode??"Meal",summary:result.summary,assessment:result.assessment,cookingCue:result.cookingCue,items:(result.items??[]).slice(0,24),warnings:(result.warnings??[]).slice(0,8)}}}))};
 const applyItem=(item:VisionItem,index:number)=>{if(!item.id)return;const ingredient=getIngredient(item.id);if(ingredient){const current=h.ingredientStock[item.id]??0;if(ingredient.tracking==="state"){const next=item.quantity==null?Math.max(1,current):Math.max(0,Math.min(3,Math.round(item.quantity)));h.setIngredient(item.id,next)}else{const q=clampQty(item.quantity);if(q==null)return;h.setIngredient(item.id,mode==="Receipt"?current+q:q)}if(item.useSoon&&!h.useSoon[item.id])h.toggleUseSoon(item.id);setApplied(v=>({...v,[`${index}:${item.id}`]:true}));return}const prep=getCanonicalPrepV2(item.id);if(prep&&mode==="Freezer"){if(item.unit!==prep.workingUnit.unit)return;const q=clampQty(item.quantity);if(q==null)return;h.setComponent(item.id,q);setApplied(v=>({...v,[`${index}:${item.id}`]:true}))}};
 if(path!=="/scan"||enabled===false||(!loading&&!result&&!error))return null;
 return <aside className={styles.panel} aria-live="polite"><div className={styles.head}><JoshPresenceAnchor priority={75} expression={loading?"thinking":error?"sheepish":"happy"} size={48} observeVisibility={false} className={styles.josh}/><div><span>{loading?"HAVING A LOOK":"WHAT I CAN SEE"}</span><strong>{loading?"Give me a second…":result?.summary||"Photo review"}</strong><p>{mode==="Prep"||mode==="Meal"?"I can help with what’s visible, but a photo can’t prove food-safe temperature.":"Nothing changes until you confirm it."}</p></div>{!loading&&<button className={styles.close} onClick={()=>{setResult(null);setError("")}} aria-label="Close photo review">×</button>}</div>{loading&&<div className={styles.loading}><i/>Looking at the photo…</div>}{error&&<div className={styles.error}>{error}</div>}{result&&<>{(result.cookingCue||result.assessment)&&<div className={styles.cue}><strong>{result.cookingCue?"LOOK FOR":"WHAT I THINK"}</strong><p>{result.cookingCue||result.assessment}</p></div>}{result.items?.length>0&&<div className={styles.items}>{result.items.filter(item=>item.id||item.name).map((item,index)=>{const key=`${index}:${item.id??item.name}`,done=!!applied[key],ingredient=!!getIngredient(item.id??""),prep=item.id?getCanonicalPrepV2(item.id):undefined,canApply=ingredient||(mode==="Freezer"&&!!prep&&item.unit===prep.workingUnit.unit);return <div key={key} className={`${styles.item} ${done?styles.done:""}`}><div><strong>{item.name}{item.confidence>=.8&&<span className={styles.badge}>looks likely</span>}</strong><small>{item.quantity==null?"amount unclear":`${item.quantity} ${item.unit??""}`}{item.useSoon?" · use soon":""}</small></div>{item.id&&item.quantity!=null&&canApply&&(mode==="Fridge"||mode==="Freezer"||mode==="Pantry"||mode==="Receipt")&&<button disabled={done} onClick={()=>applyItem(item,index)}>{done?"Kept ✓":mode==="Receipt"?"Add":"Keep"}</button>}</div>})}</div>}{result.warnings?.length>0&&<div className={styles.warnings}>{result.warnings.join(" · ")}</div>}<div className={styles.actions}><button className={styles.secondary} onClick={()=>setResult(null)}>I’ll do it myself</button><button className={styles.primary} onClick={askJosh}>Ask Josh about this</button></div></>}</aside>;
}
