"use client";
import {useEffect,useMemo,useState} from "react";
import {usePathname} from "next/navigation";
import {getIngredient,prepComponents} from "@/data/home-data";
import {useHousehold} from "./HouseholdState";
import styles from "./VisionRuntime.module.css";

type VisionItem={id:string|null;name:string;quantity:number|null;unit:string|null;confidence:number;useSoon:boolean};
type VisionResult={summary:string;items:VisionItem[];assessment:string|null;cookingCue:string|null;needsConfirmation:boolean;warnings:string[];source?:string};
const modes=new Set(["Fridge","Freezer","Pantry","Receipt","Prep","Meal"]);
function fileDataUrl(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>typeof reader.result==="string"?resolve(reader.result):reject(new Error("read"));reader.onerror=()=>reject(reader.error??new Error("read"));reader.readAsDataURL(file)})}
function clampQty(value:number|null){return value==null?null:Math.max(0,Number(value)||0)}

export function VisionRuntime(){
 const path=usePathname();const h=useHousehold();const[enabled,setEnabled]=useState<boolean|null>(null);const[result,setResult]=useState<VisionResult|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[applied,setApplied]=useState<Record<string,boolean>>({});
 const mode=useMemo(()=>{if(path!=="/scan")return null;const q=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("mode"):null;return q&&modes.has(q)?q:"Meal"},[path]);
 useEffect(()=>{if(path!=="/scan")return;fetch("/api/vision",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"Meal",imageDataUrl:""})}).then(r=>setEnabled(r.status!==503)).catch(()=>setEnabled(false))},[path]);
 useEffect(()=>{if(path!=="/scan"||enabled===false)return;const onChange=async(event:Event)=>{const input=event.target instanceof HTMLInputElement?event.target:null;if(!input||input.type!=="file"||!input.accept.includes("image"))return;const file=input.files?.[0];if(!file)return;setResult(null);setApplied({});setError("");setLoading(true);try{const imageDataUrl=await fileDataUrl(file);const current=new URLSearchParams(window.location.search).get("mode");const active=current&&modes.has(current)?current:(mode??"Meal");const res=await fetch("/api/vision",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:active,imageDataUrl})});if(res.status===503){setEnabled(false);return}if(!res.ok)throw new Error("vision");const data=await res.json() as VisionResult;setResult(data);setEnabled(true)}catch{setError("Home couldn’t read that photo. The manual controls underneath still work.")}finally{setLoading(false)}};document.addEventListener("change",onChange,true);return()=>document.removeEventListener("change",onChange,true)},[enabled,mode,path]);
 const applyItem=(item:VisionItem,index:number)=>{if(!item.id)return;const ingredient=getIngredient(item.id);if(ingredient){const current=h.ingredientStock[item.id]??0;if(ingredient.tracking==="state"){const next=item.quantity==null?Math.max(1,current):Math.max(0,Math.min(3,Math.round(item.quantity)));h.setIngredient(item.id,next)}else{const q=clampQty(item.quantity);if(q==null)return;const addMode=mode==="Receipt";h.setIngredient(item.id,addMode?current+q:q)}if(item.useSoon&&!h.useSoon[item.id])h.toggleUseSoon(item.id);setApplied(v=>({...v,[`${index}:${item.id}`]:true}));return}const prep=prepComponents.find(c=>c.id===item.id);if(prep&&mode==="Freezer"){const q=clampQty(item.quantity);if(q==null)return;h.setComponent(item.id,q);setApplied(v=>({...v,[`${index}:${item.id}`]:true}))}};
 if(path!=="/scan"||enabled===false||(!loading&&!result&&!error))return null;
 return <aside className={styles.panel} aria-live="polite"><div className={styles.head}><div><span>HOME VISION</span><strong>{loading?"Looking carefully…":result?.summary||"Photo review"}</strong><p>{mode==="Prep"||mode==="Meal"?"Visual guidance only. Appearance cannot replace temperature or food-safety checks.":"Home proposes changes. Nothing enters Kitchen until you confirm it."}</p></div>{!loading&&<button className={styles.close} onClick={()=>{setResult(null);setError("")}} aria-label="Close photo review">×</button>}</div>{loading&&<div className={styles.loading}><i/>Reading the photo…</div>}{error&&<div className={styles.error}>{error}</div>}{result&&<>{(result.cookingCue||result.assessment)&&<div className={styles.cue}><strong>{result.cookingCue?"COOKING CUE":"ASSESSMENT"}</strong><p>{result.cookingCue||result.assessment}</p></div>}{result.items?.length>0&&<div className={styles.items}>{result.items.filter(item=>item.id||item.name).map((item,index)=>{const key=`${index}:${item.id??item.name}`;const done=!!applied[key];return <div key={key} className={`${styles.item} ${done?styles.done:""}`}><div><strong>{item.name}{item.confidence>=.8&&<span className={styles.badge}>high confidence</span>}</strong><small>{item.quantity==null?"quantity uncertain":`${item.quantity} ${item.unit??""}`} · {Math.round(item.confidence*100)}% confidence{item.useSoon?" · use soon":""}</small></div>{item.id&&item.quantity!=null&&(mode==="Fridge"||mode==="Freezer"||mode==="Pantry"||mode==="Receipt")&&<button disabled={done} onClick={()=>applyItem(item,index)}>{done?"Added ✓":mode==="Receipt"?"Add":"Confirm"}</button>}</div>})}</div>}{result.warnings?.length>0&&<div className={styles.warnings}>{result.warnings.join(" · ")}</div>}<div className={styles.actions}><button className={styles.secondary} onClick={()=>setResult(null)}>Keep manual</button></div></>}</aside>;
}
