"use client";
import {useEffect,useRef,useState} from "react";
import {JoshPresenceAnchor} from "./JoshPresence";
import styles from "./VoiceRuntime.module.css";

const STATE_KEY="home-meals-household-v12";
type Status="idle"|"connecting"|"listening"|"thinking"|"error";
type Mutation={type:string;[key:string]:unknown};
type Reply={text:string;mealIds?:string[];tags?:string[];href?:string|null;action?:string|null;mutation?:Mutation|null};
function householdState(){try{const raw=localStorage.getItem(STATE_KEY);if(!raw)return {version:12};const value=JSON.parse(raw);return value&&typeof value==="object"?value:{version:12}}catch{return {version:12}}}
function fillAsk(text:string){let attempts=0;const fill=()=>{const input=document.querySelector<HTMLInputElement>("[data-ask-composer] input");if(!input){if(attempts++<14){window.dispatchEvent(new Event("home-meals:ask"));window.setTimeout(fill,120)}return}const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")?.set;setter?.call(input,text);input.dispatchEvent(new Event("input",{bubbles:true}));window.setTimeout(()=>input.form?.requestSubmit(),30)};window.dispatchEvent(new Event("home-meals:ask"));window.setTimeout(fill,100)}
function sleep(ms:number){return new Promise(resolve=>window.setTimeout(resolve,ms))}

export function VoiceRuntime(){
 const[status,setStatus]=useState<Status>("idle");const[message,setMessage]=useState("");const pcRef=useRef<RTCPeerConnection|null>(null);const streamRef=useRef<MediaStream|null>(null);const audioRef=useRef<HTMLAudioElement|null>(null);const dcRef=useRef<RTCDataChannel|null>(null);const transcriptRef=useRef("");const handledRef=useRef(new Set<string>());
 const stop=()=>{try{if(dcRef.current?.readyState==="open")dcRef.current.send(JSON.stringify({type:"session.close",event_id:crypto.randomUUID()}))}catch{}dcRef.current=null;pcRef.current?.close();pcRef.current=null;streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(audioRef.current){audioRef.current.pause();audioRef.current.srcObject=null;audioRef.current=null}transcriptRef.current="";handledRef.current.clear();setStatus("idle");setMessage("")};
 const fallbackSpeech=()=>{const W=window as typeof window & {SpeechRecognition?:new()=>any;webkitSpeechRecognition?:new()=>any};const Recognition=W.SpeechRecognition||W.webkitSpeechRecognition;if(!Recognition){setMessage("Voice isn’t available in this browser yet.");setStatus("error");return}const rec=new Recognition();rec.lang="en-SG";rec.interimResults=false;rec.maxAlternatives=1;rec.onstart=()=>setStatus("listening");rec.onresult=(e:any)=>{const text=e.results?.[0]?.[0]?.transcript??"";setStatus("idle");if(text)fillAsk(text)};rec.onerror=()=>{setMessage("I couldn’t hear that clearly. Try again or type it.");setStatus("error")};rec.onend=()=>setStatus(s=>s==="listening"?"idle":s);rec.start()};
 const sendCommentary=(delegationId:string,content:string)=>{const dc=dcRef.current;if(dc?.readyState!=="open")return;dc.send(JSON.stringify({type:"session.commentary.append",event_id:crypto.randomUUID(),delegation_id:delegationId,content:content.slice(0,1800)}))};
 const handleDelegation=async(delegationId:string)=>{if(!delegationId||handledRef.current.has(delegationId))return;handledRef.current.add(delegationId);setStatus("thinking");await sleep(320);let question=transcriptRef.current.trim();if(!question){await sleep(350);question=transcriptRef.current.trim()}transcriptRef.current="";if(!question){sendCommentary(delegationId,"I didn’t catch that clearly. Say it again for me.");setStatus("listening");return}try{const res=await fetch("/api/ask-home",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question,state:householdState()})});if(!res.ok)throw new Error("ask_failed");const reply=await res.json() as Reply;const mutation=reply.mutation&&reply.mutation.type!=="none"?reply.mutation:null;if(mutation)window.dispatchEvent(new CustomEvent("home-meals:voice-proposal",{detail:{question,reply}}));sendCommentary(delegationId,`${reply.text}${mutation?" I’ve put that change on screen for you to confirm.":""}`);setStatus("listening")}catch{sendCommentary(delegationId,"I couldn’t check that just now. Nothing has changed. Try me again in a moment.");setStatus("listening")}};
 const start=async()=>{if(status==="connecting")return;if(pcRef.current){stop();return}setStatus("connecting");setMessage("");try{if(!navigator.mediaDevices?.getUserMedia||typeof RTCPeerConnection==="undefined"){fallbackSpeech();return}const pc=new RTCPeerConnection();pcRef.current=pc;const audio=new Audio();audio.autoplay=true;audioRef.current=audio;pc.ontrack=e=>{audio.srcObject=e.streams[0]};const stream=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=stream;for(const track of stream.getTracks())pc.addTrack(track,stream);const dc=pc.createDataChannel("oai-events");dcRef.current=dc;dc.addEventListener("message",event=>{try{const data=JSON.parse(event.data);if(data?.type==="session.started"){setStatus("listening");return}if(data?.type==="session.input_transcript.delta"&&typeof data.delta==="string"){transcriptRef.current+=data.delta;return}if(data?.type==="session.delegation.created"&&data?.delegation?.target==="client"){void handleDelegation(String(data.delegation.id||""));return}if(data?.type==="session.closed"){stop();return}if(data?.type==="error"){setMessage(data?.error?.message?`Voice: ${String(data.error.message).slice(0,140)}`:"Voice hit a connection error. You can still type instead.");setStatus("error")}}catch{}});const offer=await pc.createOffer();await pc.setLocalDescription(offer);if(pc.iceGatheringState!=="complete")await new Promise<void>(resolve=>{const timeout=setTimeout(resolve,1800);const done=()=>{if(pc.iceGatheringState==="complete"){clearTimeout(timeout);pc.removeEventListener("icegatheringstatechange",done);resolve()}};pc.addEventListener("icegatheringstatechange",done)});const res=await fetch("/api/live",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sdp:pc.localDescription?.sdp??offer.sdp})});if(res.status===503){pc.close();pcRef.current=null;stream.getTracks().forEach(t=>t.stop());streamRef.current=null;fallbackSpeech();return}if(!res.ok)throw new Error("live_failed");const live=await res.json() as {sdp?:string};if(!live.sdp)throw new Error("live_answer_missing");await pc.setRemoteDescription({type:"answer",sdp:live.sdp});pc.onconnectionstatechange=()=>{if(["failed","closed"].includes(pc.connectionState)){setMessage("Voice connection ended. Tap the mic to try again.");setStatus("error")}}}catch{pcRef.current?.close();pcRef.current=null;streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;dcRef.current=null;fallbackSpeech()}};
 useEffect(()=>{const custom=()=>start();const capture=(event:MouseEvent)=>{const target=event.target instanceof Element?event.target:null;if(!target?.closest('button[aria-label="Talk to Home"]'))return;event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();start()};window.addEventListener("home-meals:voice",custom);document.addEventListener("click",capture,true);return()=>{window.removeEventListener("home-meals:voice",custom);document.removeEventListener("click",capture,true);pcRef.current?.close();streamRef.current?.getTracks().forEach(t=>t.stop())}},[status]);
 if(status==="idle")return null;const expression=status==="thinking"?"thinking":status==="listening"?"talk":status==="error"?"sheepish":"thinking";return <div className={`${styles.voice} ${status==="error"?styles.error:""}`} role="status"><JoshPresenceAnchor priority={90} expression={expression} size={44} observeVisibility={false} className={styles.josh}/><span><strong>{status==="connecting"?"One sec…":status==="thinking"?"Let me check…":status==="listening"?"I’m listening":"Voice needs attention"}</strong>{message&&<small>{message}</small>}</span><button onClick={status==="error"?()=>{setStatus("idle");setMessage("")}:stop}>{status==="error"?"Dismiss":"Stop"}</button></div>;
}
