import Link from "next/link";
import { FoundationArchitecture, PortionLanguage, PrepTimelineGraphic, StorageGraphic } from "@/components/FoundationVisuals";
import { foundationImages } from "@/data/foundation-assets";

const guides=[
 {slug:"system",eyebrow:"START HERE",title:"How Home Meals works",blurb:"Mother → mid → booster → fresh dinner. Understand why we prep labour rather than finished meals."},
 {slug:"cubes",eyebrow:"15 / 30 / 60 / 90",title:"Portion language",blurb:"The measured freezer modules that make recipes repeatable instead of vague."},
 {slug:"prep-day",eyebrow:"TWO SESSIONS",title:"Prep-day architecture",blurb:"How six mothers and the core modifiers are sequenced without turning the kitchen into chaos."},
 {slug:"freezer",eyebrow:"PHYSICAL OS",title:"Freezer organisation",blurb:"A consistent home for bases, raw proteins, vegetables and carbs — built for JB heat and humidity."},
 {slug:"protein",eyebrow:"KEEP IT FRESH",title:"Protein portioning",blurb:"Why most protein stays raw until dinner, and how to freeze one-dinner packs cleanly."},
 {slug:"rice",eyebrow:"CARB MODULE",title:"Freezing rice properly",blurb:"Thin meal portions, safe cooling and reheating without one giant frozen brick."},
 {slug:"storage",eyebrow:"JB / SG",title:"Cold-storage rules",blurb:"What belongs in freezer, fridge and pantry, with the temperatures that govern the system."},
 {slug:"builder",eyebrow:"VALID COMBINATIONS",title:"Build a meal",blurb:"Use flexibility without culinary nonsense: the builder only surfaces combinations represented in the researched cookbook."}
];

export default function LearnPage(){return <div className="page researched-learn"><header className="topbar"><div><span className="eyebrow">LEARN · VISUAL OPERATING MANUAL</span><h1>Understand the kitchen, not just the recipe.</h1><p>Everything here is tied to the live Home Meals system: measured modules, prep order, freezer organisation, storage and valid meal construction.</p></div><Link href="/prep" className="primary-button">Open foundation →</Link></header><section className="learn-hero"><img src={foundationImages.freezer} alt="Organised Home Meals freezer"/><div><span className="eyebrow">THE PHYSICAL SYSTEM</span><h2>The freezer is part of the interface.</h2><p>Consistent drawers, measured modules and machine-readable labels make dinner faster today and camera reconciliation possible later.</p></div></section><div className="guide-grid researched-guides">{guides.map((guide,i)=><Link href={`/learn/${guide.slug}`} key={guide.slug} className="guide-card"><div className={`guide-visual visual-${(i%4)+1}`}><span>{String(i+1).padStart(2,"0")}</span></div><div><span className="eyebrow">{guide.eyebrow}</span><h3>{guide.title}</h3><p>{guide.blurb}</p><span className="text-button">Open guide →</span></div></Link>)}</div><FoundationArchitecture/><PortionLanguage/><PrepTimelineGraphic/><StorageGraphic/><section className="learn-actions"><Link href="/prep/groceries"><span>SHOP</span><strong>Foundation grocery checklist</strong><b>→</b></Link><Link href="/prep/day"><span>PREP</span><strong>Guided two-session prep mode</strong><b>→</b></Link><Link href="/cook"><span>COOK</span><strong>Researched recipe library</strong><b>→</b></Link></section></div>}
