import Link from "next/link";
import { notFound } from "next/navigation";
import { guides } from "@/data/home-meals";
import { CubeScale, FreezerMap, MealTransformation, SystemLayers } from "@/components/SystemInfographics";

const content: Record<string,{intro:string;steps:string[];rules:string[]}>= {
  system:{intro:"Home Meals is a hierarchy, not a recipe folder. The mother base stores slow reusable work. A mid-base creates a directional identity. Boosters and fresh finishers add the final specificity while the protein, vegetables and texture are still cooked fresh.",steps:["Choose the protein or vegetable anchor.","Choose one of the eight mother bases.","Add a mid-base only when a more specific direction is wanted.","Add fresh finishers, vegetables and a carb.","Choose the cooking architecture: pan, stir-fry, oven, air fryer, braise, one-pot or pasta."],rules:["Mother bases stay broader than finished sauces.","Mid-bases are directional, not another set of mother sauces.","Most protein stays raw until dinner."]},
  cubes:{intro:"Standardised portions turn the freezer into a language. Base, mid-base and booster volumes are intentionally different because they do different jobs.",steps:["30 ml for boosters and concentrated directional mids.","60 ml for aromatic mother bases and substantial mids.","90 ml for sauce-bodied mother bases such as RED and FIRE.","125–250 ml only for finished curries, ragù, dhal or soup when deliberately freezing a whole meal."],rules:["Label CODE / ML / DATE.","Freeze in stackable measured trays.","Recipes use cube counts instead of vague scoops."]},
  "prep-day":{intro:"Prep day should build the parts that save meaningful work later, not manufacture every item in the library every weekend.",steps:["Choose the upcoming menu first.","Start the longest-cooking mother bases.","Make directional mids while mother bases reduce.","Cool and portion by standard module size.","Portion raw proteins and rice only after the sauce work is under control."],rules:["Own the library; prep only what stock and the menu require.","Work long-cook → short-cook → cold prep.","Do not make every base just because it is prep day."]},
  freezer:{intro:"The freezer layout is part of the operating system. Consistent zones make dinner faster and eventually make camera recognition much more reliable.",steps:["Drawer 1: mother bases + directional mid-bases + boosters.","Drawer 2: one-dinner protein and fish portions.","Drawer 3: frozen vegetables, rice, bread and other carbs."],rules:["Nothing enters unlabelled.","Newest stock goes behind older stock.","Base codes and portion size must be visible from above."]},
  protein:{intro:"Most proteins stay raw because pre-cooking them is where a modular food system starts tasting like conventional meal prep.",steps:["Trim and portion one dinner at a time.","Freeze plain or in a light neutral marinade.","Lay bags flat until frozen, then file vertically.","Move tomorrow's portion to the fridge when useful."],rules:["Keep several portions completely plain.","Avoid marinades that lock every piece into one cuisine.","Use internal temperature rather than photographs as the authority for doneness."]},
  rice:{intro:"Rice is one of the highest-value freezer modules if it is portioned correctly.",steps:["Cook normally.","Cool safely and portion while still supple.","Freeze as thin single-meal packs rather than a thick block.","Reheat with a touch of moisture until steaming hot."],rules:["Label jasmine vs basmati.","One pack equals one normal dinner quantity.","Thin packages stack and thaw quickly."]},
  storage:{intro:"JB heat and humidity justify a more freezer-first pantry than a temperate-climate kitchen.",steps:["Freezer: bases, mids, proteins, rice, bread, nuts and excess dry ingredients.","Fridge: cheese, opened condiments, tortillas and selected pastes.","Pantry: sealed dry food with reliable turnover."],rules:["Use airtight containers.","Keep the pantry intentionally small.","Every freezer item gets CODE / DATE / PORTION."]},
  builder:{intro:"The meal formula explains why eight mother bases can support a large, varied menu without requiring dozens of unrelated ingredients.",steps:["PROTEIN","+ MOTHER BASE","+ OPTIONAL MID-BASE","+ FRESH FINISHER","+ VEGETABLE","+ CARB","+ COOKING METHOD"],rules:["Rotate cooking method as well as flavour.","Use perishables first.","Let inventory narrow choices rather than create more browsing."]}
};
export default async function GuidePage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const guide=guides.find(g=>g.slug===slug);const body=content[slug];if(!guide||!body)notFound();return <div className="page guide-detail"><Link href="/learn" className="back-link">← Learn</Link><header className="guide-detail-hero"><span className="eyebrow">{guide.eyebrow}</span><h1>{guide.title}</h1><p>{body.intro}</p></header>{slug==="system"&&<SystemLayers/>}<section className="guide-steps"><div><span className="eyebrow">THE FLOW</span><h2>How it works.</h2></div><ol>{body.steps.map((step,i)=><li key={step}><span>{String(i+1).padStart(2,"0")}</span><strong>{step}</strong></li>)}</ol></section><section className="guide-rules"><span className="eyebrow">HOUSE RULES</span>{body.rules.map(rule=><div key={rule}>{rule}</div>)}</section>{slug==="cubes"&&<CubeScale/>}{slug==="freezer"&&<FreezerMap/>}{(slug==="system"||slug==="builder")&&<MealTransformation/>}<section className="guide-photo-strip"><span className="eyebrow">VISUAL GUIDE · PRODUCTION SLOTS</span><div>{["Overview","Close-up","Correct cue","Common mistake"].map((x,i)=><figure key={x}><div>{i+1}</div><figcaption>{x}</figcaption></figure>)}</div></section></div>}
