import Link from "next/link";
import { notFound } from "next/navigation";
import { guides } from "@/data/home-meals";
import { CubeScale, FreezerMap, MealTransformation } from "@/components/SystemInfographics";

const content: Record<string,{intro:string;steps:string[];rules:string[]}>= {
  system:{intro:"Home Meals is designed around reusable work, not reheated finished meals. The freezer holds concentrated labour, while dinner stays fresh.",steps:["Choose a protein or vegetable anchor.","Choose the mother base that sets the direction.","Add a finisher that makes the base culturally and texturally specific.","Add vegetables and a carb.","Choose the cooking architecture: pan, stir-fry, oven, air fryer, braise or pasta."],rules:["Mother bases should not taste like finished dishes.","Most protein stays raw until dinner.","Do the slow aromatic work once; do the fresh texture work tonight."]},
  cubes:{intro:"Standardised portions turn the freezer into a language. You should know what a cube does before you thaw it.",steps:["30 ml for boosters and intense concentrates.","60 ml for strong aromatic and masala bases.","90 ml for main sauce foundations such as RED and FIRE.","125–250 ml only for finished curries, ragù, dhal or soup."],rules:["Label BASE / ML / DATE.","Freeze flat or in stackable trays.","Design recipes around cube counts instead of vague scoops."]},
  "prep-day":{intro:"Prep day should remove friction from future dinners, not consume the whole weekend.",steps:["Start the longest-cooking onion/tomato bases first.","While they reduce, process boosters and herbs.","Cool bases rapidly before filling moulds.","Portion raw proteins flat in one-dinner packs.","Finish with cooked rice portions and freezer labels."],rules:["Work from long cook → short cook → cold prep.","Do not make every base just because it is prep day.","Prep against forecast stock, not habit."]},
  freezer:{intro:"The freezer layout is part of the software design. A consistent physical arrangement makes human use faster and future camera recognition easier.",steps:["Drawer 1: mother bases and booster cubes.","Drawer 2: one-dinner protein and fish portions.","Drawer 3: frozen vegetables, rice, bread and other carbs."],rules:["Nothing enters unlabelled.","Newest stock goes behind older stock.","Keep visually distinct labels for base code and size."]},
  protein:{intro:"Most proteins are frozen raw because precooking is where homemade meal systems start tasting like meal prep.",steps:["Trim and portion one dinner at a time.","Freeze plain or in a very light neutral marinade.","Lay bags flat until frozen, then file vertically.","Move tomorrow's portion to the fridge when useful."],rules:["Keep some portions completely plain.","Avoid marinades that lock the protein to one cuisine.","Use temperature, not photographs, as the authority for doneness."]},
  rice:{intro:"Rice is one of the easiest useful freezer modules if it is portioned correctly.",steps:["Cook normally.","Cool safely and portion while still supple.","Freeze in thin single-meal portions rather than a thick block.","Reheat with a touch of moisture until steaming hot."],rules:["Label jasmine vs basmati.","One pack should equal one dinner quantity.","Thin packages stack and thaw faster."]},
  storage:{intro:"JB heat and humidity change the operating model. Home Meals deliberately moves more ingredients into cold storage than a temperate-climate pantry would.",steps:["Freezer: sauces, proteins, rice, bread, nuts and excess flour.","Fridge: cheese, opened condiments, tortillas and selected pastes.","Pantry: sealed dry food with reliable turnover."],rules:["Use airtight containers.","Keep the pantry intentionally small.","Every freezer item gets NAME / DATE / PORTION."]},
  builder:{intro:"The meal formula is the fastest way to understand why a small freezer can create a large menu.",steps:["PROTEIN","+ BASE","+ MID-BASE / FINISHER","+ VEGETABLE","+ CARB","+ COOKING METHOD"],rules:["Rotate cooking method as well as flavour.","Use perishables first.","Let inventory narrow choices rather than create more browsing."]}
};
export default async function GuidePage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const guide=guides.find(g=>g.slug===slug);const body=content[slug];if(!guide||!body)notFound();return <div className="page guide-detail"><Link href="/learn" className="back-link">← Learn</Link><header className="guide-detail-hero"><span className="eyebrow">{guide.eyebrow}</span><h1>{guide.title}</h1><p>{body.intro}</p></header><section className="guide-steps"><div><span className="eyebrow">THE FLOW</span><h2>How it works.</h2></div><ol>{body.steps.map((step,i)=><li key={step}><span>{String(i+1).padStart(2,"0")}</span><strong>{step}</strong></li>)}</ol></section><section className="guide-rules"><span className="eyebrow">HOUSE RULES</span>{body.rules.map(rule=><div key={rule}>{rule}</div>)}</section>{slug==="cubes"&&<CubeScale/>}{slug==="freezer"&&<FreezerMap/>}{(slug==="system"||slug==="builder")&&<MealTransformation/>}<section className="guide-photo-strip"><span className="eyebrow">VISUAL GUIDE · PLACEHOLDERS</span><div>{["Overview","Close-up","Correct cue","Common mistake"].map((x,i)=><figure key={x}><div>{i+1}</div><figcaption>{x}</figcaption></figure>)}</div></section></div>}
