import {NextRequest,NextResponse} from "next/server";
import {ingredients,recipes,getRecipe} from "@/data/home-data";
import {canonicalPrepComponentsV2,getCanonicalPrepV2,recipePrepV2} from "@/data/food-truth-v2";
import {recipeTitle} from "@/data/recipe-display";

export const dynamic="force-dynamic";
const validRecipeIds=new Set(recipes.map(r=>r.id));
const validIngredientIds=new Set(ingredients.map(i=>i.id));
const validComponentIds=new Set(canonicalPrepComponentsV2.map(c=>c.id));
type QuantityV2={qty:number;unit:"g"|"ml"|"count"};
type State={version?:number;week?:string[];componentStock?:Record<string,number>;componentStockV2?:Record<string,QuantityV2>;ingredientStock?:Record<string,number>;useSoon?:Record<string,boolean>;favourites?:Record<string,boolean>;ratings?:Record<string,{josh?:number;g?:number}>;history?:{mealId:string;at:string}[];recipeNotes?:Record<string,{author:string;text:string;at:string}[]>;prepBatches?:{componentId:string;remainingMl?:number;outputMl?:number;at:string}[];componentBatches?:{componentId:string;remaining?:QuantityV2;producedAt?:string}[];kitchenReady?:boolean};
type Mutation={type:"none"|"set_day"|"set_ingredient"|"set_component"|"set_use_soon"|"add_note"|"set_favourite";dayIndex:number|null;mealId:string|null;ingredientId:string|null;componentId:string|null;quantity:number|null;value:boolean|null;note:string|null;author:"josh"|"g"|"home"|null};
function noStore(body:unknown,status=200){return NextResponse.json(body,{status,headers:{"Cache-Control":"no-store"}})}
function outputText(data:any){if(typeof data?.output_text==="string")return data.output_text;for(const item of data?.output??[])for(const content of item?.content??[])if(content?.type==="output_text"&&typeof content.text==="string")return content.text;return ""}
function householdContext(state:State){
 const week=(state.week??[]).map((id,i)=>({day:i,mealId:id,title:validRecipeIds.has(id)?recipeTitle(id,getRecipe(id).title):id}));
 const prepV2=canonicalPrepComponentsV2.map(c=>{const value=state.componentStockV2?.[c.id];if(!value||value.qty<=0)return null;return{id:c.id,code:c.code,name:c.name,qty:value.qty,unit:value.unit,truth:"v2"}}).filter(Boolean);
 const legacyPrep=state.version===12?[]:canonicalPrepComponentsV2.map(c=>({id:c.id,code:c.code,name:c.name,legacyMl:Math.max(0,Number(state.componentStock?.[c.id]??0)),truth:"legacy-v11-ml"})).filter(x=>x.legacyMl>0);
 const stocked=ingredients.map(i=>({id:i.id,name:i.name,qty:Math.max(0,Number(state.ingredientStock?.[i.id]??0)),unit:i.unit,useSoon:!!state.useSoon?.[i.id]})).filter(x=>x.qty>0||x.useSoon).slice(0,120);
 const favourites=recipes.filter(r=>state.favourites?.[r.id]).map(r=>({id:r.id,title:recipeTitle(r.id,r.title)}));
 const ratings=Object.entries(state.ratings??{}).filter(([id])=>validRecipeIds.has(id)).map(([id,v])=>({id,title:recipeTitle(id,getRecipe(id).title),josh:v.josh??null,g:v.g??null}));
 const recent=(state.history??[]).slice(0,12).filter(x=>validRecipeIds.has(x.mealId)).map(x=>({id:x.mealId,title:recipeTitle(x.mealId,getRecipe(x.mealId).title),at:x.at}));
 const notes=Object.entries(state.recipeNotes??{}).flatMap(([id,list])=>validRecipeIds.has(id)?(list??[]).slice(0,2).map(n=>({id,title:recipeTitle(id,getRecipe(id).title),author:n.author,text:n.text,at:n.at})):[]).slice(0,20);
 const batchesV2=(state.componentBatches??[]).filter(b=>b.remaining&&b.remaining.qty>0).slice(0,30);
 const legacyBatches=state.version===12?[]:(state.prepBatches??[]).filter(b=>(b.remainingMl??b.outputMl??0)>0).slice(0,30);
 const catalog=recipes.map(r=>({id:r.id,title:recipeTitle(r.id,r.title),minutes:r.minutes,cuisine:r.cuisine,ingredients:r.ingredients.filter(x=>!x.optional).map(x=>x.id),prep:recipePrepV2(r.id).map(x=>({id:x.componentId,qty:x.quantity.qty,unit:x.quantity.unit}))}));
 return {version:state.version??11,kitchenReady:!!state.kitchenReady,week,prepV2,legacyPrep,stocked,favourites,ratings,recent,notes,batchesV2,legacyBatches,catalog,truthContract:{componentQuantities:"g/ml/count only; never infer g↔ml",nutrition:"not available unless deterministic household data supplies it",safety:"never infer safe internal temperature from appearance"}}
}
function cleanMutation(raw:any,stateVersion:number|undefined):Mutation|null{const none:Mutation={type:"none",dayIndex:null,mealId:null,ingredientId:null,componentId:null,quantity:null,value:null,note:null,author:null};if(!raw||typeof raw!=="object")return null;const type=String(raw.type||"none") as Mutation["type"];const m:{[K in keyof Mutation]:Mutation[K]}={...none,type};if(!["none","set_day","set_ingredient","set_component","set_use_soon","add_note","set_favourite"].includes(type))return null;m.dayIndex=Number.isInteger(raw.dayIndex)&&raw.dayIndex>=0&&raw.dayIndex<7?raw.dayIndex:null;m.mealId=typeof raw.mealId==="string"&&validRecipeIds.has(raw.mealId)?raw.mealId:null;m.ingredientId=typeof raw.ingredientId==="string"&&validIngredientIds.has(raw.ingredientId)?raw.ingredientId:null;m.componentId=typeof raw.componentId==="string"&&validComponentIds.has(raw.componentId)?raw.componentId:null;m.quantity=Number.isFinite(raw.quantity)?Math.max(0,Number(raw.quantity)):null;m.value=typeof raw.value==="boolean"?raw.value:null;m.note=typeof raw.note==="string"?raw.note.trim().slice(0,500):null;m.author=raw.author==="josh"||raw.author==="g"||raw.author==="home"?raw.author:null;if(type==="set_component"&&stateVersion!==12)return null;const ok=type==="none"||(type==="set_day"&&m.dayIndex!=null&&m.mealId)||(type==="set_ingredient"&&m.ingredientId&&m.quantity!=null)||(type==="set_component"&&m.componentId&&m.quantity!=null)||(type==="set_use_soon"&&m.ingredientId&&m.value!=null)||(type==="add_note"&&m.mealId&&m.note)||(type==="set_favourite"&&m.mealId&&m.value!=null);return ok?m:null}

export async function GET(){return noStore({configured:!!process.env.OPENAI_API_KEY?.trim()})}
export async function POST(req:NextRequest){const key=process.env.OPENAI_API_KEY?.trim();if(!key)return noStore({error:"ai_not_configured"},503);const body=await req.json().catch(()=>null) as {question?:unknown;state?:State}|null;const question=typeof body?.question==="string"?body.question.trim():"";if(!question)return noStore({error:"question_required"},400);const state=body?.state??{};const context=householdContext(state);const mutationSchema={type:"object",additionalProperties:false,required:["type","dayIndex","mealId","ingredientId","componentId","quantity","value","note","author"],properties:{type:{type:"string",enum:["none","set_day","set_ingredient","set_component","set_use_soon","add_note","set_favourite"]},dayIndex:{type:["integer","null"]},mealId:{type:["string","null"]},ingredientId:{type:["string","null"]},componentId:{type:["string","null"]},quantity:{type:["number","null"]},value:{type:["boolean","null"]},note:{type:["string","null"]},author:{type:["string","null"],enum:["josh","g","home",null]}}};const schema={type:"object",additionalProperties:false,required:["text","mealIds","tags","href","action","mutation"],properties:{text:{type:"string"},mealIds:{type:"array",items:{type:"string"},maxItems:4},tags:{type:"array",items:{type:"string"},maxItems:6},href:{type:["string","null"]},action:{type:["string","null"]},mutation:mutationSchema}};
 try{const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_MODEL?.trim()||"gpt-5.6-sol",store:false,max_output_tokens:650,instructions:"You are Home, the private household kitchen assistant for Josh and G. Be concise and practical. Use only supplied household state for stock, batches, history, preferences and plan. Never invent inventory, component yields, calories/macros, expiry, allergens, validated substitutions or safe temperatures. Component quantities use their supplied canonical unit; never convert g to ml or ml to g. Legacy v11 prep values are historical ml-only data and must not be treated as v2 mass truth. If nutrition or safety evidence is missing, say so. Prefer stocked meals, use-soon food, favourites/ratings and avoid recent repeats. You may PROPOSE one household mutation only when the user explicitly asks to change something. Never mutate implicitly from a suggestion question. set_component is allowed only for v12 state and its quantity is in that component's canonical unit. The client always asks for confirmation before applying it. href must be an internal path or null. Return only the structured object.",input:[{role:"user",content:[{type:"input_text",text:JSON.stringify({question,household:context})}]}],text:{format:{type:"json_schema",name:"home_meals_reply",strict:true,schema}}})});if(!response.ok)return noStore({error:"ai_failed",status:response.status},502);const data=await response.json();const raw=outputText(data);if(!raw)return noStore({error:"ai_empty"},502);const parsed=JSON.parse(raw) as {text:string;mealIds:string[];tags:string[];href:string|null;action:string|null;mutation:Mutation};const mealIds=(parsed.mealIds??[]).filter(id=>validRecipeIds.has(id)).slice(0,4);const href=typeof parsed.href==="string"&&parsed.href.startsWith("/")&&!parsed.href.startsWith("//")?parsed.href:null;return noStore({text:String(parsed.text||""),mealIds,tags:(parsed.tags??[]).map(String).slice(0,6),href,action:parsed.action?String(parsed.action):null,mutation:cleanMutation(parsed.mutation,state.version),source:"ai"})}catch(error){return noStore({error:"ai_failed",detail:error instanceof Error?error.message:"unknown"},502)}}
