"use client";
import Link from "next/link";
import {useEffect,useMemo,useRef,useState,type CSSProperties} from "react";
import {useHousehold} from "../HouseholdState";
import {getRecipe} from "@/data/home-data";
import {getRuntimeDinnerFormulationV4} from "@/data/runtime-dinner-v4";
import {getCanonicalPrepV2} from "@/data/food-truth-v2";
import {prepRequirementPacketTextV6} from "@/data/prep-portioning-v6";
import {recipeTitle} from "@/data/recipe-display";
import {feedback} from "@/lib/feedback";
import {getHouseholdPerson} from "@/lib/device-profile";
import {phaseFor} from "@/lib/steps";
import {toneFor} from "@/lib/tones";
import {HomeSays} from "./HomeSays";
import {Orb} from "./Orb";
import {Avatar,formatQty} from "./Primitives";

type CookSession={step:number;timerEnd:number|null;timerDone:boolean;updatedAt:number};
type StockReceipt={stockConsumed:boolean;prep:{id:string;plannedQty:number;deductedQty:number;unit:string}[];ingredients:{name:string;qty:number;unit:string}[]};
type Author="josh"|"g";
const noteChips=["More chilli","Less salt","Bigger portion","Perfect as is"];
function readCookSession(id:string,totalSteps:number):CookSession|null{if(typeof window==="undefined")return null;try{const raw=sessionStorage.getItem(`home-meals-cook:${id}`);if(!raw)return null;const s=JSON.parse(raw) as CookSession;if(!s||Date.now()-(s.updatedAt??0)>6*60*60*1000){sessionStorage.removeItem(`home-meals-cook:${id}`);return null}return {step:Math.max(0,Math.min(totalSteps-1,Number(s.step)||0)),timerEnd:Number(s.timerEnd)>Date.now()?Number(s.timerEnd):null,timerDone:!!s.timerDone&&!(Number(s.timerEnd)>Date.now()),updatedAt:Number(s.updatedAt)||Date.now()}}catch{return null}}

export function Cooking({id}:{id:string}){
 const h=useHousehold(),r=getRecipe(id),f=getRuntimeDinnerFormulationV4(id);if(!f)throw new Error(`Missing canonical dinner formulation: ${id}`);const total=f.steps.length;
 const initial=useRef<CookSession|null>(null);if(initial.current===null)initial.current=readCookSession(id,total);
 const[step,setStep]=useState(()=>initial.current?.step??0),[done,setDone]=useState(false),[startedAt]=useState(()=>Date.now());
 const[timer,setTimer]=useState(()=>initial.current?.timerEnd?Math.max(0,Math.ceil((initial.current.timerEnd-Date.now())/1000)):0),[timerEnd,setTimerEnd]=useState<number|null>(()=>initial.current?.timerEnd??null),[timerDone,setTimerDone]=useState(()=>initial.current?.timerDone??false);
 const[note,setNote]=useState(""),[author,setAuthor]=useState<Author>("josh"),[receipt,setReceipt]=useState<StockReceipt|null>(null),[elapsed,setElapsed]=useState(0);
 const tick=useRef<ReturnType<typeof setInterval>|null>(null),title=recipeTitle(r.id,r.title),sessionKey=`home-meals-cook:${id}`;
 const versions=h.recipeVersions[id]??[],currentVersion=versions[0]?.number??1,latest=versions[0],current=f.steps[step],suggested=current.timerMinutes??0,phase=phaseFor(step,total);
 const clearTick=()=>{if(tick.current){clearInterval(tick.current);tick.current=null}},stopTimer=()=>{clearTick();setTimer(0);setTimerEnd(null);setTimerDone(false)};
 const armTimer=(end:number)=>{clearTick();setTimerDone(false);setTimerEnd(end);setTimer(Math.max(0,Math.ceil((end-Date.now())/1000)));tick.current=setInterval(()=>{const left=Math.max(0,Math.ceil((end-Date.now())/1000));setTimer(left);if(!left){clearTick();setTimerEnd(null);setTimerDone(true);feedback("success")}},1000)};
 useEffect(()=>{const person=getHouseholdPerson();if(person)setAuthor(person)},[]);
 useEffect(()=>{let lock:any;const wake=async()=>{try{if("wakeLock" in navigator)lock=await (navigator as any).wakeLock.request("screen")}catch{}};wake();if(initial.current?.timerEnd)armTimer(initial.current.timerEnd);return()=>{lock?.release?.();clearTick()}},[]);
 useEffect(()=>{if(done)return;try{sessionStorage.setItem(sessionKey,JSON.stringify({step,timerEnd,timerDone,updatedAt:Date.now()} satisfies CookSession))}catch{}},[sessionKey,step,timerEnd,timerDone,done]);
 const startTimer=(mins:number)=>{armTimer(Date.now()+mins*60000);feedback("tap")},next=()=>{stopTimer();setStep(s=>Math.min(total-1,s+1));feedback("tap")},back=()=>{stopTimer();setStep(s=>Math.max(0,s-1));feedback("tap")},leave=()=>{stopTimer();try{sessionStorage.removeItem(sessionKey)}catch{}};
 const finish=()=>{if(done)return;stopTimer();try{sessionStorage.removeItem(sessionKey)}catch{}const stockConsumed=h.cookMeal(id);if(!stockConsumed)h.logMealWithoutStock(id);const prep=f.prep.map(x=>({id:x.componentId,plannedQty:x.quantity.qty,deductedQty:stockConsumed?x.quantity.qty:0,unit:x.quantity.unit}));setReceipt({stockConsumed,prep,ingredients:f.ingredients.filter(x=>!x.optional&&x.ingredientId!=="water").map(x=>({name:x.name,qty:x.qty,unit:x.unit}))});const mins=Math.max(1,Math.round((Date.now()-startedAt)/60000));setElapsed(mins);h.recordCookObservation({observationId:`${id}-${Date.now()}`,recipeId:id,cookedAt:new Date().toISOString(),activeMinutes:null,totalMinutes:mins,finishedWeightG:null,joshPlateWeightG:null,gPlateWeightG:null,leftoverWeightG:null,joshRating:null,gRating:null,heatFeedback:null});setDone(true);feedback("success")};
 const askHome=()=>{window.dispatchEvent(new Event("home-meals:ask"));feedback("tap")};const touch=useRef<{x:number;y:number}|null>(null);const onTouchStart=(e:React.TouchEvent)=>{touch.current={x:e.touches[0].clientX,y:e.touches[0].clientY}},onTouchEnd=(e:React.TouchEvent)=>{const s=touch.current;touch.current=null;if(!s)return;const dx=e.changedTouches[0].clientX-s.x,dy=e.changedTouches[0].clientY-s.y;if(Math.abs(dx)<60||Math.abs(dx)<Math.abs(dy)*1.5)return;if(dx<0){if(step<total-1)next()}else back()};
 const tip=current.warningCue??current.visualCue??(current.safetyTargetC?`Use a thermometer here: at least ${current.safetyTargetC}°C.`:latest?`Our v${currentVersion}: “${latest.summary}”`:step===total-1?"Say “done” and I’ll log the cook. Kitchen stock only changes when the recorded amounts fully support it.":"Swipe or say “next” when you’re ready.");

 if(done){const prepLine=receipt?.prep.filter(x=>x.deductedQty>0).map(x=>`${formatQty(x.deductedQty,x.unit)} ${getCanonicalPrepV2(x.id)?.code??x.id}`).join(" and ");const finishUp=()=>{const clean=note.trim();if(clean){h.noteMeal(id,clean,author);if(clean!==latest?.summary)h.promoteRecipeVersion(id,clean,author)}feedback("success")};return <div className="hm-done hm-screen flush" style={{paddingBottom:140}}><div className="stage">{r.image&&<img src={r.image} alt={title}/>}<div className="shade"/><div className="logged"><span className="hm-pill white">DINNER LOGGED</span></div></div><div className="body"><h1 className="title">That’s {title}<br/>done in {elapsed} min.</h1><HomeSays>{receipt?.stockConsumed?<>Kitchen was reconciled from the four-serving cook batch. {prepLine?<>Prep used: <b>{prepLine}</b>. </>:null}Exact ingredient stock was deducted where Home had an exact amount; qualitative pantry levels stay qualitative. For Josh + G, the normal plan is two portions now and two leftovers.</>:<>Dinner is in History, but Kitchen stock was left unchanged because the recorded Kitchen did not fully cover this recipe. Update Kitchen when useful; Home did not invent or partially deduct anything.</>}</HomeSays><div className="hm-list">{(["josh","g"] as const).map(w=><div key={w} className="hm-card lg hm-rate-row"><Avatar who={w} size="lg"/><div><div className="who">{w==="josh"?"Josh":"G"}</div><div className="hm-stars">{[1,2,3,4,5].map(n=><button key={n} className={(h.ratings[id]?.[w]??0)>=n?"on":""} aria-label={`${w} ${n} stars`} onClick={()=>{h.rateMeal(id,w,n);feedback("change")}}>★</button>)}</div></div></div>)}<div className="hm-card lg hm-notebox"><div className="who">Next time</div><div className="hm-authors sm" style={{marginTop:8}}>{(["josh","g"] as const).map(a=><button key={a} className={author===a?"on":""} onClick={()=>{setAuthor(a);feedback("tap")}}><Avatar who={a} size="sm"/>{a==="josh"?"Josh":"G"}</button>)}</div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="More chilli. Less salt. Bigger portion." aria-label="Note for next time"/><div className="chips">{noteChips.map(c=><button key={c} className="hm-chip tint" onClick={()=>setNote(v=>v?`${v.replace(/\.?\s*$/,"")}. ${c}.`:`${c}.`)}>{c}</button>)}</div></div><Link className="hm-card hm-version hm-lift" href={`/scan?mode=Meal&meal=${id}&back=${encodeURIComponent(`/cook/${id}`)}`}><div><span className="kick">PHOTO</span><strong>Save a photo of tonight</strong><small>Kept with the recipe on this phone.</small></div><span style={{fontSize:22,color:"var(--muted)"}}>›</span></Link></div></div><div className="hm-cta"><Link className="hm-btn primary" href={`/cook/${id}`} onClick={finishUp}>{note.trim()?`Save as our v${(latest?.summary===note.trim()?currentVersion:currentVersion+1)} →`:"Done →"}</Link></div></div>}

 return <div className="hm-cooking" onTouchStart={onTouchStart} onTouchEnd={onTouchEnd}><div className="stage">{r.image&&<img src={r.image} alt={title} loading="eager" fetchPriority="high"/>}<div className="shade"/><div className="top"><Link href={`/cook/${id}`} className="hm-round onphoto" aria-label="Leave cooking mode" onClick={leave}>×</Link><span className="hm-pill onphoto" style={{overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",maxWidth:"60%"}}>{title} · {step+1}/{total}</span><button onClick={askHome} aria-label="Ask Home" style={{display:"grid",placeItems:"center"}}><Orb size={44}/></button></div><div className="dots" aria-hidden="true">{f.steps.map((_,i)=><i key={i} style={i<=step?{background:phaseFor(i,total).gradient}:undefined}/>)}</div></div><div className="body"><div className="phase" style={{"--phase":phase.gradient} as CSSProperties}><b>{step+1}</b><span>{phase.name}{latest&&step===0?` · our v${currentVersion}`:""}</span></div><p className="text" key={step}>{current.instruction}</p>{current.visualCue&&<div className="hm-card tip"><span>Look for: {current.visualCue}</span></div>}{current.safetyTargetC&&<div className="hm-card tip"><span>Safety: thermometer ≥ {current.safetyTargetC}°C. Camera appearance cannot prove this.</span></div>}{suggested>0&&<div className="timer" aria-live="polite">{timerDone?<><strong className="done">Done ✓</strong><button onClick={()=>startTimer(suggested)}>Run again</button></>:timer>0?<><strong>{Math.floor(timer/60)}:{String(timer%60).padStart(2,"0")}</strong><button onClick={()=>startTimer(suggested)}>Restart</button></>:<><strong>{suggested}:00</strong><button onClick={()=>startTimer(suggested)}>Start timer</button></>}</div>}<details className="drawer"><summary>Ingredients &amp; prep · 4 servings ›</summary><div className="hm-ing">{f.prep.map(p=><span key={p.componentId}><i style={{background:toneFor(p.componentId)}}/>{prepRequirementPacketTextV6(p.componentId,p.quantity)}</span>)}{f.ingredients.map((x,i)=><span key={`${x.ingredientId}-${i}`} className={`plain ${x.optional?"optional":""}`}>{x.name} · {formatQty(x.qty,x.unit)}{x.optional?" · optional":""}</span>)}</div></details><div className="hm-card tip"><Orb size={30}/><span>{tip}</span></div></div><div className="foot"><div className="nav"><button className="hm-btn ghost" disabled={step===0} onClick={back}>Back</button>{step<total-1?<button className="hm-btn primary" onClick={next}>Next</button>:<button className="hm-btn primary" onClick={finish}>Done — log it</button>}</div><div className="hint">‹ swipe · or say “next” ›</div></div></div>;
}
