"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import {useHousehold} from "../HouseholdState";
import {baseRecipesV2} from "@/data/base-recipes-v2";
import {motherProcessImages} from "@/data/mother-process-assets";
import {midBases,motherBases,recipes} from "@/data/home-data";
import {batchOutputMl,prepDemandForWeekMl,stockPortions} from "@/data/stock-math";
import {feedback} from "@/lib/feedback";
import {useSheet} from "@/lib/useSheet";
import {Back,MealCard,SectionHead} from "./Primitives";

export function Mother({id}:{id:string}){
 const h=useHousehold();const m=motherBases.find(x=>x.id===id)!;const recipe=baseRecipesV2[id];const process=motherProcessImages[id]??[];const mids=midBases.filter(x=>x.parentMotherIds.includes(id));const[confirm,setConfirm]=useState(false);const[added,setAdded]=useState(false);useSheet(confirm,()=>setConfirm(false));const ml=h.componentStock[id]??0;const portions=stockPortions(id,h.componentStock);const batchMl=batchOutputMl(id);
 const weekDemand=prepDemandForWeekMl(h.week).find(x=>x.id===id);const short=h.prepNeeds.find(x=>x.id===id);const neededMl=weekDemand?.neededMl??0;
 const linked=useMemo(()=>{const viaMid=new Set(mids.map(x=>x.id));const all=recipes.filter(r=>r.motherIds.includes(id)||r.midIds.some(mid=>viaMid.has(mid)));return [...new Map(all.map(r=>[r.id,r])).values()]},[id,mids]);
 const batches=h.prepBatches.filter(b=>b.componentId===id&&(b.remainingMl??b.outputMl)>0).sort((a,b)=>new Date(a.at).getTime()-new Date(b.at).getTime());const datedMl=batches.reduce((sum,b)=>sum+(b.remainingMl??b.outputMl),0);const undatedMl=Math.max(0,ml-datedMl);const oldest=batches[0];const ageDays=oldest?Math.max(0,Math.floor((Date.now()-new Date(oldest.at).getTime())/86400000)):null;
 const finishBatch=()=>{h.makeBatch(id);setConfirm(false);setAdded(true);feedback("success");setTimeout(()=>setAdded(false),1800)};
 const hero=process.at(-1)?.url;
 return <div className="hm-page-v5 hm-mother-v5 hm-mother-v6"><Back href="/prep" label="Prep"/>
  <header className="hm-mother-head-v5 hm-mother-head-v6" style={{"--tone":m.tone} as React.CSSProperties}>{hero?<div className="hm-mother-photo-v6"><img src={hero} alt={`${m.name} frozen in measured portions`}/><span>{m.code}</span></div>:<div className="hm-base-cube-v5 big"><i/><b>{m.code}</b></div>}<div><span>{short?"THIS WEEK":"MOTHER BASE"}</span><h1>{m.name}</h1><p>{m.purpose}</p></div></header>
  <section className="hm-stock-action-v5 hm-stock-action-v6"><div><span>{short?"This week":"In the freezer"}</span><strong>{!h.kitchenReady?"Not checked":short?`${short.shortMl} ml short`:`${ml} ml`}</strong><small>{added?`${m.code} added to freezer ✓`:!h.kitchenReady?`Standard portion: ${m.portionMl} ml`:short?`Have ${ml} ml · need ${neededMl} ml`:neededMl?`Enough for this week · ${portions} standard ${portions===1?"portion":"portions"}`:`${portions} standard ${portions===1?"portion":"portions"}`}</small></div><button onClick={()=>setConfirm(true)}>{short?"Make for this week":"Make batch"}</button></section>

  {h.kitchenReady&&(oldest||undatedMl>0)&&<section className="hm-mother-batches-v34"><header><span>FREEZER LABELS</span><strong>{batches.length?`${batches.length} dated ${batches.length===1?"batch":"batches"}`:"No dated batches"}</strong></header>{oldest&&<div className="oldest"><b>USE FIRST</b><span><strong>{oldest.remainingMl??oldest.outputMl} ml</strong><small>Made {new Date(oldest.at).toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"})} · {ageDays===0?"today":`${ageDays} ${ageDays===1?"day":"days"} ago`}</small></span></div>}{batches.slice(1,4).map((b,i)=><div key={`${b.at}-${i}`}><b>{i+2}</b><span><strong>{b.remainingMl??b.outputMl} ml</strong><small>Made {new Date(b.at).toLocaleDateString(undefined,{day:"numeric",month:"short"})}</small></span></div>)}{undatedMl>0&&<div className="undated"><b>?</b><span><strong>{undatedMl} ml undated</strong><small>Counts as stock, but Home does not invent a made date.</small></span></div>}</section>}

  {process.length>0&&<section className="hm-block-v5 hm-process-v6"><SectionHead title="What it should look like" action={<span>Visual cues, not just minutes.</span>}/><div className="hm-process-rail-v6">{process.map((p,i)=><article key={p.url}><div><img src={p.url} alt={`${m.name}: ${p.stage.replace(/^\d+\s*·\s*/,"").toLowerCase()}`} loading={i<2?"eager":"lazy"}/><b>{String(i+1).padStart(2,"0")}</b></div><span>{p.stage.replace(/^\d+\s*·\s*/,"")}</span><p>{p.caption}</p></article>)}</div></section>}

  {recipe&&<><section className="hm-block-v5 hm-batch-recipe-v5 hm-batch-recipe-v6"><SectionHead title="What goes in"/><ul>{recipe.ingredients.map(x=><li key={x}>{x}</li>)}</ul></section><section className="hm-block-v5"><SectionHead title="Cook it"/><ol className="hm-step-list-v5">{recipe.method.map((x,i)=><li key={x}><b>{i+1}</b><p>{x}</p></li>)}</ol></section><section className="hm-block-v5"><SectionHead title="When it’s ready"/><div className="hm-cue-grid-v5 hm-cue-grid-v6">{recipe.cues.map(x=><div key={x}>✓ {x}</div>)}</div></section><section className="hm-practical-grid-v5 hm-practical-grid-v6"><div><span>Portion + freeze</span><strong>{m.freezeFormat}</strong></div><div><span>Storage</span><p>{recipe.storage}</p></div><div><span>JB / Singapore</span><p>{recipe.local}</p></div><a href={recipe.sourceUrl} target="_blank" rel="noreferrer"><span>Reference</span><strong>{recipe.sourceLabel} ↗</strong></a></section></>}
  {mids.length>0&&<section className="hm-block-v5"><SectionHead title={`Build from ${m.code}`}/><div className="hm-mid-quick-v5">{mids.map(x=>{const n=recipes.filter(r=>r.midIds.includes(x.id)).length;return <Link href={`/prep/mids/${x.id}`} key={x.id} style={{"--tone":x.tone} as React.CSSProperties}><i/><div><strong>{x.code}</strong><span>{x.name}</span><small>{n?`${n} saved ${n===1?"recipe":"recipes"}`:"idea to try"}</small></div></Link>})}</div></section>}
  <section className="hm-block-v5"><SectionHead title={linked.length?`${linked.length} dinners from ${m.code}`:`What ${m.code} can become`}/>{linked.length?<div className="hm-meal-rail-v5">{linked.map(r=><MealCard recipe={r} key={r.id} compact/>)}</div>:<div className="hm-base-directions-v5"><strong>Good next directions</strong><div tabIndex={0} aria-label={`Possible ${m.code} dinner directions`}>{m.examples.slice(0,6).map(x=><span key={x}>{x}</span>)}</div><small>Ideas this mother base supports; we have not saved a dinner here yet.</small></div>}</section>
  {confirm&&<div className="hm-sheet-backdrop-v5" onMouseDown={e=>{if(e.target===e.currentTarget)setConfirm(false)}}><section className="hm-sheet-v5" role="dialog" aria-modal="true" aria-label={`Add ${m.code} batch`}><div className="hm-sheet-handle-v5"/><header><div><span>{short?"FOR THIS WEEK":"ADD A BATCH"}</span><h2>{m.code}</h2></div><button className="hm-icon-button-v5" onClick={()=>setConfirm(false)} aria-label="Close">×</button></header><p>One batch adds <strong>{batchMl} ml</strong> to the freezer ({m.batchYield} × {m.portionMl} ml).{short?` This week is ${short.shortMl} ml short.`:""}</p><p className="hm-sheet-note-v5">When you confirm this batch, Home records today as the made date so FIFO stays real.</p><button className="hm-primary-button-v5" onClick={finishBatch}>Batch finished</button></section></div>}
 </div>}
