"use client";
import Link from "next/link";
import {useMemo,useState,type CSSProperties} from "react";
import {useHousehold} from "../HouseholdState";
import {motherProcessImages} from "@/data/mother-process-assets";
import {getComponent,motherBases} from "@/data/home-data";
import {allLiveRecipesV7 as recipes} from "@/data/recipe-catalog-v7";
import {canonicalPrepComponentsV2,getCanonicalPrepV2} from "@/data/food-truth-v2";
import {prepForRecipeAtCookScaleV7} from "@/data/food-engine-v7";
import {quantity} from "@/data/food-quantity";
import {containerGuidanceV6,getHouseholdPrepFormulationV6,getPrepPortionPolicyV6,packetBreakdownV6} from "@/data/prep-portioning-v6";
import {getPrepStorageV2} from "@/data/prep-storage-v2";
import {prepDemandForWeekV7,stockPortionsV7} from "@/data/stock-math-v7";
import {feedback} from "@/lib/feedback";
import {motherHero,toneFor,toneGradient} from "@/lib/tones";
import {HomeSays} from "./HomeSays";
import {formatQty,MealTile,RoundBack,SectionHead,Sheet,Toast} from "./Primitives";
import {ComponentSheet} from "./StockSheets";

function descendantsOf(id:string){const out=new Set([id]);let changed=true;while(changed){changed=false;for(const c of canonicalPrepComponentsV2)if(c.madeFrom.some(p=>out.has(p))&&!out.has(c.id)){out.add(c.id);changed=true}}return out}
export function Mother({id}:{id:string}){
 const h=useHousehold(),m=motherBases.find(x=>x.id===id)!,truth=getCanonicalPrepV2(id),form=getHouseholdPrepFormulationV6(id),policy=getPrepPortionPolicyV6(id),storage=getPrepStorageV2(id);if(!truth||!form||!policy)throw new Error(`Missing canonical mother ${id}`);
 const process=motherProcessImages[id]??[],hero=motherHero(id),tone=toneFor(id),grad=toneGradient(id);
 const[confirm,setConfirm]=useState(false),[count,setCount]=useState(false),[toast,setToast]=useState(""),[made,setMade]=useState(""),[error,setError]=useState("");
 const qty=h.componentStock[id]??0,packets=stockPortionsV7(id,h.componentStock),short=h.prepNeeds.find(x=>x.id===id),weekDemand=prepDemandForWeekV7(h.week).find(x=>x.id===id);
 const children=canonicalPrepComponentsV2.filter(x=>x.tier==="mid"&&x.madeFrom.includes(id));
 const linked=useMemo(()=>{const family=descendantsOf(id);return recipes.filter(r=>prepForRecipeAtCookScaleV7(r.id).some(p=>family.has(p.componentId)))},[id]);
 const batches=h.prepBatches.filter(b=>b.componentId===id&&b.remaining.qty>0).sort((a,b)=>new Date(a.producedAt).getTime()-new Date(b.producedAt).getTime()),oldest=batches[0];
 const suggestedPackets=short?Math.max(1,Math.ceil(short.shortQty/policy.packet.qty)):Math.max(policy.targetRotation[0],Math.ceil((weekDemand?.neededQty??0)/policy.packet.qty));
 const finishBatch=()=>{const measured=Number(made);if(!(measured>0))return;try{const output=quantity(measured,policy.packet.unit),split=packetBreakdownV6(id,output);h.recordMeasuredProduction(id,output,"portion-v6");setMade("");setError("");setConfirm(false);feedback("success");const rem=split.remainder.qty>0?` + ${formatQty(split.remainder.qty,split.remainder.unit)} remainder`:"";setToast(`${m.code} · ${split.fullPackets} full ${split.fullPackets===1?"packet":"packets"}${rem}`);window.setTimeout(()=>setToast(""),2200)}catch(e){setError(e instanceof Error?e.message:"Couldn’t log the measured batch.")}};
 const says=(()=>{if(!h.kitchenReady)return{text:<>Count {m.code} in the freezer once and I’ll tell you when this week is short.</>,actions:<button className="primary" onClick={()=>setCount(true)}>Count {m.code}</button>};if(short){const n=Math.ceil(short.shortQty/policy.packet.qty);return{text:<>This week is <b>{formatQty(short.shortQty,short.unit)} short</b> of {m.code}, about {n} stored {n===1?"packet":"packets"}. Make one sensible household batch, measure the finished output, then portion it.</>,actions:<><button className="primary" onClick={()=>setConfirm(true)}>Make {m.code}</button><Link className="ghost" href="/prep/day">Prep Day</Link></>}};if(oldest)return{text:<><b>{m.code}</b> has about {packets} full {packets===1?"packet":"packets"} recorded plus any labelled remainder. Oldest batch is from {new Date(oldest.producedAt).toLocaleDateString(undefined,{day:"numeric",month:"short"})}; use it first.</>};return{text:<>{packets} full {packets===1?"packet":"packets"} recorded{weekDemand?` and this week needs ${formatQty(weekDemand.neededQty,weekDemand.unit)}`:""}. {linked.length?`${linked.length} of our dinners start here or through a child prep.`:"Nothing saved uses it yet."}</>}})();
 return <div className="hm-screen flush" style={{"--tone":tone,"--tone-grad":grad} as CSSProperties}>
  {hero?<div className="hm-hero md"><img src={hero} alt={m.name} loading="eager" fetchPriority="high"/><div className="shade"/><div className="top"><RoundBack href="/prep" onPhoto label="Back to prep"/></div></div>:<div className="hm-hero-grad" style={{"--tone-light":`${tone}aa`,"--tone-deep":tone} as CSSProperties}><div className="glow"/><div className="top"><RoundBack href="/prep" onPhoto label="Back to prep"/></div><div className="code"><span className="kick">MOTHER BASE</span><b>{m.code}</b></div></div>}
  <div className="hm-sheetpage peach" style={{paddingBottom:80}}>
   <div style={{display:"flex",alignItems:"center",gap:8}}><span className="hm-code-badge">{m.code}</span><span className="hm-note">storage packet = {formatQty(policy.packet.qty,policy.packet.unit)} · {h.kitchenReady?`${packets} full left`:"not counted"}</span></div>
   <h1 className="hm-h1-lg" style={{marginTop:10}}>{m.name}</h1><p className="hm-lead" style={{marginTop:8}}>{m.purpose}</p>
   <div className="hm-detail-actions"><button className="hm-btn tone" onClick={()=>setConfirm(true)}>Make {m.code}</button><button className="hm-btn ghost icon" aria-label={`Count ${m.code}`} onClick={()=>setCount(true)}>＋</button></div>
   <HomeSays actions={says.actions}>{says.text}</HomeSays>
   {process.length>0&&<><SectionHead title="How it should look" action={<span className="muted">swipe · {process.length} stages</span>}/><div className="hm-process">{process.map((p,i)=><article key={p.url}><img src={p.url} alt={`${m.name}: ${p.stage.replace(/^\d+\s*·\s*/,"").toLowerCase()}`} loading={i<2?"eager":"lazy"}/><div className="copy"><div className="stage">{p.stage}</div><p>{p.caption}</p></div></article>)}</div></>}
   <SectionHead title="What goes in" action={<span className="muted">household batch · measure after cooking</span>}/><div className="hm-chiplist">{form.ingredientInputs.map((x,i)=><span key={`${x.ingredientId}-${i}`}>{x.name} · {formatQty(x.qty,x.unit)}{x.optional?" · optional":""}</span>)}</div>
   <SectionHead title="Cook it" action={<span className="muted">{form.method.length} steps</span>}/><div className="hm-steps" style={{marginTop:14}}>{form.method.map((step,i)=><div key={i} className="hm-card hm-step" style={{"--phase":grad} as CSSProperties}><b>{i+1}</b><div><p>{step.instruction}</p>{step.cue&&<small>{step.cue}</small>}</div><span/></div>)}</div>
   <SectionHead title="When it’s ready" action={<Link href={`/scan?mode=Prep&back=${encodeURIComponent(`/prep/${id}`)}`}>Show the pan</Link>}/><div className="hm-cues">{form.method.filter(x=>x.cue).map((x,i)=><div key={i} className="hm-card"><b>✓</b>{x.cue}</div>)}</div>
   {h.kitchenReady&&(batches.length>0||qty>0)&&<><SectionHead title="In the freezer" action={<span className="muted">oldest first · exact stock underneath</span>}/><div className="hm-card hm-batches-card">{batches.slice(0,4).map((b,i)=>{const left=packetBreakdownV6(id,b.remaining),madeN=packetBreakdownV6(id,b.initial);return <div key={b.batchId} className="row"><b className={`n ${i===0?"first":""}`}>{i+1}</b><span><strong>{left.fullPackets} full {left.fullPackets===1?"packet":"packets"}{left.remainder.qty?` + ${formatQty(left.remainder.qty,left.remainder.unit)} remainder`:""}{i===0?" · use first":""}</strong><small>Made {new Date(b.producedAt).toLocaleDateString(undefined,{day:"numeric",month:"short"})} · measured {formatQty(b.initial.qty,b.initial.unit)} · {madeN.fullPackets} full packets</small></span></div>})}</div></>}
   {children.length>0&&<><SectionHead title={`Build from ${m.code}`} action={<Link href="/prep/mids">Explore ›</Link>}/><div className="hm-chiplist">{children.map(x=>{const c=getComponent(x.id),n=recipes.filter(r=>prepForRecipeAtCookScaleV7(r.id).some(p=>p.componentId===x.id)).length;return c?<Link key={x.id} href={`/prep/mids/${x.id}`} className="tinted" style={{"--tone":toneFor(x.id)} as CSSProperties}><i/>{x.code}<small>{n?`${n} ${n===1?"dinner":"dinners"}`:x.name}</small></Link>:null})}</div></>}
   <SectionHead title="Becomes" action={<span style={{color:tone,fontWeight:700,fontSize:13}}>{linked.length} dinners</span>}/>{linked.length?<div className="hm-rail">{linked.map(r=><MealTile key={r.id} recipe={r}/>)}</div>:<div className="hm-chiplist">{m.examples.map(x=><span key={x}>{x}</span>)}</div>}
   <div className="hm-card hm-refs"><p><b>Portioning · </b>{containerGuidanceV6(id)}</p>{storage?.note&&<p><b>Storage · </b>{storage.note}</p>}{form.evidence.map(e=><a key={e.url} href={e.url} target="_blank" rel="noreferrer">{e.label} ↗</a>)}</div>
  </div>
  <Sheet open={confirm} onClose={()=>{setConfirm(false);setError("")}} label={`Make ${m.code}`} title={`Make ${m.code}`} action={<span className="muted">measure finished output</span>}><HomeSays className="tight">Cook the household batch shown here. After cooling as directed, weigh or measure the <b>actual finished output</b>. Home will convert that measurement into full storage packets plus a labelled remainder. No yield is guessed.</HomeSays><div className="hm-card" style={{marginTop:14,padding:14}}><strong>Storage packet · {formatQty(policy.packet.qty,policy.packet.unit)}</strong><small style={{display:"block"}}>{containerGuidanceV6(id)} Target rotation is usually {policy.targetRotation[0]}–{policy.targetRotation[1]} packets; this week currently points to about {suggestedPackets}.</small></div><label style={{display:"grid",gap:8,marginTop:18}}><span className="hm-note">Actual finished output ({policy.packet.unit})</span><input inputMode="decimal" value={made} onChange={e=>setMade(e.target.value)} placeholder={`e.g. ${Math.round(policy.packet.qty*policy.targetRotation[0])}`} aria-label={`Measured finished ${policy.packet.unit} of ${m.code}`}/></label>{error&&<p role="alert" style={{color:"var(--peach-text)",fontWeight:700,marginTop:10}}>{error}</p>}<div className="hm-sheet-actions"><button className="hm-btn ghost" onClick={()=>setConfirm(false)}>Not yet</button><button className="hm-btn primary" disabled={!(Number(made)>0)} onClick={finishBatch}>Measure & add to Kitchen</button></div></Sheet>
  <ComponentSheet id={count?id:null} onClose={()=>setCount(false)}/>{toast&&<Toast text={toast}/>} 
 </div>;
}
