"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import {useHousehold} from "../HouseholdState";
import {baseRecipesV2} from "@/data/base-recipes-v2";
import {midBases,motherBases,recipes} from "@/data/home-data";
import {batchOutputMl,prepDemandForWeekMl,stockPortions} from "@/data/stock-math";
import {feedback} from "@/lib/feedback";
import {useSheet} from "@/lib/useSheet";
import {Back,MealCard,SectionHead} from "./Primitives";

export function Mother({id}:{id:string}){
 const h=useHousehold();const m=motherBases.find(x=>x.id===id)!;const recipe=baseRecipesV2[id];const mids=midBases.filter(x=>x.parentMotherIds.includes(id));const[confirm,setConfirm]=useState(false);useSheet(confirm,()=>setConfirm(false));const ml=h.componentStock[id]??0;const portions=stockPortions(id,h.componentStock);const batchMl=batchOutputMl(id);
 const weekDemand=prepDemandForWeekMl(h.week).find(x=>x.id===id);const short=h.prepNeeds.find(x=>x.id===id);const neededMl=weekDemand?.neededMl??0;
 const linked=useMemo(()=>{const viaMid=new Set(mids.map(x=>x.id));const all=recipes.filter(r=>r.motherIds.includes(id)||r.midIds.some(mid=>viaMid.has(mid)));return [...new Map(all.map(r=>[r.id,r])).values()]},[id,mids]);
 return <div className="hm-page-v5 hm-mother-v5"><Back href="/prep" label="Prep"/><header className="hm-mother-head-v5" style={{"--tone":m.tone} as React.CSSProperties}><div className="hm-base-cube-v5 big"><i/><b>{m.code}</b></div><div><span>{short?"THIS WEEK":"MOTHER BASE"}</span><h1>{m.name}</h1><p>{m.purpose}</p></div></header>
  <section className="hm-stock-action-v5"><div><span>{short?"This week":"In the freezer"}</span><strong>{!h.kitchenReady?"Not checked":short?`${short.shortMl} ml short`:`${ml} ml`}</strong><small>{!h.kitchenReady?`Standard portion: ${m.portionMl} ml`:short?`Have ${ml} ml · need ${neededMl} ml`:neededMl?`Enough for this week · ${portions} standard ${portions===1?"portion":"portions"}`:`${portions} standard ${portions===1?"portion":"portions"}`}</small></div><button onClick={()=>setConfirm(true)}>{short?"Make for this week":"Make batch"}</button></section>
  {recipe&&<><section className="hm-block-v5 hm-batch-recipe-v5"><SectionHead eyebrow="BATCH RECIPE" title="What goes in"/><ul>{recipe.ingredients.map(x=><li key={x}>{x}</li>)}</ul></section><section className="hm-block-v5"><SectionHead eyebrow="METHOD" title="Cook it"/><ol className="hm-step-list-v5">{recipe.method.map((x,i)=><li key={x}><b>{i+1}</b><p>{x}</p></li>)}</ol></section><section className="hm-block-v5"><SectionHead eyebrow="LOOK FOR" title="When it’s ready"/><div className="hm-cue-grid-v5">{recipe.cues.map(x=><div key={x}>✓ {x}</div>)}</div></section><section className="hm-practical-grid-v5"><div><span>Freeze</span><strong>{m.freezeFormat}</strong></div><div><span>JB / Singapore</span><p>{recipe.local}</p></div><a href={recipe.sourceUrl} target="_blank" rel="noreferrer"><span>Reference</span><strong>{recipe.sourceLabel} ↗</strong></a></section></>}
  {mids.length>0&&<section className="hm-block-v5"><SectionHead eyebrow="MIDS" title={`Build from ${m.code}`}/><div className="hm-mid-quick-v5">{mids.map(x=>{const n=recipes.filter(r=>r.midIds.includes(x.id)).length;return <Link href={`/prep/mids/${x.id}`} key={x.id} style={{"--tone":x.tone} as React.CSSProperties}><i/><div><strong>{x.code}</strong><span>{x.name}</span><small>{n?`${n} saved ${n===1?"recipe":"recipes"}`:"research"}</small></div></Link>})}</div></section>}
  <section className="hm-block-v5"><SectionHead eyebrow="DINNERS" title={linked.length?`${linked.length} saved with ${m.code}`:`What ${m.code} can become`}/>{linked.length?<div className="hm-meal-rail-v5">{linked.map(r=><MealCard recipe={r} key={r.id} compact/>)}</div>:<div className="hm-base-directions-v5"><strong>Good next directions</strong><div tabIndex={0} aria-label={`Possible ${m.code} dinner directions`}>{m.examples.slice(0,6).map(x=><span key={x}>{x}</span>)}</div><small>Ideas this mother base supports; we have not saved a dinner here yet.</small></div>}</section>
  {confirm&&<div className="hm-sheet-backdrop-v5" onMouseDown={e=>{if(e.target===e.currentTarget)setConfirm(false)}}><section className="hm-sheet-v5" role="dialog" aria-modal="true" aria-label={`Add ${m.code} batch`}><div className="hm-sheet-handle-v5"/><header><div><span>{short?"FOR THIS WEEK":"ADD A BATCH"}</span><h2>{m.code}</h2></div><button className="hm-icon-button-v5" onClick={()=>setConfirm(false)} aria-label="Close">×</button></header><p>One batch adds <strong>{batchMl} ml</strong> to the freezer ({m.batchYield} × {m.portionMl} ml).{short?` This week is ${short.shortMl} ml short.`:""}</p><button className="hm-primary-button-v5" onClick={()=>{h.makeBatch(id);setConfirm(false);feedback("success")}}>Batch finished</button></section></div>}
 </div>}
