"use client";
import Link from "next/link";
import {useMemo,useState,type CSSProperties} from "react";
import {getComponent,getIngredient,getRecipe,recipes} from "@/data/home-data";
import {ingredientsForRecipeV2} from "@/data/ingredient-engine-v2";
import {getCanonicalIngredientV2} from "@/data/ingredient-catalog-v2";
import {recipePrepV2} from "@/data/food-truth-v2";
import {missingActivePrepForRecipeV2,recipeSupportedByActivePrepV2} from "@/data/prep-repertoire-v2";
import {mealHistorySummaryV2,recentPenaltyV2} from "@/data/meal-history-v2";
import {recipeTitle} from "@/data/recipe-display";
import {recipeAvailability} from "@/data/stock-math";
import {useHousehold} from "../HouseholdState";
import {useHouseholdV12} from "../HouseholdStateV12";
import {feedback} from "@/lib/feedback";
import {toneFor} from "@/lib/tones";
import {HomeSays} from "./HomeSays";
import {Orb} from "./Orb";
import {Check,formatQty,mealMeta,MealTile,Progress,SectionHead,Sheet,Stat,Toast,useReadiness} from "./Primitives";

const days=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],longDays=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],poolFilters=["All","Favourites","Not lately","Quick","New"];
type RecipeRow=(typeof recipes)[number];
export function Plan(){
 const h=useHousehold(),v12=useHouseholdV12(),ready=useReadiness(),today=(new Date().getDay()+6)%7;
 const[day,setDay]=useState(today),[swap,setSwap]=useState<number|null>(null),[q,setQ]=useState(""),[poolOpen,setPoolOpen]=useState(false),[poolFilter,setPoolFilter]=useState("All"),[shopOpen,setShopOpen]=useState(false),[changed,setChanged]=useState<number|null>(null),[suggested,setSuggested]=useState<string[]|null>(null),[toast,setToast]=useState("");
 const history=useMemo(()=>mealHistorySummaryV2({history:h.history,favourites:h.favourites,ratings:h.ratings}),[h.history,h.favourites,h.ratings]);
 const useSoonIds=useMemo(()=>new Set(Object.keys(v12.state.useSoon).filter(id=>v12.state.useSoon[id])),[v12.state.useSoon]);
 const useSoonAge=(id:string)=>{const at=v12.state.useSoonAt[id];return at?Math.max(0,Math.floor((Date.now()-new Date(at).getTime())/86400000)):0};
 const usesSoon=(r:RecipeRow)=>ingredientsForRecipeV2(r.id).filter(x=>useSoonIds.has(x.ingredientId));
 const useSoonWeight=(r:RecipeRow)=>usesSoon(r).reduce((s,x)=>s+1+Math.min(useSoonAge(x.ingredientId),7)*.18,0),inMonth=(id:string)=>h.monthlyPool.includes(id);
 const stockGap=(r:RecipeRow)=>{if(!h.kitchenReady)return 0;const a=recipeAvailability(r.id,h.componentStock,h.ingredientStock);return a.missingPrep.length+a.missingIngredients.length};
 const activeGap=(r:RecipeRow)=>h.activePrepIds.length?missingActivePrepForRecipeV2(r.id,h.activePrepIds).length:0;
 const daysSinceCooked=(id:string)=>history.recipes[id]?.daysSince??9999;
 const rank=(a:RecipeRow,b:RecipeRow)=>activeGap(a)-activeGap(b)||useSoonWeight(b)-useSoonWeight(a)||stockGap(a)-stockGap(b)||recentPenaltyV2(a.id,h.history)-recentPenaltyV2(b.id,h.history)||Number(inMonth(b.id))-Number(inMonth(a.id))||Number(!!h.favourites[b.id])-Number(!!h.favourites[a.id])||Math.max(h.ratings[b.id]?.josh??0,h.ratings[b.id]?.g??0)-Math.max(h.ratings[a.id]?.josh??0,h.ratings[a.id]?.g??0)||a.minutes-b.minutes;
 const swapResults=recipes.filter(r=>!q||`${recipeTitle(r.id,r.title)} ${r.cuisine}`.toLowerCase().includes(q.toLowerCase())).sort(rank),planned=getRecipe(h.week[day]),plannedReady=ready(planned);
 const reuse=useMemo(()=>{const m=new Map<string,{count:number;days:number[]}>();h.week.forEach((id,di)=>{const seen=new Set<string>();recipePrepV2(id).forEach(p=>{if(seen.has(p.componentId))return;seen.add(p.componentId);const cur=m.get(p.componentId)??{count:0,days:[]};cur.count++;cur.days.push(di);m.set(p.componentId,cur)})});return[...m.entries()].map(([id,v])=>({id,...v,component:getComponent(id)!})).filter(x=>x.component).sort((a,b)=>b.count-a.count).slice(0,5)},[h.week]);
 const required=useMemo(()=>new Set(h.week.flatMap(id=>ingredientsForRecipeV2(id).filter(x=>!x.optional&&x.ingredientId!=="water").map(x=>x.ingredientId))).size,[h.week]);
 const prepLine=h.prepNeeds.slice(0,3).map(x=>{const c=getComponent(x.id);return c?`${c.code} ${formatQty(x.shortQty,x.unit)}`:null}).filter(Boolean).join(" · ");
 const nameForNeed=(x:typeof h.shoppingNeeds[number])=>getCanonicalIngredientV2(x.canonicalId)?.name??getIngredient(x.id)?.name??x.id;
 const buyNames=h.shoppingNeeds.slice(0,3).map(x=>nameForNeed(x).toLowerCase()).join(", "),checked=h.shoppingNeeds.filter(x=>h.groceryChecked[x.id]),shopPct=h.shoppingNeeds.length?Math.round(checked.length/h.shoppingNeeds.length*100):100;
 const activeFitCount=h.week.filter(id=>!h.activePrepIds.length||recipeSupportedByActivePrepV2(id,h.activePrepIds)).length;
 const flash=(t:string)=>{setToast(t);window.setTimeout(()=>setToast(""),1600)},chooseSwap=(r:RecipeRow)=>{if(swap===null)return;const i=swap;h.setDay(i,r.id);setSwap(null);setDay(i);setChanged(i);window.setTimeout(()=>setChanged(v=>v===i?null:v),600);feedback("change");flash(`${days[i]} · ${recipeTitle(r.id,r.title)}`)};
 const finishShopping=()=>{for(const item of checked){const cur=h.ingredientStock[item.id]??0;h.setIngredient(item.id,item.unit==="have"?Math.max(cur,2):cur+item.qty);h.toggleGrocery(item.id)}setShopOpen(false);feedback("success");flash(`${checked.length} added to Kitchen`)};
 const buildWeek=()=>{
  const month=recipes.filter(r=>inMonth(r.id)),pool=month.length>=7?month:recipes,picked:RecipeRow[]=[],reused=new Set<string>(),cuisineCounts=new Map<string,number>();
  for(let di=0;di<7;di++){
   const previous=picked.at(-1),ranked=pool.filter(r=>!picked.some(x=>x.id===r.id)).map(r=>{
    const a=h.kitchenReady?recipeAvailability(r.id,h.componentStock,h.ingredientStock):null,gap=a?a.missingPrep.length+a.missingIngredients.length:0,rating=Math.max(h.ratings[r.id]?.josh??0,h.ratings[r.id]?.g??0),overlap=recipePrepV2(r.id).filter(p=>reused.has(p.componentId)).length,weekday=di<5,timeCost=weekday?Math.max(0,r.minutes-35)*.65:Math.max(0,25-r.minutes)*.18,sameCuisine=previous&&previous.cuisine===r.cuisine?10:0,cuisineRepeat=(cuisineCounts.get(r.cuisine)??0)*7,prepOutside=activeGap(r),recent=recentPenaltyV2(r.id,h.history);
    return{r,score:prepOutside*48+gap*20+recent-useSoonWeight(r)*24-Number(!!h.favourites[r.id])*8-rating*2-overlap*5+timeCost+sameCuisine+cuisineRepeat}
   }).sort((a,b)=>a.score-b.score||a.r.minutes-b.r.minutes),next=ranked[0]?.r;
   if(!next)break;picked.push(next);cuisineCounts.set(next.cuisine,(cuisineCounts.get(next.cuisine)??0)+1);recipePrepV2(next.id).forEach(p=>reused.add(p.componentId));
  }
  if(picked.length===7){setSuggested(picked.map(r=>r.id));feedback("success")}
 };
 const acceptWeek=()=>{if(!suggested||suggested.length!==7)return;suggested.forEach((id,i)=>h.setDay(i,id));setSuggested(null);feedback("success");flash("Week updated")},swapSuggested=(i:number)=>{if(!suggested)return;const next=[...recipes].sort(rank).find(r=>!suggested.includes(r.id));if(next)setSuggested(suggested.map((id,j)=>j===i?next.id:id))};
 const suggestedRecipes=(suggested??[]).map(id=>getRecipe(id)),suggestedReady=suggestedRecipes.filter(r=>h.kitchenReady&&recipeAvailability(r.id,h.componentStock,h.ingredientStock).ready).length,suggestedSoon=new Set(suggestedRecipes.flatMap(r=>usesSoon(r).map(x=>x.ingredientId))).size,suggestedPrepFit=suggestedRecipes.filter(r=>!h.activePrepIds.length||recipeSupportedByActivePrepV2(r.id,h.activePrepIds)).length,suggestedReuse=(()=>{const c=new Map<string,number>();suggestedRecipes.forEach(r=>recipePrepV2(r.id).forEach(p=>c.set(p.componentId,(c.get(p.componentId)??0)+1)));return[...c.entries()].filter(([,n])=>n>1).map(([id,n])=>`${getComponent(id)?.code} ×${n}`)[0]??"—"})();
 const poolCandidates=recipes.filter(r=>poolFilter==="Favourites"?!!h.favourites[r.id]:poolFilter==="Not lately"?daysSinceCooked(r.id)>=28:poolFilter==="Quick"?r.minutes<=25:poolFilter==="New"?history.recipes[r.id]?.neverCooked:true).sort((a,b)=>Number(inMonth(b.id))-Number(inMonth(a.id))||recipeTitle(a.id,a.title).localeCompare(recipeTitle(b.id,b.title))),monthRecipes=h.monthlyPool.map(id=>getRecipe(id)).filter(Boolean);
 const says=(()=>{if(!h.kitchenReady)return{text:<>Pick the seven dinners first. Once Kitchen is confirmed, the list and prep become real.</>,actions:<Link className="primary" href="/kitchen">Set Kitchen truth</Link>};if(h.activePrepIds.length&&activeFitCount<7)return{text:<><b>{activeFitCount}/7</b> dinners fit your active prep repertoire. Build it for us will favour your active prep and avoid recent repeats before asking you to add anything new.</>,actions:<button className="primary" onClick={buildWeek}>Rebuild around our prep</button>};const top=reuse.find(x=>x.count>1),soonId=[...useSoonIds][0],uncovered=soonId&&!h.week.some(rid=>ingredientsForRecipeV2(rid).some(x=>x.ingredientId===soonId));if(uncovered){const name=getCanonicalIngredientV2(soonId)?.name??soonId,free=[0,1,2,3,4,5,6].find(i=>i>=today&&!usesSoon(getRecipe(h.week[i])).length)??today;return{text:<><b>{name}</b> is marked use soon and nothing this week uses it. Swap {longDays[free]}?</>,actions:<button className="primary" onClick={()=>setSwap(free)}>Swap {days[free]}</button>}}if(top)return{text:<>{top.count} dinners reuse <b>{top.component.code}</b>. Home also penalises recent repeats and too much of the same cuisine.</>};if(h.shoppingNeeds.length)return{text:<>{h.shoppingNeeds.length} things to buy — {buyNames}. Shop mode uses exact shortfalls where Home knows quantities.</>,actions:<button className="primary" onClick={()=>setShopOpen(true)}>Shop mode</button>};return{text:<>Recorded Kitchen truth covers this week. Nothing to buy.</>}})();
 return <div className="hm-screen"><div className="hm-plan-head"><h1 className="hm-h1">This week</h1><button className="hm-build" onClick={buildWeek}>Build it for us<Orb size={30}/></button></div><div className="hm-week" aria-label="This week's dinners">{h.week.map((id,i)=>{const r=getRecipe(id);return<button key={`${id}-${i}`} className={`${i===day?"on":""} ${changed===i?"changed":""}`} aria-pressed={i===day} onClick={()=>setDay(i)}><span>{days[i]}</span><div className="tile">{r.image&&<img src={r.image} alt=""/>}</div></button>})}</div><div className="hm-plan-hero">{planned.image&&<img key={planned.id} src={planned.image} alt={recipeTitle(planned.id,planned.title)}/>}<div className="shade"/><div className="copy"><span className="kick">{longDays[day].toUpperCase()}{day===today?" · TONIGHT":""}</span><h2>{recipeTitle(planned.id,planned.title)}</h2><div className="acts"><button className="swap" onClick={()=>{setSwap(day);setQ("")}}>Swap ⇄</button><span className="meta">{mealMeta(planned)}</span>{h.kitchenReady&&<span className="hm-pill onphoto" style={plannedReady.state==="missing"?{background:"rgba(255,138,92,.5)"}:undefined}>{plannedReady.label}</span>}</div></div></div><div className="hm-plan-tiles"><div className="hm-plan-tile"><span className="kick">TO BUY</span><b>{h.kitchenReady?h.shoppingNeeds.length:"—"}</b><p>{h.kitchenReady?(buyNames||"we have it all"):"set Kitchen truth first"}</p><button className="hm-btn primary" disabled={!h.shoppingNeeds.length} onClick={()=>setShopOpen(true)}>Shop mode</button></div><div className="hm-plan-tile peach"><span className="kick">TO PREP</span><b>{h.kitchenReady?h.prepNeeds.length:"—"}</b><p>{h.kitchenReady?(prepLine||"freezer covers it"):"set Kitchen truth first"}</p><Link className="hm-btn peach" href={h.prepNeeds.length?"/prep/day":"/prep"}>{h.prepNeeds.length?"Prep Day":"Prep"}</Link></div></div><HomeSays actions={says.actions}>{says.text}</HomeSays>
 {h.activePrepIds.length>0&&<div className="hm-card" style={{marginTop:14,padding:14}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"}}><span><strong>{activeFitCount}/7 fit your active prep</strong><small style={{display:"block"}}>Home can still suggest an extra prep when the payoff is worth it.</small></span><Link href="/prep" className="hm-pill">Edit prep</Link></div></div>}
 {reuse.length>0&&<><SectionHead title="Shared prep" action={<span className="muted">used across the week</span>}/><div className="hm-card lg hm-reuse" style={{marginTop:14}}><div className="days">{h.week.map((id,i)=>{const r=getRecipe(id);return<div key={`${id}-${i}`}><span>{days[i]}</span>{r.image?<img src={r.image} alt=""/>:<div className="ph"/>}</div>})}</div><div className="rows">{reuse.map(x=><div key={x.id} style={{"--tone":toneFor(x.id)} as CSSProperties}><span className="code"><i/>{x.component.code}</span><span className="cells">{days.map((_,di)=><i key={di} className={x.days.includes(di)?"on":""}/>)}</span><b className={`n ${x.count>1?"multi":""}`}>{x.count}</b></div>)}</div></div></>}
 <SectionHead title="Where the list comes from"/><div className="hm-gap"><div><b>{required}</b><small>week ingredients</small></div><span>−</span><div className="sky"><b>{h.kitchenReady?Math.max(0,required-h.shoppingNeeds.length):"—"}</b><small>covered</small></div><span>=</span><div className="peach"><b>{h.kitchenReady?h.shoppingNeeds.length:"—"}</b><small>to buy</small></div></div>
 <SectionHead title="This month" action={<button onClick={()=>setPoolOpen(true)}>Edit pool</button>}/><div className="hm-rail">{monthRecipes.slice(0,10).map(r=><MealTile key={r.id} recipe={r}/>)}</div>
 <Sheet open={swap!==null} onClose={()=>setSwap(null)} label={swap!==null?`Swap ${longDays[swap]}`:"Swap dinner"} title="What instead?" action={<span className="muted">prep · recency · readiness</span>}><label className="hm-search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search dinners"/></label><div className="hm-list tight" style={{marginTop:12}}>{swapResults.slice(0,16).map(r=>{const a=ready(r),outside=activeGap(r);return<button key={r.id} className="hm-card hm-row" onClick={()=>chooseSwap(r)}>{r.image?<img className="thumb" src={r.image} alt=""/>:<span className="thumb"/>}<span><strong>{recipeTitle(r.id,r.title)}</strong><small>{a.label} · {r.cuisine} · {daysSinceCooked(r.id)===9999?"never cooked":`${daysSinceCooked(r.id)}d ago`}{outside?` · +${outside} prep`:" · active prep"}</small></span></button>})}</div></Sheet>
 <Sheet open={!!suggested} onClose={()=>setSuggested(null)} label="Suggested week" title="Built around your kitchen" action={<span className="muted">you still decide</span>}>{suggested&&<><div className="hm-stats"><Stat v={suggestedPrepFit} k="fit active prep"/><Stat v={suggestedSoon} k="use-soon foods" tint="var(--tint-peach)"/><Stat v={suggestedReuse} k="best reuse" tint="var(--tint-sky)"/></div><div className="hm-list tight" style={{marginTop:14}}>{suggested.map((id,i)=>{const r=getRecipe(id),hx=history.recipes[id];return<div key={`${id}-${i}`} className="hm-card hm-row"><span className="hm-pill">{days[i]}</span><span><strong>{recipeTitle(r.id,r.title)}</strong><small>{r.cuisine} · {hx.neverCooked?"never cooked":`${hx.daysSince}d since last`} · {recipeSupportedByActivePrepV2(r.id,h.activePrepIds)||!h.activePrepIds.length?"active prep":"needs extra prep"}</small></span><button onClick={()=>swapSuggested(i)}>⇄</button></div>})}</div><button className="hm-btn primary full" style={{marginTop:18}} onClick={acceptWeek}>Use this week</button></>}</Sheet>
 <Sheet open={shopOpen} onClose={()=>setShopOpen(false)} label="Shop mode" title="This week’s gaps" action={<span className="muted">exact where known</span>}><Progress pct={shopPct}/><div className="hm-list tight" style={{marginTop:14}}>{h.shoppingNeeds.map(item=>{const on=!!h.groceryChecked[item.id];return<button key={item.canonicalId} className={`hm-checkrow ${on?"done":""}`} onClick={()=>h.toggleGrocery(item.id)}><Check on={on}/><span className="name">{nameForNeed(item)}</span><small>{item.unit==="have"?"restock":formatQty(item.qty,item.unit)}</small></button>})}</div><button className="hm-btn primary full" style={{marginTop:18}} disabled={!checked.length} onClick={finishShopping}>Add checked to Kitchen</button></Sheet>
 <Sheet open={poolOpen} onClose={()=>setPoolOpen(false)} label="Monthly pool" title="What’s in rotation"><div className="hm-chips" style={{marginBottom:14}}>{poolFilters.map(f=><button key={f} className={`hm-chip ${poolFilter===f?"on":""}`} onClick={()=>setPoolFilter(f)}>{f}</button>)}</div><div className="hm-list tight">{poolCandidates.map(r=>{const on=inMonth(r.id);return<button key={r.id} className={`hm-card hm-row ${on?"selected":""}`} onClick={()=>h.toggleMonthlyPool(r.id)}>{r.image?<img className="thumb" src={r.image} alt=""/>:<span className="thumb"/>}<span><strong>{recipeTitle(r.id,r.title)}</strong><small>{r.cuisine} · {r.minutes} min · {history.recipes[r.id]?.neverCooked?"new":`${history.recipes[r.id]?.daysSince}d since last`}</small></span><Check on={on}/></button>})}</div></Sheet>{toast&&<Toast text={toast}/>}</div>;
}