"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import {getComponent,getIngredient,getRecipe,recipes} from "@/data/home-data";
import {recipeTitle} from "@/data/recipe-display";
import {prepDemandForWeekMl} from "@/data/stock-math";
import {useHousehold} from "../HouseholdState";
import {feedback} from "@/lib/feedback";
import {useSheet} from "@/lib/useSheet";
import {MealCard,PageHead,SectionHead} from "./Primitives";
import {GroceryGap,WeekReuse} from "./PlanVisuals";

const days=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
export function Plan(){
 const h=useHousehold();
 const[swap,setSwap]=useState<number|null>(null);const[q,setQ]=useState("");const[showGroceries,setShowGroceries]=useState(false);const[editPool,setEditPool]=useState(false);const[poolQ,setPoolQ]=useState("");
 useSheet(swap!==null,()=>setSwap(null));useSheet(editPool,()=>setEditPool(false));
 const useSoonIds=useMemo(()=>new Set(Object.keys(h.useSoon).filter(id=>h.useSoon[id]&&(h.ingredientStock[id]??0)>0)),[h.useSoon,h.ingredientStock]);
 const demand=prepDemandForWeekMl(h.week);const prepList=h.kitchenReady?h.prepNeeds:demand.map(x=>({id:x.id,shortMl:x.neededMl,batches:0}));
 const usesSoon=(r:(typeof recipes)[number])=>r.ingredients.filter(x=>useSoonIds.has(x.id)).length;
 const inMonth=(id:string)=>h.monthlyPool.includes(id);
 const swapResults=recipes.filter(r=>!q||`${recipeTitle(r.id,r.title)} ${r.title} ${r.cuisine}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>usesSoon(b)-usesSoon(a)||Number(inMonth(b.id))-Number(inMonth(a.id))||Number(!!h.favourites[b.id])-Number(!!h.favourites[a.id])||Math.max(h.ratings[b.id]?.josh??0,h.ratings[b.id]?.g??0)-Math.max(h.ratings[a.id]?.josh??0,h.ratings[a.id]?.g??0)||a.minutes-b.minutes);
 const poolCandidates=recipes.filter(r=>!poolQ||`${recipeTitle(r.id,r.title)} ${r.cuisine}`.toLowerCase().includes(poolQ.toLowerCase())).sort((a,b)=>Number(inMonth(b.id))-Number(inMonth(a.id))||Number(!!h.favourites[b.id])-Number(!!h.favourites[a.id])||a.title.localeCompare(b.title));
 const groceryList=showGroceries?h.shoppingNeeds:h.shoppingNeeds.slice(0,12);const useSoonList=[...useSoonIds].map(id=>getIngredient(id)).filter(Boolean);const monthRecipes=h.monthlyPool.map(id=>getRecipe(id)).filter(Boolean);
 return <div className="hm-page-v5 hm-plan-v5"><PageHead eyebrow="PLAN" title="This week" sub="Pick the dinners. The rest follows."/>
  <div className="hm-week-strip-v5">{h.week.map((id,i)=>{const r=getRecipe(id);const soon=usesSoon(r);return <button key={`${id}-${i}`} onClick={()=>{setSwap(i);setQ("");feedback("tap")}}>{r.image?<img src={r.image} alt=""/>:<div/>}<span>{days[i]}</span><strong>{recipeTitle(r.id,r.title)}</strong><small>{r.minutes} min{soon?` · uses ${soon} soon`:""}</small></button>})}</div>
  {useSoonList.length>0&&<section className="hm-use-soon-strip-v5"><div><span>USE SOON</span><strong>{useSoonList.length===1?"One thing to finish":"Finish these first"}</strong></div><div>{useSoonList.slice(0,6).map(i=><button key={i!.id} onClick={()=>{h.toggleUseSoon(i!.id);feedback("change")}}><span>{i!.name}</span><b>×</b></button>)}</div><Link href="/kitchen">Kitchen</Link></section>}
  <GroceryGap/>
  <section className="hm-block-v5"><SectionHead eyebrow="GROCERIES" title={h.kitchenReady?(h.shoppingNeeds.length?`${h.shoppingNeeds.length} things to buy`:"We have what we need"):"What the week uses"} action={<Link href="/kitchen">Kitchen</Link>}/>{h.shoppingNeeds.length?<><div className="hm-grocery-list-v5">{groceryList.map(x=>{const d=getIngredient(x.id);return <label key={x.id} className={h.groceryChecked[x.id]?"done":""}><input type="checkbox" checked={!!h.groceryChecked[x.id]} onChange={()=>{h.toggleGrocery(x.id);feedback("tap")}}/><span><strong>{d?.name}</strong><small>{x.unit==="have"?"check pantry":`${Math.round(x.qty*10)/10} ${x.unit}`}</small></span></label>})}</div>{h.shoppingNeeds.length>12&&<button className="hm-text-button-v5" onClick={()=>{setShowGroceries(v=>!v);feedback("tap")}}>{showGroceries?"Show less":`Show all ${h.shoppingNeeds.length}`}</button>}</>:<div className="hm-empty-v5">Nothing to buy for the current week.</div>}</section>
  <section className="hm-block-v5"><SectionHead eyebrow="PREP" title={h.kitchenReady?(h.prepNeeds.length?`${h.prepNeeds.length} things to top up`:"Freezer covered"):"Prep used this week"} action={<Link href="/prep">Prep</Link>}/>{prepList.length?<div className="hm-plan-prep-v5">{prepList.map(x=>{const c=getComponent(x.id);return c?<div key={x.id} style={{"--tone":c.tone} as React.CSSProperties}><i/><span><strong>{c.code}</strong><small>{x.shortMl} ml {h.kitchenReady?"short":"needed"}</small></span></div>:null})}</div>:<div className="hm-empty-v5">Nothing to prep for this week.</div>}</section>
  <WeekReuse/>
  <section className="hm-block-v5"><SectionHead eyebrow="THIS MONTH" title={`${monthRecipes.length} dinners in our pool`} action={<button onClick={()=>{setEditPool(true);setPoolQ("");feedback("tap")}}>Edit</button>}/>{monthRecipes.length?<div className="hm-meal-rail-v5">{monthRecipes.map(r=><MealCard recipe={r} key={r.id} compact/>)}</div>:<div className="hm-empty-v5">The pool is empty. Add a few dinners we actually want this month.</div>}</section>
  {swap!==null&&<div className="hm-sheet-backdrop-v5" onMouseDown={e=>{if(e.target===e.currentTarget)setSwap(null)}}><section className="hm-sheet-v5 hm-swap-sheet-v5" role="dialog" aria-modal="true" aria-label={`Swap ${days[swap]} dinner`}><div className="hm-sheet-handle-v5"/><header><div><span>{days[swap]}</span><h2>Swap dinner</h2></div><button className="hm-icon-button-v5" onClick={()=>setSwap(null)} aria-label="Close">×</button></header>{useSoonIds.size>0&&<p className="hm-swap-hint-v5">Meals using food marked “use soon” appear first. Then we favour this month’s pool.</p>}<label className="hm-search-v5"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Find a recipe" autoFocus/></label><div className="hm-swap-list-v5">{swapResults.slice(0,20).map(r=>{const soon=usesSoon(r);return <button key={r.id} onClick={()=>{h.setDay(swap,r.id);setSwap(null);feedback("change")}}>{r.image?<img src={r.image} alt=""/>:<div/>}<span><strong>{recipeTitle(r.id,r.title)}</strong><small>{r.minutes} min · {r.cuisine}{soon?` · uses ${soon} soon`:""}</small></span>{h.favourites[r.id]?<em>♥</em>:inMonth(r.id)?<em>This month</em>:(h.ratings[r.id]?.josh||h.ratings[r.id]?.g)?<em>{h.ratings[r.id]?.josh??"—"}★ · {h.ratings[r.id]?.g??"—"}★</em>:null}</button>})}</div></section></div>}
  {editPool&&<div className="hm-sheet-backdrop-v5" onMouseDown={e=>{if(e.target===e.currentTarget)setEditPool(false)}}><section className="hm-sheet-v5 hm-pool-sheet-v5" role="dialog" aria-modal="true" aria-label="Edit this month's meal pool"><div className="hm-sheet-handle-v5"/><header><div><span>THIS MONTH</span><h2>Edit our meal pool</h2></div><button className="hm-icon-button-v5" onClick={()=>setEditPool(false)} aria-label="Close">×</button></header><p className="hm-sheet-note-v5">Keep a useful mix of favourites, things we haven’t had lately, quick backups and a few meals worth trying.</p><label className="hm-search-v5"><span>⌕</span><input value={poolQ} onChange={e=>setPoolQ(e.target.value)} placeholder="Find a recipe" autoFocus/></label><div className="hm-pool-edit-list-v5">{poolCandidates.map(r=>{const active=inMonth(r.id);return <button key={r.id} className={active?"active":""} onClick={()=>{h.toggleMonthlyPool(r.id);feedback("change")}}>{r.image?<img src={r.image} alt=""/>:<div/>}<span><strong>{recipeTitle(r.id,r.title)}</strong><small>{r.minutes} min · {r.cuisine}{h.favourites[r.id]?" · favourite":""}</small></span><b>{active?"✓":"+"}</b></button>})}</div></section></div>}
 </div>}
