"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import {getComponent,getIngredient,getRecipe,recipes} from "@/data/home-data";
import {recipeTitle} from "@/data/recipe-display";
import {prepDemandForWeekMl} from "@/data/stock-math";
import {useHousehold} from "../HouseholdState";
import {feedback} from "@/lib/feedback";
import {MealCard,PageHead,SectionHead} from "./Primitives";
import {GroceryGap,WeekReuse} from "./PlanVisuals";

const days=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
const poolNames=["Favourites","Not lately","Quick","Weekend"] as const;type PoolName=typeof poolNames[number];
export function Plan(){const h=useHousehold();const[swap,setSwap]=useState<number|null>(null);const[q,setQ]=useState("");const[showGroceries,setShowGroceries]=useState(false);const[pool,setPool]=useState<PoolName>("Not lately");
 const useSoonIds=useMemo(()=>new Set(Object.keys(h.useSoon).filter(id=>h.useSoon[id]&&(h.ingredientStock[id]??0)>0)),[h.useSoon,h.ingredientStock]);
 const monthly=useMemo(()=>{const fav=recipes.filter(r=>h.favourites[r.id]||(h.ratings[r.id]?.josh??0)>=4||(h.ratings[r.id]?.g??0)>=4);const cooked=new Set(h.history.map(x=>x.mealId));return{"Favourites":fav,"Not lately":recipes.filter(r=>!cooked.has(r.id)).slice(0,12),"Quick":recipes.filter(r=>r.minutes<=25).slice(0,12),"Weekend":recipes.filter(r=>r.minutes>=40).slice(0,12)}},[h.favourites,h.ratings,h.history]);
 const demand=prepDemandForWeekMl(h.week);const prepList=h.kitchenReady?h.prepNeeds:demand.map(x=>({id:x.id,shortMl:x.neededMl,batches:0}));
 const usesSoon=(r:(typeof recipes)[number])=>r.ingredients.filter(x=>useSoonIds.has(x.id)).length;
 const swapResults=recipes.filter(r=>!q||`${recipeTitle(r.id,r.title)} ${r.title} ${r.cuisine}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>usesSoon(b)-usesSoon(a)||Number(!!h.favourites[b.id])-Number(!!h.favourites[a.id])||Math.max(h.ratings[b.id]?.josh??0,h.ratings[b.id]?.g??0)-Math.max(h.ratings[a.id]?.josh??0,h.ratings[a.id]?.g??0)||a.minutes-b.minutes);
 const groceryList=showGroceries?h.shoppingNeeds:h.shoppingNeeds.slice(0,12);const currentPool=monthly[pool];
 const useSoonList=[...useSoonIds].map(id=>getIngredient(id)).filter(Boolean);
 return <div className="hm-page-v5 hm-plan-v5"><PageHead eyebrow="PLAN" title="This week" sub="Pick the dinners. The rest follows."/>
  <div className="hm-week-strip-v5">{h.week.map((id,i)=>{const r=getRecipe(id);const soon=usesSoon(r);return <button key={`${id}-${i}`} onClick={()=>{setSwap(i);setQ("");feedback("tap")}}>{r.image?<img src={r.image} alt=""/>:<div/>}<span>{days[i]}</span><strong>{recipeTitle(r.id,r.title)}</strong><small>{r.minutes} min{soon?` · uses ${soon} soon`:""}</small></button>})}</div>
  {useSoonList.length>0&&<section className="hm-use-soon-strip-v5"><div><span>USE SOON</span><strong>{useSoonList.length===1?"One thing to finish":"Finish these first"}</strong></div><div>{useSoonList.slice(0,6).map(i=><button key={i!.id} onClick={()=>{h.toggleUseSoon(i!.id);feedback("change")}}><span>{i!.name}</span><b>×</b></button>)}</div><Link href="/kitchen">Kitchen</Link></section>}
  <GroceryGap/>
  <section className="hm-block-v5"><SectionHead eyebrow="GROCERIES" title={h.kitchenReady?(h.shoppingNeeds.length?`${h.shoppingNeeds.length} things to buy`:"We have what we need"):"What the week uses"} action={<Link href="/kitchen">Kitchen</Link>}/>{h.shoppingNeeds.length?<><div className="hm-grocery-list-v5">{groceryList.map(x=>{const d=getIngredient(x.id);return <label key={x.id} className={h.groceryChecked[x.id]?"done":""}><input type="checkbox" checked={!!h.groceryChecked[x.id]} onChange={()=>{h.toggleGrocery(x.id);feedback("tap")}}/><span><strong>{d?.name}</strong><small>{x.unit==="have"?"check pantry":`${Math.round(x.qty*10)/10} ${x.unit}`}</small></span></label>})}</div>{h.shoppingNeeds.length>12&&<button className="hm-text-button-v5" onClick={()=>{setShowGroceries(v=>!v);feedback("tap")}}>{showGroceries?"Show less":`Show all ${h.shoppingNeeds.length}`}</button>}</>:<div className="hm-empty-v5">Nothing to buy for the current week.</div>}</section>
  <section className="hm-block-v5"><SectionHead eyebrow="PREP" title={h.kitchenReady?(h.prepNeeds.length?`${h.prepNeeds.length} things to top up`:"Freezer covered"):"Prep used this week"} action={<Link href="/prep">Prep</Link>}/>{prepList.length?<div className="hm-plan-prep-v5">{prepList.map(x=>{const c=getComponent(x.id);return c?<div key={x.id} style={{"--tone":c.tone} as React.CSSProperties}><i/><span><strong>{c.code}</strong><small>{x.shortMl} ml {h.kitchenReady?"short":"needed"}</small></span></div>:null})}</div>:<div className="hm-empty-v5">Nothing to prep for this week.</div>}</section>
  <WeekReuse/>
  <section className="hm-block-v5"><SectionHead eyebrow="THIS MONTH" title="Meal pool"/><div className="hm-segment-v5 hm-pool-tabs-v5">{poolNames.map(name=><button key={name} className={pool===name?"active":""} onClick={()=>{setPool(name);feedback("tap")}}>{name}</button>)}</div>{currentPool.length?<div className="hm-meal-rail-v5">{currentPool.slice(0,10).map(r=><MealCard recipe={r} key={r.id} compact/>)}</div>:<div className="hm-empty-v5">Nothing here yet. Ratings and favourites will fill this up.</div>}</section>
  {swap!==null&&<div className="hm-sheet-backdrop-v5" onMouseDown={e=>{if(e.target===e.currentTarget)setSwap(null)}}><section className="hm-sheet-v5 hm-swap-sheet-v5"><div className="hm-sheet-handle-v5"/><header><div><span>{days[swap]}</span><h2>Swap dinner</h2></div><button className="hm-icon-button-v5" onClick={()=>setSwap(null)} aria-label="Close">×</button></header>{useSoonIds.size>0&&<p className="hm-swap-hint-v5">Meals using food marked “use soon” appear first.</p>}<label className="hm-search-v5"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Find a recipe" autoFocus/></label><div className="hm-swap-list-v5">{swapResults.slice(0,20).map(r=>{const soon=usesSoon(r);return <button key={r.id} onClick={()=>{h.setDay(swap,r.id);setSwap(null);feedback("change")}}>{r.image?<img src={r.image} alt=""/>:<div/>}<span><strong>{recipeTitle(r.id,r.title)}</strong><small>{r.minutes} min · {r.cuisine}{soon?` · uses ${soon} soon`:""}</small></span>{h.favourites[r.id]?<em>♥</em>:(h.ratings[r.id]?.josh||h.ratings[r.id]?.g)?<em>{h.ratings[r.id]?.josh??"—"}★ · {h.ratings[r.id]?.g??"—"}★</em>:null}</button>})}</div></section></div>}
 </div>}
