"use client";
import Link from "next/link";
import {useMemo,useState,type CSSProperties} from "react";
import {useHousehold} from "../HouseholdState";
import {getComponent,recipes} from "@/data/home-data";
import {canonicalPrepComponentsV2,recipePrepV2} from "@/data/food-truth-v2";
import {activePrepSummaryV2,prepExpansionCandidatesV2,prepRelationshipLabelV2,prepStarterSetsV2} from "@/data/prep-repertoire-v2";
import {foundationImages} from "@/data/foundation-assets";
import {feedback} from "@/lib/feedback";
import {prepHero,toneFor,toneGradient} from "@/lib/tones";
import {HomeSays} from "./HomeSays";
import {MealTile,SectionHead} from "./Primitives";

const tierLabel={mother:"Core bases",mid:"Mids & sauces",booster:"Boosters"} as const;
function componentHref(id:string,tier:"mother"|"mid"|"booster"){return tier==="mother"?`/prep/${id}`:tier==="mid"?`/prep/mids/${id}`:`/prep/boosters/${id}`}
function PrepThumb({id,code}:{id:string;code:string}){const img=prepHero(id);return <span style={{width:48,height:48,borderRadius:14,overflow:"hidden",display:"grid",placeItems:"center",background:toneGradient(id),color:"white",fontSize:10,fontWeight:800,flex:"0 0 auto"}}>{img?<img src={img} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/>:code.slice(0,7)}</span>}

export function Prep(){
 const h=useHousehold(),[showLibrary,setShowLibrary]=useState(false),active=h.activePrepIds??[],summary=useMemo(()=>activePrepSummaryV2(active),[active]);
 const weekIds=useMemo(()=>new Set(h.week.flatMap(id=>recipePrepV2(id).map(x=>x.componentId))),[h.week]),needsById=useMemo(()=>new Map(h.prepNeeds.map(x=>[x.id,x])),[h.prepNeeds]);
 const activeComponents=canonicalPrepComponentsV2.filter(c=>active.includes(c.id)).sort((a,b)=>a.tier.localeCompare(b.tier)||a.code.localeCompare(b.code)),inactiveNeeded=canonicalPrepComponentsV2.filter(c=>weekIds.has(c.id)&&!active.includes(c.id)),unlocked=recipes.filter(r=>summary.unlockedRecipeIds.includes(r.id)),expansions=prepExpansionCandidatesV2(active).filter(x=>x.newDinnerCount>0).slice(0,4),recent=h.prepBatches.slice(0,4);
 const setStarter=(ids:readonly string[])=>{h.setActivePrepSet(ids);feedback("success")},toggle=(id:string,on?:boolean)=>{h.toggleActivePrep(id,on);feedback("change")};
 const says=(()=>{if(!active.length)return{text:<>You do <b>not</b> need all 41 prep items. Pick a small repertoire and Home will build dinner around it.</>,actions:<button className="primary" onClick={()=>setStarter(prepStarterSetsV2.small.componentIds)}>Start with GOLD · SAMBAL · RED</button>};if(inactiveNeeded.length)return{text:<>This week asks for <b>{inactiveNeeded.slice(0,3).map(x=>x.code).join(", ")}</b> outside your active repertoire. Add them, or swap those dinners.</>,actions:<Link className="primary" href="/plan">Review the week</Link>};if(h.prepNeeds.length)return{text:<>Your repertoire is set. Prep Day only asks for what this week is actually short of.</>,actions:<Link className="primary" href="/prep/day">Open Prep Day</Link>};return{text:<><b>{active.length}</b> prep items are active and they currently unlock <b>{summary.unlockedCount}</b> of {summary.totalRecipes} dinners. Nothing in the current week is short.</>}})();
 return <div className="hm-screen">
  <h1 className="hm-h1 hm-gut">Prep</h1><HomeSays actions={says.actions}>{says.text}</HomeSays>
  {!active.length&&<><SectionHead title="How much do you want to maintain?" action={<span className="muted">change it anytime</span>}/><div className="hm-list tight">{[prepStarterSetsV2.small,prepStarterSetsV2.balanced,prepStarterSetsV2.fullMothers].map(s=>{const unlockedCount=activePrepSummaryV2(s.componentIds).unlockedCount;return <button key={s.id} className="hm-card hm-row hm-lift" style={{textAlign:"left",padding:14}} onClick={()=>setStarter(s.componentIds)}><span style={{width:44,height:44,borderRadius:14,display:"grid",placeItems:"center",background:"var(--tint-peach)",fontWeight:800}}>{s.componentIds.length}</span><span><strong>{s.label}</strong><small>{s.description}</small><small>{unlockedCount} dinners fit that repertoire</small></span></button>})}</div></>}
  {active.length>0&&<><SectionHead title="Your prep" action={<span className="muted">{active.length} active · {summary.unlockedCount} dinners</span>}/><div className="hm-list tight">{activeComponents.map(c=>{const need=needsById.get(c.id);return <div key={c.id} className="hm-card hm-row" style={{padding:"8px 10px",gridTemplateColumns:"52px 1fr auto"}}><Link href={componentHref(c.id,c.tier)}><PrepThumb id={c.id} code={c.code}/></Link><Link href={componentHref(c.id,c.tier)} style={{minWidth:0}}><strong>{c.code} · {c.name}</strong><small>{tierLabel[c.tier]} · {prepRelationshipLabelV2(c.id)}</small><small>{weekIds.has(c.id)?need?`this week · short ${need.shortQty} ${need.unit}`:"this week · covered":"active repertoire"}</small></Link><button className="hm-pill neutral" onClick={()=>toggle(c.id,false)}>Pause</button></div>})}</div></>}
  <SectionHead title="This week" action={<Link href="/prep/day">Prep Day ›</Link>}/>{weekIds.size?<div className="hm-list tight">{[...weekIds].map(id=>{const c=getComponent(id),truth=canonicalPrepComponentsV2.find(x=>x.id===id),need=needsById.get(id);if(!c||!truth)return null;return <Link key={id} href={componentHref(id,truth.tier)} className="hm-card hm-row hm-lift" style={{padding:"10px 14px 10px 10px"}}><PrepThumb id={id} code={c.code}/><span><strong>{c.name}</strong><small>{prepRelationshipLabelV2(id)}</small></span><span className={`hm-pill ${need?"peach":"sky"}`}>{need?`short ${need.shortQty} ${need.unit}`:"covered"}</span></Link>})}</div>:<div className="hm-empty"><strong>No prep dependencies this week.</strong>Your dinners are direct-ingredient dishes.</div>}
  <Link href="/prep/day" className={`hm-session hm-lift ${h.prepNeeds.length?"":"calm"}`} onClick={()=>feedback("tap")}><img src={foundationImages.prepDay} alt="" loading="lazy"/><div className="shade"/><div className="copy"><div><span className="kick">{h.prepNeeds.length?"THIS WEEK":"OPTIONAL STOCK-UP"}</span><h3>{h.prepNeeds.length?<>Make only the {h.prepNeeds.length} prep {h.prepNeeds.length===1?"item":"items"} the plan is short of</>:<>Nothing required<br/>prep only if you want to</>}</h3></div><span className="hm-btn">Open Prep Day</span></div></Link>
  {active.length>0&&<><SectionHead title="What your prep unlocks" action={<Link href="/cook">Browse all ›</Link>}/>{unlocked.length?<div className="hm-rail">{unlocked.slice(0,12).map(r=><MealTile key={r.id} recipe={r}/>)}</div>:<div className="hm-empty"><strong>No complete dinner is inside the active set yet.</strong>Add one more prep item below, or cook direct-ingredient recipes.</div>}{expansions.length>0&&<><SectionHead title="Add one more" action={<span className="muted">most new dinners first</span>}/><div className="hm-list tight">{expansions.map(x=>{const c=canonicalPrepComponentsV2.find(y=>y.id===x.componentId)!;return <button key={x.componentId} className="hm-card hm-row hm-lift" style={{textAlign:"left",padding:"10px 14px 10px 10px"}} onClick={()=>toggle(x.componentId,true)}><PrepThumb id={c.id} code={c.code}/><span><strong>{c.code} · {c.name}</strong><small>{prepRelationshipLabelV2(c.id)}</small></span><span className="hm-pill">+{x.newDinnerCount} dinners</span></button>})}</div></>}</>}
  {recent.length>0&&<><SectionHead title="Recent prep" action={<span className="muted">newest first</span>}/><div className="hm-batches">{recent.map((b,i)=>{const c=getComponent(b.componentId);return <div key={`${b.producedAt}-${i}`} className="hm-card" style={{"--tone":toneFor(b.componentId)} as CSSProperties}><i/><span><strong>{c?.code} · {c?.name}</strong><small>{new Date(b.producedAt).toLocaleDateString(undefined,{day:"numeric",month:"short"})} · {b.remaining.qty>0?`${b.remaining.qty} ${b.remaining.unit} left`:"used up"}</small></span><b>{b.initial.qty} {b.initial.unit}</b></div>})}</div></>}
  <SectionHead title="Prep library" action={<button onClick={()=>setShowLibrary(v=>!v)}>{showLibrary?"Hide":"Browse all 41"}</button>}/>{!showLibrary?<div className="hm-quick"><button className="hm-card hm-lift" style={{"--bg":"var(--grad-green-short)"} as CSSProperties} onClick={()=>setShowLibrary(true)}><span className="ic">8</span><strong>Core bases</strong></button><Link href="/prep/mids" className="hm-card hm-lift" style={{"--bg":"linear-gradient(135deg,#ffc2a8,#ff9f7a)"} as CSSProperties}><span className="ic">26</span><strong>Mids & sauces</strong></Link><Link href="/prep/boosters" className="hm-card hm-lift" style={{"--bg":"linear-gradient(135deg,#9fc0ff,#4f8cff)"} as CSSProperties}><span className="ic">7</span><strong>Boosters</strong></Link></div>:<div>{(["mother","mid","booster"] as const).map(tier=><div key={tier}><SectionHead title={tierLabel[tier]} action={<span className="muted">{canonicalPrepComponentsV2.filter(x=>x.tier===tier).length}</span>}/><div className="hm-list tight">{canonicalPrepComponentsV2.filter(x=>x.tier===tier).map(c=>{const on=active.includes(c.id);return <div key={c.id} className="hm-card hm-row" style={{padding:"8px 10px",gridTemplateColumns:"52px 1fr auto"}}><Link href={componentHref(c.id,c.tier)}><PrepThumb id={c.id} code={c.code}/></Link><Link href={componentHref(c.id,c.tier)}><strong>{c.code} · {c.name}</strong><small>{prepRelationshipLabelV2(c.id)}</small></Link><button className={`hm-pill ${on?"":"neutral"}`} onClick={()=>toggle(c.id,!on)}>{on?"Active":"Add"}</button></div>})}</div></div>)}</div>}
 </div>;
}
