"use client";
import Link from "next/link";
import {useMemo,useState,type CSSProperties} from "react";
import {useHousehold} from "../HouseholdState";
import {getComponent} from "@/data/home-data";
import {allLiveRecipesV7 as recipes} from "@/data/recipe-catalog-v7";
import {canonicalPrepComponentsV2} from "@/data/food-truth-v2";
import {prepForRecipeAtCookScaleV7} from "@/data/food-engine-v7";
import {activePrepSummaryV7,coreMotherIdsV7,optionalPrepIdsV7,prepExpansionCandidatesV7,prepRelationshipLabelV7,prepStarterSetsV7} from "@/data/prep-repertoire-v7";
import {formatPacketCountV6,getPrepPortionPolicyV6} from "@/data/prep-portioning-v6";
import {foundationImages} from "@/data/foundation-assets";
import {feedback} from "@/lib/feedback";
import {prepHero,toneFor,toneGradient} from "@/lib/tones";
import {HomeSays} from "./HomeSays";
import {formatQty,MealTile,SectionHead} from "./Primitives";

const tierLabel={mother:"Core bases",mid:"Mids & sauces",booster:"Boosters"} as const;
type LibraryFocus="core"|"mid"|"booster"|"optional"|null;
function componentHref(id:string,tier:"mother"|"mid"|"booster"){return tier==="mother"?`/prep/${id}`:tier==="mid"?`/prep/mids/${id}`:`/prep/boosters/${id}`}
function PrepThumb({id,code}:{id:string;code:string}){const img=prepHero(id);return <span className="hm-prep-thumb" style={{"--tone-grad":toneGradient(id)} as CSSProperties}>{img?<img src={img} alt=""/>:code.slice(0,7)}</span>}
function LibraryCard({title,kicker,count,ids,active,stocked,onClick,href,wide=false,quiet=false}:{title:string;kicker:string;count:number;ids:readonly string[];active:number;stocked:number;onClick?:()=>void;href?:string;wide?:boolean;quiet?:boolean}){
 const content=<><div className="visual">{ids.slice(0,3).map((id,i)=>{const img=prepHero(id);return img?<img key={id} src={img} alt="" style={{"--i":i} as CSSProperties}/>:null})}<div className="shade"/></div><div className="copy"><span className="kick">{kicker}</span><div className="title"><b>{count}</b><strong>{title}</strong></div><small>{active} active · {stocked} stocked</small><span className="go">Explore <b>→</b></span></div></>;
 const cls=`hm-prep-library-card ${wide?"wide":""} ${quiet?"quiet":""}`;
 return href?<Link href={href} className={cls} onClick={()=>feedback("tap")}>{content}</Link>:<button className={cls} onClick={onClick}>{content}</button>
}

export function Prep(){
 const h=useHousehold(),[showInventory,setShowInventory]=useState(false),[libraryFocus,setLibraryFocus]=useState<LibraryFocus>(null),active=h.activePrepIds??[],summary=useMemo(()=>activePrepSummaryV7(active),[active]);
 const displayWeek=h.weekStatus==="suggested"&&h.suggestedWeek?.length===7?h.suggestedWeek:h.week;
 const weekIds=useMemo(()=>new Set(displayWeek.flatMap(id=>prepForRecipeAtCookScaleV7(id).map(x=>x.componentId))),[displayWeek]),needsById=useMemo(()=>new Map(h.prepNeeds.map(x=>[x.id,x])),[h.prepNeeds]);
 const activeComponents=canonicalPrepComponentsV2.filter(c=>active.includes(c.id)).sort((a,b)=>a.tier.localeCompare(b.tier)||a.code.localeCompare(b.code)),inactiveNeeded=canonicalPrepComponentsV2.filter(c=>weekIds.has(c.id)&&!active.includes(c.id)),unlocked=recipes.filter(r=>summary.unlockedRecipeIds.includes(r.id)),expansions=prepExpansionCandidatesV7(active).filter(x=>x.newDinnerCount>0).slice(0,4),recent=h.prepBatches.slice(0,4);
 const stockedComponents=canonicalPrepComponentsV2.filter(c=>(h.componentStock[c.id]??0)>0),core=canonicalPrepComponentsV2.filter(c=>coreMotherIdsV7.includes(c.id)),mids=canonicalPrepComponentsV2.filter(c=>c.tier==="mid"),boosters=canonicalPrepComponentsV2.filter(c=>c.tier==="booster"),optional=canonicalPrepComponentsV2.filter(c=>optionalPrepIdsV7.has(c.id as "onion"));
 const categoryStats=(items:typeof canonicalPrepComponentsV2)=>({active:items.filter(c=>active.includes(c.id)).length,stocked:items.filter(c=>(h.componentStock[c.id]??0)>0).length});
 const setStarter=(ids:readonly string[])=>{h.setActivePrepSet(ids);feedback("success")},toggle=(id:string,on?:boolean)=>{h.toggleActivePrep(id,on);feedback("change")};
 const packetText=(id:string)=>{const p=getPrepPortionPolicyV6(id),qty=h.componentStock[id]??0;if(!p)return `${qty} recorded`;const n=formatPacketCountV6(qty/p.packet.qty);return `${n} ${p.kind==="stock-block"?"stock block":p.kind==="booster-dose"?"dose":"packet"}${n==="1"?"":"s"} · ${formatQty(qty,p.packet.unit)} total`};
 const adjustPacket=(id:string,delta:number)=>{const p=getPrepPortionPolicyV6(id);if(!p)return;h.setComponent(id,Math.max(0,(h.componentStock[id]??0)+delta*p.packet.qty));feedback("change")};
 const says=(()=>{if(!active.length&&stockedComponents.length)return{text:<>You already have <b>{stockedComponents.length}</b> prep {stockedComponents.length===1?"item":"items"} recorded. That is <b>Have now</b>. Choose separately what you want to keep maintaining, or plan around the stock you already have.</>,actions:<><Link className="primary" href="/plan" onClick={()=>h.setPlanPreferences("stock")}>Plan around what we have</Link><button className="ghost" onClick={()=>setShowInventory(true)}>Edit have now</button></>};if(!active.length)return{text:<>You do <b>not</b> need all 41 prep items. <b>Have now</b> is physical stock; <b>Our prep</b> is the smaller repertoire you want to maintain.</>,actions:<button className="primary" onClick={()=>setStarter(prepStarterSetsV7.small.componentIds)}>Start with GOLD · SAMBAL · RED</button>};if(inactiveNeeded.length)return{text:<>{h.weekStatus==="confirmed"?"This week":"The preview week"} asks for <b>{inactiveNeeded.slice(0,3).map(x=>x.code).join(", ")}</b> outside your active repertoire. Add them, or rebuild around your chosen prep.</>,actions:<Link className="primary" href="/plan">Review the week</Link>};if(h.weekStatus==="confirmed"&&h.prepNeeds.length)return{text:<>Your repertoire is set. Prep Day only asks for what the confirmed week is actually short of.</>,actions:<Link className="primary" href="/prep/day">Open Prep Day</Link>};return{text:<><b>{active.length}</b> prep items are in <b>Our prep</b> and they currently unlock <b>{summary.unlockedCount}</b> of {summary.totalRecipes} dinners. Physical stock remains separate.</>}})();
 const focused=libraryFocus==="core"?core:libraryFocus==="mid"?mids:libraryFocus==="booster"?boosters:libraryFocus==="optional"?optional:[];
 return <div className="hm-screen">
  <h1 className="hm-h1 hm-gut">Prep</h1><HomeSays actions={says.actions}>{says.text}</HomeSays>
  <SectionHead title="Have now" action={<button onClick={()=>setShowInventory(v=>!v)}>{showInventory?"Done":"Edit stock"}</button>}/>
  {!showInventory?(stockedComponents.length?<div className="hm-prep-stock-rail">{stockedComponents.map(c=><Link key={c.id} href={componentHref(c.id,c.tier)} className="hm-prep-stock-card"><PrepThumb id={c.id} code={c.code}/><span><strong>{c.code}</strong><small>{packetText(c.id)}</small></span></Link>)}</div>:<div className="hm-empty"><strong>No prep stock recorded yet.</strong>Tap Edit stock to add packets you already have. This does not add them to “Our prep”.</div>):<div className="hm-list tight">{canonicalPrepComponentsV2.map(c=>{const p=getPrepPortionPolicyV6(c.id),qty=h.componentStock[c.id]??0;return <div key={c.id} className="hm-card hm-row" style={{padding:"8px 10px",gridTemplateColumns:"52px 1fr auto"}}><Link href={componentHref(c.id,c.tier)}><PrepThumb id={c.id} code={c.code}/></Link><span><strong>{c.code} · {c.name}</strong><small>{qty>0?packetText(c.id):`none recorded · packet ${p?formatQty(p.packet.qty,p.packet.unit):"—"}`}</small></span><span className="hm-stock-step"><button aria-label={`Remove one ${c.code} packet`} disabled={qty<=0} onClick={()=>adjustPacket(c.id,-1)}>−</button><b>{p?formatPacketCountV6(qty/p.packet.qty):qty}</b><button aria-label={`Add one ${c.code} packet`} onClick={()=>adjustPacket(c.id,1)}>＋</button></span></div>})}</div>}
  {!active.length&&<><SectionHead title="Choose our prep" action={<span className="muted">change it anytime</span>}/><div className="hm-prep-starters">{[prepStarterSetsV7.small,prepStarterSetsV7.balanced,prepStarterSetsV7.fullMothers].map((s,i)=>{const unlockedCount=activePrepSummaryV7(s.componentIds).unlockedCount,hero=prepHero(s.componentIds[0]);return <button key={s.id} className={`hm-prep-starter ${i===0?"featured":""}`} onClick={()=>setStarter(s.componentIds)}>{hero&&<img src={hero} alt=""/>}<div className="shade"/><div className="copy"><span>{s.componentIds.length} prep items</span><strong>{s.label}</strong><small>{s.description}</small><b>{unlockedCount} dinners fit →</b></div></button>})}</div></>}
  {active.length>0&&<><SectionHead title="Our prep" action={<span className="muted">{active.length} active · {summary.unlockedCount} dinners</span>}/><div className="hm-prep-active-grid">{activeComponents.map(c=>{const need=needsById.get(c.id),img=prepHero(c.id);return <div key={c.id} className="hm-prep-active-card"><Link href={componentHref(c.id,c.tier)} className="photo">{img?<img src={img} alt={c.name}/>:<span style={{background:toneGradient(c.id)}}/>}<div className="shade"/><strong>{c.code}</strong><small>{c.name}</small></Link><div className="meta"><span>{weekIds.has(c.id)?need?`${h.weekStatus==="confirmed"?"this week":"preview"} · short ${formatQty(need.shortQty,need.unit)}`:`${h.weekStatus==="confirmed"?"this week":"preview"} · covered`:prepRelationshipLabelV7(c.id)}</span><button onClick={()=>toggle(c.id,false)}>Pause</button></div></div>})}</div><Link href="/plan" className="hm-card hm-row hm-lift hm-prep-plan-link" onClick={()=>h.setPlanPreferences("repertoire",h.allowExtraPrep)}><span className="hm-pill">Plan</span><span><strong>Plan around this prep</strong><small>Prioritise this maintenance repertoire; Home can keep or forbid extra prep.</small></span><span>›</span></Link></>}
  <SectionHead title="Prep library" action={<span className="muted">visual library · 41 total</span>}/>
  <div className="hm-prep-library"><LibraryCard wide kicker="FOUNDATIONS" title="Core bases" count={core.length} ids={core.map(x=>x.id)} {...categoryStats(core)} onClick={()=>setLibraryFocus(libraryFocus==="core"?null:"core")}/><LibraryCard kicker="SAUCES" title="Mids & sauces" count={mids.length} ids={mids.map(x=>x.id)} {...categoryStats(mids)} href="/prep/mids"/><LibraryCard kicker="FINISHERS" title="Boosters" count={boosters.length} ids={boosters.map(x=>x.id)} {...categoryStats(boosters)} href="/prep/boosters"/><LibraryCard wide quiet kicker="OPTIONAL" title="Caramelised onion foundation" count={optional.length} ids={optional.map(x=>x.id)} {...categoryStats(optional)} onClick={()=>setLibraryFocus(libraryFocus==="optional"?null:"optional")}/></div>
  {libraryFocus&&<div className="hm-prep-library-expanded" id="prep-library-detail"><SectionHead title={libraryFocus==="core"?"7 core bases":libraryFocus==="optional"?"Optional foundation":tierLabel[libraryFocus]} action={<button onClick={()=>setLibraryFocus(null)}>Close</button>}/><div className="hm-prep-photo-grid">{focused.map(c=>{const img=prepHero(c.id),on=active.includes(c.id),qty=h.componentStock[c.id]??0;return <article key={c.id} className="hm-prep-photo-card"><Link href={componentHref(c.id,c.tier)} className="photo">{img?<img src={img} alt={c.name}/>:<span style={{background:toneGradient(c.id)}}/>}<div className="shade"/><span className="code">{c.code}</span>{qty>0&&<span className="stock">stocked</span>}</Link><div className="copy"><strong>{c.name}</strong><small>{prepRelationshipLabelV7(c.id)}</small><button className={on?"on":""} onClick={()=>toggle(c.id,!on)}>{on?"In our prep ✓":"Add to our prep"}</button></div></article>})}</div></div>}
  <SectionHead title={h.weekStatus==="confirmed"?"This week":"Preview week"} action={<Link href={h.weekStatus==="confirmed"?"/prep/day":"/plan"}>{h.weekStatus==="confirmed"?"Prep Day ›":"Review plan ›"}</Link>}/>
  {weekIds.size?<div className="hm-list tight">{[...weekIds].map(id=>{const c=getComponent(id),truth=canonicalPrepComponentsV2.find(x=>x.id===id),need=needsById.get(id);if(!c||!truth)return null;return <Link key={id} href={componentHref(id,truth.tier)} className="hm-card hm-row hm-lift" style={{padding:"10px 14px 10px 10px"}}><PrepThumb id={id} code={c.code}/><span><strong>{c.name}</strong><small>{prepRelationshipLabelV7(id)}</small></span><span className={`hm-pill ${need?"peach":"sky"}`}>{need?`short ${formatQty(need.shortQty,need.unit)}`:"covered"}</span></Link>})}</div>:<div className="hm-empty"><strong>No prep dependencies in this {h.weekStatus==="confirmed"?"week":"preview"}.</strong>The dinners are direct-ingredient dishes.</div>}
  <Link href={h.weekStatus==="confirmed"?"/prep/day":"/plan"} className={`hm-session hm-lift ${h.weekStatus==="confirmed"&&h.prepNeeds.length?"":"calm"}`} onClick={()=>feedback("tap")}><img src={foundationImages.prepDay} alt="" loading="lazy"/><div className="shade"/><div className="copy"><div><span className="kick">{h.weekStatus==="confirmed"?(h.prepNeeds.length?"THIS WEEK":"OPTIONAL STOCK-UP"):"PREVIEW ONLY"}</span><h3>{h.weekStatus!=="confirmed"?<>Confirm the week before turning gaps into a Prep Day</>:h.prepNeeds.length?<>Make only the {h.prepNeeds.length} prep {h.prepNeeds.length===1?"item":"items"} the plan is short of</>:<>Nothing required<br/>prep only if you want to</>}</h3></div><span className="hm-btn">{h.weekStatus==="confirmed"?"Open Prep Day":"Review Plan"}</span></div></Link>
  {active.length>0&&<><SectionHead title="What your prep unlocks" action={<Link href="/cook">Browse all ›</Link>}/>{unlocked.length?<div className="hm-rail">{unlocked.slice(0,12).map(r=><MealTile key={r.id} recipe={r}/>)}</div>:<div className="hm-empty"><strong>No complete dinner is inside the active set yet.</strong>Add one more prep item below, or cook direct-ingredient recipes.</div>}{expansions.length>0&&<><SectionHead title="Add one more" action={<span className="muted">most new dinners first</span>}/><div className="hm-list tight">{expansions.map(x=>{const c=canonicalPrepComponentsV2.find(y=>y.id===x.componentId)!;return <button key={x.componentId} className="hm-card hm-row hm-lift" style={{textAlign:"left",padding:"10px 14px 10px 10px"}} onClick={()=>toggle(x.componentId,true)}><PrepThumb id={c.id} code={c.code}/><span><strong>{c.code} · {c.name}</strong><small>{prepRelationshipLabelV7(c.id)}</small></span><span className="hm-pill">+{x.newDinnerCount} dinners</span></button>})}</div></>}</>}
  {recent.length>0&&<><SectionHead title="Recent prep" action={<span className="muted">newest first</span>}/><div className="hm-batches">{recent.map((b,i)=>{const c=getComponent(b.componentId);return <div key={`${b.producedAt}-${i}`} className="hm-card" style={{"--tone":toneFor(b.componentId)} as CSSProperties}><i/><span><strong>{c?.code} · {c?.name}</strong><small>{new Date(b.producedAt).toLocaleDateString(undefined,{day:"numeric",month:"short"})} · {b.remaining.qty>0?`${formatQty(b.remaining.qty,b.remaining.unit)} left`:"used up"}</small></span><b>{formatQty(b.initial.qty,b.initial.unit)}</b></div>})}</div></>}
 </div>;
}
