"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import {useHousehold} from "../HouseholdState";
import {getComponent,getIngredient,getRecipe} from "@/data/home-data";
import {recipeSubtitle,recipeTitle} from "@/data/recipe-display";
import {feedback} from "@/lib/feedback";
import {ingredientRequirementMissing} from "@/data/stock-math";
import {useSheet} from "@/lib/useSheet";
import {Back,ComponentPill,formatQty,RecipeReady} from "./Primitives";

const days=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
function stateLevelLabel(value:number){return value>=3?"plenty":value>=2?"some":value>=1?"low":"out"}
export function Recipe({id}:{id:string}){
 const h=useHousehold();const r=getRecipe(id);const[chooseDay,setChooseDay]=useState(false);const[note,setNote]=useState(h.ratings[id]?.note??"");const[noteAuthor,setNoteAuthor]=useState<"josh"|"g">("josh");const[saved,setSaved]=useState(false);const[versionSaved,setVersionSaved]=useState(false);useSheet(chooseDay,()=>setChooseDay(false));
 const cooked=h.history.filter(x=>x.mealId===id);const lastNote=h.recipeNotes[id]?.[0];const rating=h.ratings[id]??{};const favourite=!!h.favourites[id];const versions=h.recipeVersions[id]??[];const currentVersion=versions[0]?.number??1;const latestVersionSummary=versions[0]?.summary;const personalPhoto=h.mealPhotos.find(x=>x.mealId===id);
 const events=useMemo(()=>[...cooked.map(x=>({at:x.at,label:"Cooked",detail:"Dinner logged"})),...(h.recipeNotes[id]??[]).map(x=>({at:x.at,label:x.author==="josh"?"Josh note":x.author==="g"?"G note":"Our note",detail:x.text})),...versions.map(v=>({at:v.at,label:`v${v.number} adopted`,detail:v.summary}))].sort((a,b)=>new Date(b.at).getTime()-new Date(a.at).getTime()).slice(0,7),[cooked,h.recipeNotes,id,versions]);
 const cues=useMemo(()=>r.steps.filter(s=>/(until|fragrant|aromatic|glossy|clings?|tender|golden|brown|crisp|wilt|thicken|reduce|coats?|soft|sizzling|bubbl)/i.test(s)).slice(0,4),[r.steps]);
 const saveNote=()=>{const clean=note.trim();if(!clean)return;h.noteMeal(id,clean,noteAuthor);setSaved(true);setVersionSaved(false);feedback("success");setTimeout(()=>setSaved(false),1400)};
 const promote=(summary:string,author:"josh"|"g"|"home"="home")=>{const clean=summary.trim();if(!clean||clean===latestVersionSummary)return;h.promoteRecipeVersion(id,clean,author);setVersionSaved(true);feedback("success");setTimeout(()=>setVersionSaved(false),1600)};
 const title=recipeTitle(r.id,r.title),subtitle=recipeSubtitle(r.id,r.subtitle);
 return <div className="hm-page-v5 hm-recipe-v5">
  <div className="hm-recipe-top-v5"><Back href="/cook" label="Recipes"/><button className={`hm-favourite-v5 ${favourite?"on":""}`} aria-label={favourite?"Remove from favourites":"Add to favourites"} onClick={()=>{h.toggleFavourite(id);feedback("change")}}>{favourite?"♥":"♡"}</button></div>
  <section className="hm-recipe-hero-v5">{r.image?<img src={r.image} alt={title} width={780} height={520} loading="eager" fetchPriority="high" decoding="async"/>:<div className="hm-photo-placeholder-v5">{title[0]}</div>}<div className="hm-recipe-hero-shade-v5"/><div className="hm-recipe-hero-copy-v5"><div><span>{r.cuisine}</span><RecipeReady recipe={r}/></div><h1>{title}</h1><p>{subtitle}</p><small>{r.minutes} min · {r.method} · serves 2</small></div></section>
  <div className="hm-sticky-actions-v5"><Link href={`/cook/${r.id}/cook`}>Cook</Link><button onClick={()=>setChooseDay(true)}>Add to week</button></div>
  {cooked.length===0&&!lastNote&&<div className="hm-not-cooked-v7"><strong>Not cooked by us yet.</strong> This stays a test recipe until Josh or G actually makes it and leaves a rating or note.</div>}
  {(cooked.length>0||lastNote||favourite)&&<section className="hm-our-note-v5 hm-version-card-v22"><span>OUR VERSION · v{currentVersion}</span>{personalPhoto&&<figure className="hm-version-photo-v24"><img src={personalPhoto.dataUrl} alt={`${title} we cooked`}/><figcaption>Our dinner · {new Date(personalPhoto.at).toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"})}</figcaption></figure>}<div className="hm-couple-rating-v5"><b>J</b><strong>{rating.josh?`${rating.josh}★`:"—"}</strong><b>G</b><strong>{rating.g?`${rating.g}★`:"—"}</strong>{favourite&&<em>♥ Favourite</em>}</div>{lastNote&&<p>“{lastNote.text}” <small>— {lastNote.author==="josh"?"Josh":lastNote.author==="g"?"G":"us"}</small></p>}<small>{cooked.length?`Cooked ${cooked.length} ${cooked.length===1?"time":"times"}`:"Not cooked yet"}</small>{lastNote&&lastNote.text!==latestVersionSummary&&<button className="hm-version-adopt-v22" onClick={()=>promote(lastNote.text,lastNote.author)}>{versionSaved?`v${currentVersion+1} saved ✓`:`Make this v${currentVersion+1}`}</button>}{versions.length>0&&<div className="hm-version-latest-v22"><b>v{versions[0].number}</b><span>{versions[0].summary}</span><small>{new Date(versions[0].at).toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"})}</small></div>}<Link className="hm-version-photo-link-v24" href={`/scan?mode=Meal&meal=${id}&back=${encodeURIComponent(`/cook/${id}`)}`}>{personalPhoto?"Replace dinner photo":"Save a dinner photo"} →</Link></section>}
  <section className="hm-recipe-section-v5"><h2>What we need</h2><div className="hm-ingredient-list-v5">{r.ingredients.map(x=>{const d=getIngredient(x.id);const onHand=h.ingredientStock[x.id]??0;const missing=h.kitchenReady&&ingredientRequirementMissing(x,h.ingredientStock);const status=x.optional?"optional":!h.kitchenReady?"not checked":d?.tracking==="state"?(onHand>0?stateLevelLabel(onHand):"out"):missing?(onHand>0?`${formatQty(onHand,x.unit)} at home`:"out"):"have enough";return <div key={`${x.id}-${x.raw}`}><span>{d?.name??x.id}</span><div style={{textAlign:"right"}}><strong style={{display:"block"}}>{x.display}</strong><small style={{display:"block",fontSize:13,marginTop:2,color:x.optional?"#806f5d":h.kitchenReady?(missing?"#9b4737":d?.tracking==="state"&&onHand===1?"#956025":"#2f684d"):"var(--muted)",fontWeight:h.kitchenReady&&!x.optional?750:400}}>{status}</small></div></div>})}</div></section>
  {r.prep.length>0&&<section className="hm-recipe-section-v5"><h2>From prep</h2><div className="hm-prep-list-v5">{r.prep.map(x=>{const have=h.componentStock[x.id]??0;return <div key={x.id}><ComponentPill id={x.id} amountMl={x.totalMl}/><span className={h.kitchenReady&&have>=x.totalMl?"ok":"need"}>{h.kitchenReady?have>=x.totalMl?"have it":`${Math.max(0,x.totalMl-have)} ml short`:"not checked"}</span></div>})}</div></section>}
  <section className="hm-recipe-section-v5"><h2>Method</h2><ol className="hm-step-list-v5">{r.steps.map((s,i)=><li key={s}><b>{i+1}</b><p>{s}</p></li>)}</ol></section>
  {cues.length>0&&<section className="hm-recipe-section-v5 hm-recipe-cues-v64"><h2>What you’re looking for</h2><div>{cues.map((cue,i)=><p key={`${i}-${cue}`}><b>✓</b><span>{cue}</span></p>)}</div></section>}
  <section className="hm-recipe-section-v5 hm-why-v5"><details><summary>Serving notes</summary><p>{r.balance}</p></details><a href={r.source.url} target="_blank" rel="noreferrer">Recipe reference ↗</a></section>
  {events.length>0&&<section className="hm-recipe-history-v5"><header><span>OUR HISTORY</span><h2>How this one is changing</h2></header><div>{events.map((e,i)=><article key={`${e.at}-${i}`}><i/><span><strong>{e.label}</strong><p>{e.detail}</p><small>{new Date(e.at).toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"})}</small></span></article>)}</div></section>}
  <section className="hm-rate-v5"><div><span>AFTER DINNER</span><h2>How was it?</h2></div>{(["josh","g"] as const).map(who=><div className="hm-rate-person-v5" key={who}><strong>{who==="josh"?"Josh":"G"}</strong><div>{[1,2,3,4,5].map(n=><button key={n} className={(rating[who]??0)>=n?"on":""} aria-label={`${who} ${n} stars`} onClick={()=>{h.rateMeal(id,who,n);feedback("change")}}>★</button>)}</div></div>)}<label><span>Next time</span><div className="hm-note-author-v7" aria-label="Who is leaving this note?"><button type="button" className={noteAuthor==="josh"?"active":""} onClick={()=>{setNoteAuthor("josh");feedback("tap")}}>Josh</button><button type="button" className={noteAuthor==="g"?"active":""} onClick={()=>{setNoteAuthor("g");feedback("tap")}}>G</button></div><textarea value={note} onChange={e=>{setNote(e.target.value);setVersionSaved(false)}} placeholder="More chilli? Less sweet? Different side?"/><button disabled={!note.trim()} onClick={saveNote}>{saved?"Saved ✓":`Save ${noteAuthor==="josh"?"Josh":"G"}'s note`}</button>{note.trim()&&note.trim()!==latestVersionSummary&&<button type="button" className="hm-version-inline-v22" onClick={()=>promote(note,noteAuthor)}>{versionSaved?`Saved as v${currentVersion+1} ✓`:`Adopt as v${currentVersion+1}`}</button>}</label></section>
  {chooseDay&&<div className="hm-sheet-backdrop-v5" onMouseDown={e=>{if(e.target===e.currentTarget)setChooseDay(false)}}><section className="hm-sheet-v5" role="dialog" aria-modal="true" aria-label="Add recipe to week"><div className="hm-sheet-handle-v5"/><header><div><span>ADD TO WEEK</span><h2>Which day?</h2></div><button className="hm-icon-button-v5" onClick={()=>setChooseDay(false)} aria-label="Close">×</button></header><div className="hm-day-picker-v5">{days.map((d,i)=>{const current=getRecipe(h.week[i]);return <button key={d} onClick={()=>{h.setDay(i,id);setChooseDay(false);feedback("change")}}><span>{d}</span><strong>{recipeTitle(current.id,current.title)}</strong></button>})}</div></section></div>}
 </div>
}