"use client";
import Link from "next/link";
import {useEffect,useMemo,useState,type CSSProperties} from "react";
import {feedback} from "@/lib/feedback";
import {motherBases} from "@/data/home-data";
import {getLiveRecipeV7} from "@/data/recipe-catalog-v7";
import {ingredientUiCatalogV7 as ingredients,getIngredientUiV7,ingredientUiNameV7} from "@/data/ingredient-ui-v7";
import {ingredientsForRecipeV7,canonicalIngredientIdForRuntimeV7} from "@/data/ingredient-engine-v7";
import {getCanonicalPrepV2} from "@/data/food-truth-v2";
import {stockPortionsV7} from "@/data/stock-math-v7";
import {recipeTitle} from "@/data/recipe-display";
import {useHousehold} from "../HouseholdState";
import {Icon} from "../Icons";
import {toneFor,toneGradient} from "@/lib/tones";
import {HomeSays} from "./HomeSays";
import {Orb} from "./Orb";
import {Check,formatQty,SectionHead,Toast} from "./Primitives";

const modes=[{id:"Fridge",label:"Fridge",title:"Point at the fridge",hint:"Frame the shelves so the useful food is easy to see."},{id:"Freezer",label:"Freezer",title:"Open the freezer",hint:"One drawer or one labelled prep section at a time."},{id:"Pantry",label:"Pantry",title:"Open the pantry",hint:"One shelf at a time so the staples are easy to check."},{id:"Receipt",label:"Receipt",title:"Show the receipt",hint:"Flat and readable, top to bottom."},{id:"Prep",label:"Prep check",title:"Show the pan",hint:"The colour and texture you want to check."},{id:"Meal",label:"Dinner",title:"Show dinner",hint:"What we actually cooked, for the cookbook."}] as const;
type Mode=(typeof modes)[number]["id"];const levels=["Out","Low","Some","Plenty"];
function scanStep(item:{id:string;category:string;unit:string}){if(item.unit==="count"||item.unit==="portion")return 1;if(item.unit==="ml")return item.category==="Dairy"?100:50;if(item.unit==="g")return item.category==="Protein"?200:item.category==="Fresh"?100:50;return 1}
function compressMealPhoto(file:File){return new Promise<string>((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{try{const render=(max:number,quality:number)=>{const scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext("2d");if(!ctx)throw new Error("canvas");ctx.drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL("image/jpeg",quality)};let data=render(760,.68);if(data.length>440000)data=render(640,.6);if(data.length>440000)data=render(540,.52);URL.revokeObjectURL(url);if(data.length>520000)throw new Error("photo-budget");resolve(data)}catch(e){URL.revokeObjectURL(url);reject(e)}};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("image"))};img.src=url})}
export function Scan(){
 const h=useHousehold();const[mode,setMode]=useState<Mode>("Fridge"),[preview,setPreview]=useState<string>(),[file,setFile]=useState<File>(),[error,setError]=useState(""),[back,setBack]=useState("/"),[nonce,setNonce]=useState(0),[receiptChecked,setReceiptChecked]=useState<string[]>([]),[mealId,setMealId]=useState<string>(),[mealSaving,setMealSaving]=useState(false),[toast,setToast]=useState(""),[changed,setChanged]=useState<Record<string,boolean>>({});
 useEffect(()=>{const p=new URLSearchParams(window.location.search),m=p.get("mode") as Mode|null;if(m&&modes.some(x=>x.id===m))setMode(m);const b=p.get("back");if(b?.startsWith("/"))setBack(b);const meal=p.get("meal");if(meal)setMealId(meal)},[]);useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 const flash=(t:string)=>{setToast(t);window.setTimeout(()=>setToast(""),1600)},clear=()=>{if(preview)URL.revokeObjectURL(preview);setPreview(undefined);setFile(undefined);setError("");setNonce(n=>n+1);setReceiptChecked([]);setChanged({})},chooseMode=(m:Mode)=>{clear();setMode(m);feedback("tap")};
 const chooseFile=(f?:File)=>{if(!f)return;clear();if(f.type&&!f.type.startsWith("image/")){setError("That file isn’t an image.");return}if(f.size>16*1024*1024){setError("That photo is very large — try a smaller one.");return}try{setFile(f);setPreview(URL.createObjectURL(f));feedback("change")}catch{setError("That photo couldn’t be opened.")}};
 const current=modes.find(x=>x.id===mode)!,targetMealId=mealId??h.history[0]?.mealId,targetMeal=targetMealId?getLiveRecipeV7(targetMealId):undefined,relevant=useMemo(()=>new Set(h.week.flatMap(rid=>ingredientsForRecipeV7(rid).filter(x=>!x.optional).map(canonicalIngredientIdForRuntimeV7))),[h.week]);
 const quick=useMemo(()=>ingredients.filter(i=>mode==="Pantry"?i.category==="Pantry":["Fresh","Protein","Dairy"].includes(i.category)).sort((a,b)=>Number(relevant.has(b.id))-Number(relevant.has(a.id))||Number((h.ingredientStock[b.id]??0)>0)-Number((h.ingredientStock[a.id]??0)>0)||a.name.localeCompare(b.name)).slice(0,12),[mode,relevant,h.ingredientStock]);
 const adjust=(id:string,delta:number)=>{const item=getIngredientUiV7(id);if(!item)return;const cur=h.ingredientStock[id]??0;h.setIngredient(id,item.tracking==="state"?Math.max(0,Math.min(3,cur+delta)):Math.max(0,cur+delta*scanStep(item)));setChanged(v=>({...v,[id]:true}));feedback("change")};
 const adjustBase=(id:string,delta:number)=>{const truth=getCanonicalPrepV2(id);if(!truth)return;h.setComponent(id,Math.max(0,(h.componentStock[id]??0)+delta*truth.workingUnit.qty));setChanged(v=>({...v,[id]:true}));feedback("change")};
 const toggleReceipt=(id:string)=>{setReceiptChecked(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);feedback("tap")},addReceipt=()=>{for(const id of receiptChecked){const item=h.shoppingNeeds.find(x=>x.id===id);if(!item)continue;const cur=h.ingredientStock[id]??0;h.setIngredient(id,item.unit==="have"?Math.max(cur,2):cur+item.qty);if(h.groceryChecked[id])h.toggleGrocery(id)}flash(`${receiptChecked.length} added to Kitchen`);setReceiptChecked([]);feedback("success")};
 const saveMeal=async()=>{if(!file||!targetMealId||mealSaving)return;setMealSaving(true);try{h.saveMealPhoto(targetMealId,await compressMealPhoto(file));flash("Saved with dinner");feedback("success")}catch{setError("That photo couldn’t be saved in the phone’s photo budget.")}finally{setMealSaving(false)}};
 const confirmed=Object.keys(changed).length,kitchenTab=mode==="Pantry"?"Pantry":mode==="Freezer"?"Freezer":"Fridge";
 const says=(()=>{if(error)return{text:<>{error} Try another photo — the controls below still work.</>};if(!preview)return{text:<>{current.hint} I won’t guess quantities — you confirm what goes in.</>};if(mode==="Receipt")return{text:h.shoppingNeeds.length?<>Tick the lines you can see on the receipt. Exact purchases update exact stock; qualitative pantry stays qualitative.</>:<>This week’s list is already clear. Anything else goes in through Kitchen.</>};if(mode==="Prep")return{text:<>Compare the pan with the base’s cue — colour, gloss and texture. Appearance never proves internal food safety.</>};if(mode==="Meal")return{text:targetMeal?<>Keep this with <b>{recipeTitle(targetMeal.id,targetMeal.title)}</b>? Only a small copy stays on this phone.</>:<>Log a dinner first, then a photo can sit with it.</>};return{text:<>Use the photo as your reference and tap what’s changed{confirmed?` — ${confirmed} updated so far.`:"."}</>}})();
 return <div className="hm-scan"><div className="stage">{preview&&<img src={preview} alt={`${mode} photo`} onError={()=>{clear();setError("That photo couldn’t be displayed.")}}/>}<div className="shade"/><div className="top"><Link href={back} className="hm-round dark" aria-label="Close camera">×</Link><span className="hm-pill onphoto">{current.title}</span><button aria-label="Ask Home" onClick={()=>window.dispatchEvent(new Event("home-meals:ask"))} style={{display:"grid",placeItems:"center"}}><Orb size={44}/></button></div>{!preview&&<div className="frame"><span>{mode==="Receipt"?"Whole receipt in frame":mode==="Prep"?"Fill the frame with the pan":"Steady · good light"}</span></div>}{!preview&&<div className="controls"><label><input key={`lib-${nonce}`} type="file" accept="image/*" aria-label="Choose a photo from the library" onChange={e=>chooseFile(e.target.files?.[0])}/><Icon name="camera" size={20}/></label><label className="shutter"><input key={`cam-${nonce}`} type="file" accept="image/*" capture="environment" aria-label="Take a photo" onChange={e=>chooseFile(e.target.files?.[0])}/></label><button aria-label="Open Kitchen" onClick={()=>{window.location.href="/kitchen"}}><Icon name="kitchen" size={20}/></button></div>}<HomeSays bubbleClass="dark">{says.text}</HomeSays></div><div className="hm-scan-panel"><div className="modes" role="tablist">{modes.map(m=><button key={m.id} role="tab" aria-selected={mode===m.id} className={mode===m.id?"on":""} onClick={()=>chooseMode(m.id)}>{m.label}</button>)}</div>{!preview&&<div className="acts"><Link className="hm-btn ghost sm" href={mode==="Meal"?(targetMeal?`/cook/${targetMeal.id}`:"/cook"):mode==="Prep"?(back.startsWith("/prep")||back.startsWith("/cook")?back:"/prep"):"/kitchen"}>{mode==="Meal"?"Our recipes":mode==="Prep"?"Open the cues":"Add manually"}</Link><label className="hm-btn primary sm" style={{position:"relative",cursor:"pointer"}}><input key={`cta-${nonce}`} type="file" accept="image/*" capture="environment" aria-label="Take the photo" onChange={e=>chooseFile(e.target.files?.[0])} style={{position:"absolute",inset:0,opacity:0,cursor:"pointer"}}/>Take the photo</label></div>}
 {preview&&(mode==="Fridge"||mode==="Pantry")&&<><SectionHead title={mode==="Fridge"?"What you can see":"Useful staples"} action={<Link href="/kitchen">Full {kitchenTab.toLowerCase()} ›</Link>}/><div className="hm-list tight">{quick.map(item=>{const n=h.ingredientStock[item.id]??0;return<div key={item.id} className="hm-card hm-scan-row"><span><strong>{item.name}</strong><small>{relevant.has(item.id)?"This week":"Kitchen"}{changed[item.id]?" · updated":""}</small></span><div className="hm-stepper"><button className="minus" disabled={n<=0} onClick={()=>adjust(item.id,-1)}>−</button><b>{item.tracking==="state"?levels[Math.min(3,n)]:n>0?formatQty(n,item.unit):"Out"}</b><button className="plus" disabled={item.tracking==="state"&&n>=3} onClick={()=>adjust(item.id,1)}>+</button></div></div>})}</div><div className="acts" style={{marginTop:18}}><button className="hm-btn ghost sm" onClick={clear}>Discard photo</button><Link className="hm-btn primary sm" href={back.startsWith("/")?back:"/kitchen"} onClick={()=>{if(confirmed)h.confirmKitchen()}}>{confirmed?`Confirm ${confirmed}`:"Done"}</Link></div></>}
 {preview&&mode==="Freezer"&&<><SectionHead title="Count the bases" action={<Link href="/kitchen">Full freezer ›</Link>}/><div className="hm-list tight">{motherBases.map(m=>{const truth=getCanonicalPrepV2(m.id);if(!truth)return null;const qty=h.componentStock[m.id]??0,n=stockPortionsV7(m.id,h.componentStock);return<div key={m.id} className="hm-card hm-scan-row" style={{gridTemplateColumns:"10px 1fr auto",gap:12}}><i className="hm-dot" style={{"--tone":toneFor(m.id),width:10,height:44,borderRadius:999,background:toneGradient(m.id)} as CSSProperties}/><span><strong>{m.code}</strong><small>{m.name} · {qty} {truth.workingUnit.unit}{changed[m.id]?" · updated":""}</small></span><div className="hm-stepper"><button className="minus" disabled={qty<=0} onClick={()=>adjustBase(m.id,-1)}>−</button><b>{n}</b><button className="plus" onClick={()=>adjustBase(m.id,1)}>+</button></div></div>})}</div><div className="acts" style={{marginTop:18}}><button className="hm-btn ghost sm" onClick={clear}>Discard photo</button><Link className="hm-btn primary sm" href="/kitchen" onClick={()=>{if(confirmed)h.confirmKitchen()}}>{confirmed?`Confirm ${confirmed}`:"Done"}</Link></div></>}
 {preview&&mode==="Receipt"&&<><SectionHead title="What came home" action={<span className="muted">{receiptChecked.length}/{Math.min(12,h.shoppingNeeds.length)}</span>}/>{h.shoppingNeeds.length?<div className="hm-list tight">{h.shoppingNeeds.slice(0,12).map(item=>{const on=receiptChecked.includes(item.id);return<button key={item.canonicalId} className={`hm-checkrow ${on?"done":""}`} aria-pressed={on} onClick={()=>toggleReceipt(item.id)}><Check on={on}/><span className="name">{ingredientUiNameV7(item.canonicalId)}</span><small>{item.unit==="have"?"restock":formatQty(item.qty,item.unit)}</small></button>})}</div>:<div className="hm-empty"><strong>The list is already clear.</strong>Anything extra goes in through Kitchen.</div>}<div className="acts" style={{marginTop:18}}><button className="hm-btn ghost sm" onClick={clear}>Discard</button><button className="hm-btn primary sm" disabled={!receiptChecked.length} onClick={addReceipt}>Add {receiptChecked.length||""} to Kitchen</button></div></>}
 {preview&&mode==="Prep"&&<><SectionHead title="Compare with the cue" action={<span className="muted">colour · gloss · texture</span>}/><div className="hm-list tight">{motherBases.filter(m=>back.includes(`/prep/${m.id}`)||!back.includes("/prep/")).slice(0,back.includes("/prep/")?1:4).map(m=><Link key={m.id} href={`/prep/${m.id}`} className="hm-card hm-row hm-lift"><span style={{width:44,height:44,borderRadius:14,background:toneGradient(m.id),color:"#fff",fontSize:11,fontWeight:800,display:"grid",placeItems:"center"}}>{m.code}</span><span><strong>{m.name}</strong><small>Open source-backed method and cues</small></span></Link>)}</div></>}
 {preview&&mode==="Meal"&&<><SectionHead title="Dinner photo"/>{targetMeal?<div className="hm-card lg"><strong>{recipeTitle(targetMeal.id,targetMeal.title)}</strong><p className="hm-note">This photo is household memory, not evidence of internal temperature or doneness.</p><button className="hm-btn primary full" disabled={!file||mealSaving} onClick={()=>void saveMeal()}>{mealSaving?"Saving…":"Save with dinner"}</button></div>:<div className="hm-empty"><strong>No dinner to attach this to yet.</strong></div>}</>}
 </div>{toast&&<Toast text={toast}/>}</div>;
}
