"use client";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {useEffect,useMemo,useState} from "react";
import {Icon} from "../Icons";
import {useHousehold} from "../HouseholdState";
import {getIngredient,getRecipe,ingredients,prepComponents,recipes} from "@/data/home-data";
import {recipeTitle} from "@/data/recipe-display";
import {recipeAvailability} from "@/data/stock-math";
import {freezerAge,freezerGuide} from "@/data/freezer-guide";
import {formatQty} from "./Primitives";
import {bindGlobalHaptics,feedback} from "@/lib/feedback";
import {useSheet} from "@/lib/useSheet";

const nav=[
 {href:"/",label:"Home",icon:"home" as const},
 {href:"/cook",label:"Cook",icon:"cook" as const},
 {href:"/prep",label:"Prep",icon:"prep" as const},
 {href:"/kitchen",label:"Kitchen",icon:"kitchen" as const},
 {href:"/plan",label:"Plan",icon:"plan" as const}
];
type AskMessage={who:"you"|"home";text:string;mealIds?:string[];tags?:string[];href?:string;action?:string};
type HomeReply=Omit<AskMessage,"who">;
function pantryLevel(value:number){return value>=3?"plenty":value>=2?"some":value>=1?"low":"out"}
const riceIds=new Set(["rice","jasmine-rice","basmati-rice"]);
function usesRice(r:(typeof recipes)[number]){return r.ingredients.some(i=>riceIds.has(i.id))}

export function Shell({children}:{children:React.ReactNode}){
 const path=usePathname();const h=useHousehold();const[ask,setAsk]=useState(false);const[q,setQ]=useState("");const[voiceState,setVoiceState]=useState<"idle"|"listening"|"unsupported">("idle");
 const[messages,setMessages]=useState<AskMessage[]>([{who:"home",text:"What do you need?"}]);
 const active=useMemo(()=>nav.find(x=>x.href==="/"?path==="/":path.startsWith(x.href))?.href,[path]);
 const cookingRoute=/^\/cook\/[^/]+\/cook$/.test(path);
 const day=(new Date().getDay()+6)%7;const tonight=getRecipe(h.week[day]??h.week[0])??recipes[0];
 const cameraMode=cookingRoute||path.startsWith("/prep")?"Prep":path.startsWith("/kitchen")?"Fridge":"Fridge";
 const cameraHref=`/scan?mode=${cameraMode}&back=${encodeURIComponent(path)}`;
 useEffect(()=>{bindGlobalHaptics();const openAsk=()=>setAsk(true);window.addEventListener("home-meals:ask",openAsk);return()=>window.removeEventListener("home-meals:ask",openAsk)},[]);useSheet(ask,()=>{setAsk(false);setVoiceState("idle")});
 const answer=(text:string):HomeReply=>{const s=text.toLowerCase();
  if((s.includes("how long")||s.includes("freezer life")||s.includes("storage guide")||s.includes("keep in the freezer")||s.includes("last in the freezer"))&&s.includes("freezer")){const named=prepComponents.find(x=>s.includes(x.code.toLowerCase())||s.includes(x.name.toLowerCase()));const activeBatches=h.prepBatches.filter(b=>(b.remainingMl??b.outputMl)>0).sort((a,b)=>new Date(a.at).getTime()-new Date(b.at).getTime());const target=named??(activeBatches[0]?prepComponents.find(x=>x.id===activeBatches[0].componentId):undefined);if(!target)return {text:"There isn’t a dated prep batch to check yet. Prep Day will create the first real freezer label.",href:"/prep/day",action:"Start Prep Day"};const guide=freezerGuide(target.id);const oldest=activeBatches.find(b=>b.componentId===target.id);if(!guide)return {text:`${target.code} has no freezer-life guide saved yet. I won’t invent one.`,tags:[target.name],href:target.kind==="mother"?`/prep/${target.id}`:"/prep",action:"Open prep guide"};const age=oldest?freezerAge(target.id,oldest.at):null;const batchNote=oldest&&age?` Oldest dated batch is ${age.ageDays===0?"from today":`${age.ageDays} ${age.ageDays===1?"day":"days"} old`}, with ${oldest.remainingMl??oldest.outputMl} ml left.`:" There is no dated batch for it right now.";return {text:`${target.code}: freezer guide ${guide.label}.${batchNote}`,tags:[target.name,age?.status==="past-lower-guide"?"Use first":age?.status==="approaching-guide"?"Use soon":"Freezer guide"],href:target.kind==="mother"?`/prep/${target.id}`:"/kitchen",action:target.kind==="mother"?"Open guide":"Open Freezer"}}
  const needsKitchen=s.includes("have")||s.includes("buy")||s.includes("shop")||s.includes("grocery")||s.includes("prep")||s.includes("freezer")||s.includes("pantry")||s.includes("staple")||s.includes("soon")||s.includes("low")||s.includes("make now")||s.includes("ready now");
  if(!h.kitchenReady&&needsKitchen)return {text:"I don't know the kitchen yet. Check Fridge, Freezer and Pantry once, then I can use the real stock.",href:"/kitchen",action:"Check Kitchen"};
  if(s.includes("no rice")||s.includes("without rice")||s.includes("doesn't want rice")||s.includes("does not want rice")){const options=recipes.filter(r=>!usesRice(r)).sort((a,b)=>{const avA=h.kitchenReady?recipeAvailability(a.id,h.componentStock,h.ingredientStock):null,avB=h.kitchenReady?recipeAvailability(b.id,h.componentStock,h.ingredientStock):null;const soonA=a.ingredients.filter(i=>h.useSoon[i.id]).length,soonB=b.ingredients.filter(i=>h.useSoon[i.id]).length;const rateA=Math.max(h.ratings[a.id]?.josh??0,h.ratings[a.id]?.g??0),rateB=Math.max(h.ratings[b.id]?.josh??0,h.ratings[b.id]?.g??0);return Number(!!avB?.ready)-Number(!!avA?.ready)||soonB-soonA||rateB-rateA||a.minutes-b.minutes}).slice(0,4);return {text:"No rice. These fit that and still favour what Home can cover, what needs using, and what we’ve liked.",mealIds:options.map(r=>r.id),href:"/cook",action:"See all recipes"}}
  if(s.includes("quick")||s.includes("fast")||s.includes("under 30")||s.includes("30 minutes")){const options=recipes.filter(r=>r.minutes<=30).sort((a,b)=>{const avA=h.kitchenReady?recipeAvailability(a.id,h.componentStock,h.ingredientStock):null,avB=h.kitchenReady?recipeAvailability(b.id,h.componentStock,h.ingredientStock):null;const soonA=a.ingredients.filter(i=>h.useSoon[i.id]).length,soonB=b.ingredients.filter(i=>h.useSoon[i.id]).length;const rateA=Math.max(h.ratings[a.id]?.josh??0,h.ratings[a.id]?.g??0),rateB=Math.max(h.ratings[b.id]?.josh??0,h.ratings[b.id]?.g??0);return Number(!!avB?.ready)-Number(!!avA?.ready)||soonB-soonA||rateB-rateA||a.minutes-b.minutes}).slice(0,4);return options.length?{text:"These are the best quick options right now.",mealIds:options.map(r=>r.id),href:"/cook",action:"Open our recipes"}:{text:"Nothing saved is under 30 minutes yet.",href:"/cook",action:"Open our recipes"}}
  if(s.includes("soon")||s.includes("go bad")||s.includes("expire")){const a=Object.keys(h.useSoon).filter(id=>h.useSoon[id]&&(h.ingredientStock[id]??0)>0).map(id=>getIngredient(id)?.name).filter(Boolean) as string[];return a.length?{text:`${a.length} ${a.length===1?"thing needs":"things need"} using first.`,tags:a.slice(0,6),href:"/plan",action:"Fit into the week"}:{text:"Nothing is marked use soon.",href:"/kitchen",action:"Check the fridge"}}
  if((s.includes("oldest")||s.includes("use first")||s.includes("fifo")||s.includes("first from freezer"))&&(s.includes("freezer")||s.includes("prep")||s.includes("batch"))){const oldest=h.prepBatches.filter(b=>(b.remainingMl??b.outputMl)>0).sort((a,b)=>new Date(a.at).getTime()-new Date(b.at).getTime())[0];if(!oldest)return {text:"There are no dated prep batches in the freezer yet.",href:"/prep/day",action:"Start Prep Day"};const c=prepComponents.find(x=>x.id===oldest.componentId);const age=Math.max(0,Math.floor((Date.now()-new Date(oldest.at).getTime())/86400000));const made=new Date(oldest.at).toLocaleDateString(undefined,{day:"numeric",month:"short"});return {text:`Use ${c?.code??oldest.componentId} first: ${oldest.remainingMl??oldest.outputMl} ml left, made ${made}${age?` (${age} ${age===1?"day":"days"} ago)`:" today"}.`,tags:c?[c.name,"FIFO"]:["FIFO"],href:"/kitchen",action:"Open Freezer"}}
  if(s.includes("tonight")||s.includes("eat tonight")){const a=recipeAvailability(tonight.id,h.componentStock,h.ingredientStock);const missing=a.missingPrep.length+a.missingIngredients.length;return {text:`${tonight.minutes} minutes. ${!h.kitchenReady?"Check Kitchen if you want me to confirm the stock.":a.ready?"We have everything for it.":`${missing} ${missing===1?"thing is":"things are"} still missing.`}`,mealIds:[tonight.id],href:a.ready?`/cook/${tonight.id}/cook`:`/cook/${tonight.id}`,action:a.ready?"Cook now":"Open recipe"}}
  if(s.includes("make now")||s.includes("ready now")||s.includes("what can we make")){const ready=recipes.filter(r=>recipeAvailability(r.id,h.componentStock,h.ingredientStock).ready).sort((a,b)=>{const soonA=a.ingredients.filter(i=>h.useSoon[i.id]).length,soonB=b.ingredients.filter(i=>h.useSoon[i.id]).length;const rateA=Math.max(h.ratings[a.id]?.josh??0,h.ratings[a.id]?.g??0),rateB=Math.max(h.ratings[b.id]?.josh??0,h.ratings[b.id]?.g??0);return soonB-soonA||Number(!!h.favourites[b.id])-Number(!!h.favourites[a.id])||rateB-rateA||a.minutes-b.minutes}).slice(0,4);return ready.length?{text:`${ready.length} good options are fully covered from home.`,mealIds:ready.map(r=>r.id),href:"/cook/builder",action:"See everything ready"}:{text:"Nothing is fully covered right now.",href:"/plan",action:"See what’s missing"}}
  if(s.includes("buy")||s.includes("shop")||s.includes("grocery")){const a=h.shoppingNeeds.slice(0,6).map(x=>getIngredient(x.id)?.name).filter(Boolean) as string[];return a.length?{text:`${h.shoppingNeeds.length} ${h.shoppingNeeds.length===1?"thing":"things"} to buy for the current week.`,tags:a,href:"/plan",action:"Open shopping list"}:{text:"We have what this week needs.",href:"/plan",action:"View the week"}}
  if(s.includes("low")||s.includes("running low")||s.includes("pantry")||s.includes("staple")){const low=ingredients.filter(i=>i.tracking==="state"&&(h.ingredientStock[i.id]??0)===1);const out=ingredients.filter(i=>i.tracking==="state"&&(h.ingredientStock[i.id]??0)<=0&&h.week.some(rid=>getRecipe(rid).ingredients.some(req=>req.id===i.id&&!req.optional)));return low.length?{text:`${low.length} pantry ${low.length===1?"staple is":"staples are"} running low. They still count as available, but they’re worth checking before the next shop.`,tags:low.slice(0,6).map(i=>i.name),href:"/kitchen",action:"Open Pantry"}:out.length?{text:`No tracked staple is merely low, but ${out.length} ${out.length===1?"one is":"are"} out for this week.`,tags:out.slice(0,6).map(i=>i.name),href:"/plan",action:"Open shopping list"}:{text:"Pantry levels look fine for the current week.",href:"/kitchen",action:"Open Pantry"}}
  if(s.includes("prep")||s.includes("freezer")){const a=h.prepNeeds.slice(0,6).map(x=>{const c=prepComponents.find(y=>y.id===x.id);return c?`${c.code} · ${x.shortMl} ml`:""}).filter(Boolean);return a.length?{text:`${h.prepNeeds.length} ${h.prepNeeds.length===1?"prep job is":"prep jobs are"} short for this week.`,tags:a,href:"/prep/day",action:"Start Prep Day"}:{text:"The freezer covers this week.",href:"/prep",action:"Open Prep"}}
  if(s.includes("favourite")||s.includes("favorite")||s.includes("we like")){const a=recipes.filter(r=>h.favourites[r.id]||(h.ratings[r.id]?.josh??0)>=4||(h.ratings[r.id]?.g??0)>=4).sort((a,b)=>Math.max(h.ratings[b.id]?.josh??0,h.ratings[b.id]?.g??0)-Math.max(h.ratings[a.id]?.josh??0,h.ratings[a.id]?.g??0)).slice(0,4);return a.length?{text:"These are the dinners we’ve liked most so far.",mealIds:a.map(x=>x.id),href:"/cook",action:"Our recipes"}:{text:"We haven't marked any favourites yet.",href:"/cook",action:"Choose a recipe"}}
  if(s.includes("last")&&(s.includes("cook")||s.includes("meal")||s.includes("dinner")||s.includes("time"))){const last=h.history[0]?getRecipe(h.history[0].mealId):null;const version=last?(h.recipeVersions[last.id]?.[0]?.number??1):1;return last?{text:h.recipeNotes[last.id]?.[0]?`Last note on our v${version}: “${h.recipeNotes[last.id][0].text}”`:`The last dinner logged was our v${version}.`,mealIds:[last.id],href:`/cook/${last.id}`,action:"Open our version"}:{text:"We haven't logged a dinner yet.",href:"/cook",action:"Choose dinner"}}
  if(s.includes("this week")||s.includes("week plan")){return {text:"Here’s the current week. Swap any day and groceries + prep recalculate with it.",mealIds:h.week.slice(0,4),href:"/plan",action:"Open full week"}}
  const component=prepComponents.find(x=>s.includes(x.code.toLowerCase())||s.includes(x.name.toLowerCase()));if(component)return h.kitchenReady?{text:`${component.code}: ${h.componentStock[component.id]??0} ml in the freezer.`,tags:[component.name],href:"/prep",action:"Open Prep"}:{text:"Check the freezer first and I can tell you.",href:"/kitchen",action:"Check freezer"};
  const ingredient=ingredients.find(x=>s.includes(x.name.toLowerCase())||s.includes(x.id.replace(/-/g," ")));if(ingredient){const n=h.ingredientStock[ingredient.id]??0;const state=ingredient.tracking==="state"?pantryLevel(n):n>0?formatQty(n,ingredient.unit):"out";return {text:`${ingredient.name}: ${state}.`,tags:h.useSoon[id]?.at?["Use soon"]:ingredient.tracking==="state"&&n===1?["Running low"]:undefined,href:"/kitchen",action:"Open Kitchen"}}
  if(s.includes("have")||s.includes("at home")||s.includes("kitchen")){const stockedIngredients=ingredients.filter(x=>(h.ingredientStock[x.id]??0)>0).length;const stockedMothers=prepComponents.filter(x=>x.kind==="mother"&&(h.componentStock[x.id]??0)>0).length;const soon=Object.keys(h.useSoon).filter(id=>h.useSoon[id]?.at&&(h.ingredientStock[id]??0)>0).length;const low=ingredients.filter(i=>i.tracking==="state"&&(h.ingredientStock[i.id]??0)===1).length;const tags:string[]=[];if(soon)tags.push(`${soon} use soon`);if(low)tags.push(`${low} pantry low`);if(!tags.length)tags.push("Nothing urgent");return {text:`At home: ${stockedIngredients} tracked ingredients and ${stockedMothers}/8 mother bases stocked.`,tags,href:"/kitchen",action:"Open Kitchen"};}
  return {text:"Ask me about tonight, quick or no-rice dinners, freezer life, what we have, what can be made now, groceries, pantry levels, prep, use-soon food, favourites, or the last dinner."};
 }
 const send=(text=q)=>{const clean=text.trim();if(!clean)return;const reply=answer(clean);setMessages(v=>[...v,{who:"you",text:clean},{who:"home",...reply}]);setQ("");feedback("change")};
 const startVoice=()=>{
  setAsk(true);feedback("tap");
  const W=window as typeof window & {SpeechRecognition?:new()=>any;webkitSpeechRecognition?:new()=>any};
  const Recognition=W.SpeechRecognition||W.webkitSpeechRecognition;
  if(!Recognition){setVoiceState("unsupported");setMessages(v=>[...v,{who:"home",text:"Voice input isn’t available in this browser yet. You can still type or show me something with the camera."}]);return;}
  const rec=new Recognition();rec.lang="en-SG";rec.interimResults=false;rec.maxAlternatives=1;
  rec.onstart=()=>setVoiceState("listening");
  rec.onresult=(e:any)=>{const text=e.results?.[0]?.[0]?.transcript??"";setVoiceState("idle");if(text)send(text)};
  rec.onerror=()=>setVoiceState("idle");rec.onend=()=>setVoiceState(v=>v==="listening"?"idle":v);rec.start();
 };
 return <div className="hm-shell-v5 hm-shell-v6">
  {cookingRoute?<div className="hm-main-v5">{children}</div>:<main className="hm-main-v5">{children}</main>}
  {h.storageIssue&&<div className="hm-storage-warning-v5" role="status"><span><strong>Changes aren’t saving on this device.</strong><small>Keep this tab open and try again before closing Home Meals.</small></span><button onClick={h.clearStorageIssue} aria-label="Dismiss save warning">×</button></div>}
  {!cookingRoute&&<>
   <nav className="hm-nav-v5 hm-nav-v6" aria-label="Main navigation">{nav.map(item=>{const current=active===item.href;return <Link href={item.href} key={item.href} className={current?"active":""} aria-current={current?"page":undefined}><Icon name={item.icon} size={22}/><span>{item.label}</span></Link>})}</nav>
   <div className="hm-home-tools-v6" aria-label="Home inputs">
    <Link href={cameraHref} className="hm-input-orb-v6 camera" aria-label="Show Home with camera"><Icon name="camera" size={23}/></Link>
    <button className="hm-ask-orb-v6" onClick={()=>setAsk(true)} aria-label="Ask Home"><Icon name="spark" size={24}/><span>Ask Home</span></button>
    <button className={`hm-input-orb-v6 mic ${voiceState==="listening"?"listening":""}`} onClick={startVoice} aria-label={voiceState==="listening"?"Listening to Home":"Talk to Home"}><Icon name="mic" size={23}/></button>
   </div>
  </>}
  {ask&&<div className="hm-sheet-backdrop-v5" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setAsk(false)}}><section className="hm-sheet-v5 hm-ask-sheet-v5 hm-ask-sheet-v6 hm-ask-sheet-v10" role="dialog" aria-modal="true" aria-label="Ask Home">
   <div className="hm-sheet-handle-v5"/><header><div><span>HOME</span><h2>Ask Home</h2><p>Camera, voice or text. It all uses the same kitchen, plan and cookbook.</p></div><button className="hm-icon-button-v5" onClick={()=>setAsk(false)} aria-label="Close">×</button></header>
   <div className="hm-ask-modes-v6"><Link href={cameraHref} onClick={()=>setAsk(false)}><Icon name="camera" size={20}/><span><strong>Show</strong><small>fridge, prep, receipt</small></span></Link><button className="active" aria-pressed="true" onClick={()=>document.querySelector<HTMLInputElement>(".hm-composer-v5 input")?.focus()}><Icon name="spark" size={20}/><span><strong>Ask</strong><small>what should we do?</small></span></button><button className={voiceState==="listening"?"active":""} aria-pressed={voiceState==="listening"} onClick={startVoice}><Icon name="mic" size={20}/><span><strong>{voiceState==="listening"?"Listening…":"Tell"}</strong><small>hands-free input</small></span></button></div>
   <div className="hm-ask-context-v5"><div><span>Tonight</span><strong>{recipeTitle(tonight.id,tonight.title)}</strong></div><Link href={`/cook/${tonight.id}`} onClick={()=>setAsk(false)}>Open</Link></div>
   <div className="hm-ask-messages-v5 hm-ask-messages-v10" tabIndex={0} aria-label="Ask Home conversation" aria-live="polite">{messages.slice(-6).map((m,i)=><div key={i} className={m.who}><p>{m.text}</p>{m.tags&&<div className="hm-ask-tags-v10">{m.tags.filter(Boolean).map(tag=><span key={tag}>{tag}</span>)}</div>}{m.mealIds&&<div className="hm-ask-meals-v10">{m.mealIds.map(id=>{const r=getRecipe(id);const title=recipeTitle(r.id,r.title);return <Link key={id} href={`/cook/${id}`} onClick={()=>setAsk(false)}>{r.image?<img src={r.image} alt={title}/>:<i/>}<span><strong>{title}</strong><small>{r.minutes} min · {r.cuisine}</small></span><b>›</b></Link>})}</div>}{m.href&&m.action&&<Link className="hm-ask-action-v10" href={m.href} onClick={()=>setAsk(false)}>{m.action} <b>→</b></Link>}</div>)}</div>
   <div className="hm-ask-quick-v5"><button onClick={()=>send("What should we cook tonight?")}>Tonight</button><button onClick={()=>send("What can we make now?")}>Ready now</button><button onClick={()=>send("Something quick under 30 minutes")}>Quick</button><button onClick={()=>send("G doesn't want rice")}>No rice</button><button onClick={()=>send("How long will the oldest batch last in the freezer?")}>Freezer life</button><button onClick={()=>send("What should we use soon?")}>Use soon</button><button onClick={()=>send("What is running low in the pantry?")}>Low stock</button><button onClick={()=>send("What should we prep?")}>Prep</button></div>
   <form className="hm-composer-v5" onSubmit={e=>{e.preventDefault();send()}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ask about home…" aria-label="Ask Home" autoFocus/><button aria-label="Send"><Icon name="arrow" size={18}/></button></form>
  </section></div>}
 </div>
}