"use client";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {useEffect,useState} from "react";
import {useHousehold} from "../HouseholdState";
import {AskHomeView,type AskMessage} from "../AskHomeView";
import {prepComponents} from "@/data/home-data";
import {allLiveRecipesV7 as recipes,getLiveRecipeV7} from "@/data/recipe-catalog-v7";
import {ingredientUiCatalogV7 as ingredients,ingredientUiNameV7} from "@/data/ingredient-ui-v7";
import {ingredientsForRecipeV7,canonicalIngredientIdForRuntimeV7} from "@/data/ingredient-engine-v7";
import {recipeTitle} from "@/data/recipe-display";
import {recipeAvailabilityV7} from "@/data/stock-math-v7";
import {getCanonicalPrepV2} from "@/data/food-truth-v2";
import {freezerAge,freezerGuide} from "@/data/freezer-guide";
import {formatQty} from "./Primitives";
import {bindGlobalHaptics,feedback} from "@/lib/feedback";
import {useSheet} from "@/lib/useSheet";

type HomeReply=Omit<AskMessage,"who">;
const quick=[{label:"Tonight",text:"What should we cook tonight?"},{label:"Ready now",text:"What can we make now?"},{label:"Under 30 min",text:"Something quick under 30 minutes"},{label:"No rice",text:"G doesn't want rice"},{label:"Use soon",text:"What should we use soon?"},{label:"Freezer life",text:"How long will the oldest batch last in the freezer?"},{label:"Low stock",text:"What is running low in the pantry?"},{label:"Prep",text:"What should we prep?"}];
function pantryLevel(value:number){return value>=3?"plenty":value>=2?"some":value>=1?"low":"out"}
function recipeIngredientIds(id:string){return ingredientsForRecipeV7(id).map(canonicalIngredientIdForRuntimeV7)}
function usesRice(id:string){return recipeIngredientIds(id).some(x=>x.includes("rice")&&!x.includes("vinegar")&&!x.includes("wine"))}
function usesSoonCount(id:string,useSoon:Record<string,boolean>){return recipeIngredientIds(id).filter(x=>useSoon[x]).length}
function componentMention(text:string,component:(typeof prepComponents)[number]){const name=component.name.toLowerCase();if(text.includes(name))return true;const code=component.code.toLowerCase();if(code.length<3)return false;const escaped=code.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return new RegExp(`(^|[^a-z0-9])${escaped}([^a-z0-9]|$)`).test(text)}

export function Shell({children}:{children:React.ReactNode}){
 const path=usePathname(),h=useHousehold(),[ask,setAsk]=useState(false),[q,setQ]=useState("");
 const[messages,setMessages]=useState<AskMessage[]>([{who:"home",text:"What do you need? Tonight, something quick, what needs using — or just say it."}]);
 const cookingRoute=/^\/cook\/[^/]+\/cook$/.test(path),day=(new Date().getDay()+6)%7,tonight=getLiveRecipeV7(h.week[day]??h.week[0])??recipes[0];
 const cameraMode=cookingRoute||path.startsWith("/prep")?"Prep":"Fridge",cameraHref=`/scan?mode=${cameraMode}&back=${encodeURIComponent(path)}`;
 useEffect(()=>{bindGlobalHaptics();const openAsk=()=>setAsk(true);window.addEventListener("home-meals:ask",openAsk);return()=>window.removeEventListener("home-meals:ask",openAsk)},[]);useSheet(ask,()=>setAsk(false));
 const answer=(text:string):HomeReply=>{const s=text.toLowerCase(),mentionedComponent=()=>prepComponents.find(x=>componentMention(s,x));
  if((s.includes("how long")||s.includes("freezer life")||s.includes("storage guide")||s.includes("keep in the freezer")||s.includes("last in the freezer"))&&s.includes("freezer")){const named=mentionedComponent(),activeBatches=h.prepBatches.filter(b=>b.remaining.qty>0).sort((a,b)=>new Date(a.at).getTime()-new Date(b.at).getTime()),target=named??(activeBatches[0]?prepComponents.find(x=>x.id===activeBatches[0].componentId):undefined);if(!target)return{text:"There isn’t a dated prep batch to check yet. Prep Day will create the first real freezer label.",href:"/prep/day",action:"Start Prep Day"};const guide=freezerGuide(target.id),oldest=activeBatches.find(b=>b.componentId===target.id);if(!guide)return{text:`${target.code} has no freezer-life guide saved yet. I won’t invent one.`,tags:[target.name],href:target.kind==="mother"?`/prep/${target.id}`:"/prep",action:"Open prep guide"};const age=oldest?freezerAge(target.id,oldest.at):null,batchNote=oldest&&age?` Oldest dated batch is ${age.ageDays===0?"from today":`${age.ageDays} ${age.ageDays===1?"day":"days"} old`}, with ${formatQty(oldest.remaining.qty,oldest.remaining.unit)} left.`:" There is no dated batch for it right now.";return{text:`${target.code}: freezer guide ${guide.label}.${batchNote}`,tags:[target.name,age?.status==="past-lower-guide"?"Use first":age?.status==="approaching-guide"?"Use soon":"Freezer guide"],href:target.kind==="mother"?`/prep/${target.id}`:"/kitchen",action:target.kind==="mother"?"Open guide":"Open Freezer"}}
  const needsKitchen=s.includes("have")||s.includes("buy")||s.includes("shop")||s.includes("grocery")||s.includes("prep")||s.includes("freezer")||s.includes("pantry")||s.includes("staple")||s.includes("soon")||s.includes("low")||s.includes("make now")||s.includes("ready now");
  if(!h.kitchenReady&&needsKitchen)return{text:"I don't know the kitchen yet. Check Fridge, Freezer and Pantry once, then I can use the real stock.",href:"/kitchen",action:"Check Kitchen"};
  const rank=(a:(typeof recipes)[number],b:(typeof recipes)[number])=>{const avA=h.kitchenReady?recipeAvailabilityV7(a.id,h.componentStock,h.ingredientStock):null,avB=h.kitchenReady?recipeAvailabilityV7(b.id,h.componentStock,h.ingredientStock):null,soonA=usesSoonCount(a.id,h.useSoon),soonB=usesSoonCount(b.id,h.useSoon),rateA=Math.max(h.ratings[a.id]?.josh??0,h.ratings[a.id]?.g??0),rateB=Math.max(h.ratings[b.id]?.josh??0,h.ratings[b.id]?.g??0);return Number(!!avB?.ready)-Number(!!avA?.ready)||soonB-soonA||Number(!!h.favourites[b.id])-Number(!!h.favourites[a.id])||rateB-rateA||a.minutes-b.minutes};
  if(s.includes("no rice")||s.includes("without rice")||s.includes("doesn't want rice")||s.includes("does not want rice")){const options=recipes.filter(r=>!usesRice(r.id)).sort(rank).slice(0,4);return{text:"No rice. These fit that and still favour what Home can cover, what needs using, and what we’ve liked.",mealIds:options.map(r=>r.id),href:"/cook",action:"See all recipes"}}
  if(s.includes("quick")||s.includes("fast")||s.includes("under 30")||s.includes("30 minutes")){const options=recipes.filter(r=>r.minutes<=30).sort(rank).slice(0,4);return options.length?{text:"These are the best quick options right now.",mealIds:options.map(r=>r.id),href:"/cook",action:"Open our recipes"}:{text:"Nothing saved is under 30 minutes yet.",href:"/cook",action:"Open our recipes"}}
  if(s.includes("soon")||s.includes("go bad")||s.includes("expire")){const a=Object.keys(h.useSoon).filter(id=>h.useSoon[id]&&(h.ingredientStock[id]??0)>0).map(ingredientUiNameV7).filter(Boolean);return a.length?{text:`${a.length} ${a.length===1?"thing needs":"things need"} using first.`,tags:a.slice(0,6),href:"/plan",action:"Fit into the week"}:{text:"Nothing is marked use soon.",href:"/kitchen",action:"Check the fridge"}}
  if((s.includes("oldest")||s.includes("use first")||s.includes("fifo")||s.includes("first from freezer"))&&(s.includes("freezer")||s.includes("prep")||s.includes("batch"))){const oldest=h.prepBatches.filter(b=>b.remaining.qty>0).sort((a,b)=>new Date(a.at).getTime()-new Date(b.at).getTime())[0];if(!oldest)return{text:"There are no dated prep batches in the freezer yet.",href:"/prep/day",action:"Start Prep Day"};const c=prepComponents.find(x=>x.id===oldest.componentId),age=Math.max(0,Math.floor((Date.now()-new Date(oldest.at).getTime())/86400000)),made=new Date(oldest.at).toLocaleDateString(undefined,{day:"numeric",month:"short"});return{text:`Use ${c?.code??oldest.componentId} first: ${formatQty(oldest.remaining.qty,oldest.remaining.unit)} left, made ${made}${age?` (${age} ${age===1?"day":"days"} ago)`:" today"}.`,tags:c?[c.name,"FIFO"]:["FIFO"],href:"/kitchen",action:"Open Freezer"}}
  if(s.includes("tonight")||s.includes("eat tonight")){const a=recipeAvailabilityV7(tonight.id,h.componentStock,h.ingredientStock),missing=a.missingPrep.length+a.missingIngredients.length;return{text:`${tonight.minutes} minutes. ${!h.kitchenReady?"Check Kitchen if you want me to confirm the stock.":a.ready?"We have everything for it.":`${missing} ${missing===1?"thing is":"things are"} still missing.`}`,mealIds:[tonight.id],href:a.ready?`/cook/${tonight.id}/cook`:`/cook/${tonight.id}`,action:a.ready?"Cook now":"Open recipe"}}
  if(s.includes("make now")||s.includes("ready now")||s.includes("what can we make")){const ready=recipes.filter(r=>recipeAvailabilityV7(r.id,h.componentStock,h.ingredientStock).ready).sort(rank).slice(0,4);return ready.length?{text:`${ready.length} good options are fully covered from home.`,mealIds:ready.map(r=>r.id),href:"/cook/builder",action:"See everything ready"}:{text:"Nothing is fully covered right now.",href:"/plan",action:"See what’s missing"}}
  if(s.includes("buy")||s.includes("shop")||s.includes("grocery")){const a=h.shoppingNeeds.slice(0,6).map(x=>ingredientUiNameV7(x.canonicalId)).filter(Boolean);return a.length?{text:`${h.shoppingNeeds.length} ${h.shoppingNeeds.length===1?"thing":"things"} to buy for the current week.`,tags:a,href:"/plan",action:"Open shopping list"}:{text:"We have what this week needs.",href:"/plan",action:"View the week"}}
  if(s.includes("low")||s.includes("running low")||s.includes("pantry")||s.includes("staple")){const low=ingredients.filter(i=>i.tracking==="state"&&(h.ingredientStock[i.id]??0)===1),out=ingredients.filter(i=>i.tracking==="state"&&(h.ingredientStock[i.id]??0)<=0&&h.week.some(rid=>recipeIngredientIds(rid).includes(i.id)));return low.length?{text:`${low.length} pantry ${low.length===1?"staple is":"staples are"} running low.`,tags:low.slice(0,6).map(i=>i.name),href:"/kitchen",action:"Open Pantry"}:out.length?{text:`No tracked staple is merely low, but ${out.length} ${out.length===1?"one is":"are"} out for this week.`,tags:out.slice(0,6).map(i=>i.name),href:"/plan",action:"Open shopping list"}:{text:"Pantry levels look fine for the current week.",href:"/kitchen",action:"Open Pantry"}}
  if(s.includes("prep")||s.includes("freezer")){const a=h.prepNeeds.slice(0,6).map(x=>{const c=prepComponents.find(y=>y.id===x.id);return c?`${c.code} · ${formatQty(x.shortQty,x.unit)}`:""}).filter(Boolean);return a.length?{text:`${h.prepNeeds.length} ${h.prepNeeds.length===1?"prep job is":"prep jobs are"} short for this week.`,tags:a,href:"/prep/day",action:"Start Prep Day"}:{text:"The freezer covers this week.",href:"/prep",action:"Open Prep"}}
  if(s.includes("favourite")||s.includes("favorite")||s.includes("we like")){const a=recipes.filter(r=>h.favourites[r.id]||(h.ratings[r.id]?.josh??0)>=4||(h.ratings[r.id]?.g??0)>=4).sort(rank).slice(0,4);return a.length?{text:"These are the dinners we’ve liked most so far.",mealIds:a.map(x=>x.id),href:"/cook",action:"Our recipes"}:{text:"We haven't marked any favourites yet.",href:"/cook",action:"Choose a recipe"}}
  if(s.includes("last")&&(s.includes("cook")||s.includes("meal")||s.includes("dinner")||s.includes("time"))){const last=h.history[0]?getLiveRecipeV7(h.history[0].mealId):null,version=last?(h.recipeVersions[last.id]?.[0]?.number??1):1;return last?{text:h.recipeNotes[last.id]?.[0]?`Last note on our v${version}: “${h.recipeNotes[last.id][0].text}”`:`The last dinner logged was our v${version}.`,mealIds:[last.id],href:`/cook/${last.id}`,action:"Open our version"}:{text:"We haven't logged a dinner yet.",href:"/cook",action:"Choose dinner"}}
  if(s.includes("this week")||s.includes("week plan"))return{text:"Here’s the current week. Swap any day and groceries + prep recalculate with it.",mealIds:h.week.slice(0,4),href:"/plan",action:"Open full week"};
  const component=mentionedComponent();if(component){const truth=getCanonicalPrepV2(component.id);return h.kitchenReady?{text:truth?`${component.code}: ${formatQty(h.componentStock[component.id]??0,truth.workingUnit.unit)} in the freezer.`:`${component.code}: no current quantity model saved.`,tags:[component.name],href:"/prep",action:"Open Prep"}:{text:"Check the freezer first and I can tell you.",href:"/kitchen",action:"Check freezer"}}
  const ingredient=ingredients.find(x=>s.includes(x.name.toLowerCase())||s.includes(x.id.replace(/-/g," ")));if(ingredient){const n=h.ingredientStock[ingredient.id]??0,state=ingredient.tracking==="state"?pantryLevel(n):n>0?formatQty(n,ingredient.unit):"out";return{text:`${ingredient.name}: ${state}.`,tags:h.useSoon[ingredient.id]?["Use soon"]:ingredient.tracking==="state"&&n===1?["Running low"]:undefined,href:"/kitchen",action:"Open Kitchen"}}
  if(s.includes("have")||s.includes("at home")||s.includes("kitchen")){const stockedIngredients=ingredients.filter(x=>(h.ingredientStock[x.id]??0)>0).length,stockedMothers=prepComponents.filter(x=>x.kind==="mother"&&(h.componentStock[x.id]??0)>0).length,soon=Object.keys(h.useSoon).filter(id=>h.useSoon[id]&&(h.ingredientStock[id]??0)>0).length,low=ingredients.filter(i=>i.tracking==="state"&&(h.ingredientStock[i.id]??0)===1).length,tags:string[]=[];if(soon)tags.push(`${soon} use soon`);if(low)tags.push(`${low} pantry low`);if(!tags.length)tags.push("Nothing urgent");return{text:`At home: ${stockedIngredients} tracked ingredients and ${stockedMothers}/8 mother bases stocked.`,tags,href:"/kitchen",action:"Open Kitchen"}}
  return{text:"Ask me about tonight, quick or no-rice dinners, freezer life, what we have, what can be made now, groceries, pantry levels, prep, use-soon food, favourites, or the last dinner."};
 };
 const send=(text=q)=>{const clean=text.trim();if(!clean)return;const reply=answer(clean);setMessages(v=>[...v,{who:"you",text:clean},{who:"home",...reply}]);setQ("");feedback("change")};
 return <div className="hm-shell">
  {cookingRoute?<div className="hm-main cooking">{children}</div>:<main className="hm-main">{children}</main>}
  {h.storageIssue&&<div className="hm-warning" role="status"><span><strong>Changes aren’t saving on this device.</strong><small>Keep this tab open and try again before closing Home Meals.</small></span><button onClick={h.clearStorageIssue} aria-label="Dismiss save warning">×</button></div>}
  {ask&&<div data-local=""><AskHomeView messages={messages} q={q} setQ={setQ} onSend={send} onClose={()=>setAsk(false)} cameraHref={cameraHref} quick={quick}/></div>}
 </div>;
}
